### ISSUE TITLE
Move 'Your institution' button below email/pwd fields on sign in form

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#1028]
Make the 'Your Institution' button less prominent on the sign-in form. Move it so that it is below the email and password section.

**Comment by sjDCC** [comment]
That looks great! Thanks @briri 

Seeing this screengrab reminds me of the other css refinements ticket #867. I'd asked for the coloured background to stop at the end of the buttons so they look more like tabs.

I can't see this scheduled/assigned in the gannt chart but it will be an important one for user recognition / adoption. Is this something we can prioritise @stephaniesimms

**Comment by briri** [comment]
I think we should review that ticket. We'll each be doing some work to brand the shared codebase for our respective tools, so I would like to determine which requests should be handled at the shared code level versus in our own branding customizations. (e.g. button alignment seems to be something useful for all, but maybe others are not)

**Comment by sjDCC** [comment]
Ok, perhaps @stephaniesimms and I can review it then? I'd assume she was ok with them all since she copied them into a new ticket.

I'd like to keep as much as possible in the common code base so that looks polished too and limit local branding to colours etc. The things I suggested here were not DMPonline specific, rather general button placement, layout and looks and feel improvements.

**Comment by sjDCC** [comment]
The change on the sign in area looks good so closing this ticket out.

@stephaniesimms and I have liaised on the CSS and @jollopre will make changes in #867
