### ISSUE TITLE
ajax calls on plans page not working after pagination link is clicked

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#1040]
The ajax wired to individual rows of the plans table no longer work after one of the pagination links reloads the DOM.

**Comment by briri** [comment]
@jollopre here is the ticket I mentioned in Slack.

I think if would be good if we could register a callback for the paginable.js `ajax:complete` events (pagination and search). @bhavi is running into a similar issue on the users page.

**Comment by jollopre** [comment]
After introducing paginable into the codebase, any HTML within that context gets replaced when the user clicks in View All, View Less or X page. This issue is raised against a directly-bound hander associated to checkbox for setting a plan for a test:(https://github.com/DMPRoadmap/roadmap/blob/development/lib/assets/javascripts/views/plans/index.js#L10).

In order to solve this problem, we have to change directly-bound handlers within .paginable context using delegated handlers. Using delegated event handlers helps to:
- avoid adding and removing events whenever any paginable event is triggered since it changes its children DOM when AJAX succeeds. 
- improves performance since we attach an event handler to just one element (e.g. paginable context instead of one for each plan checkbox created for setting the visibility to test)

**Comment by stephaniesimms** [comment]
I'm assuming this was for the My Dashboard plans tables. Tables on that page are working as expected now. Pagination and search box are not yet implemented on Admin Plans page, but should be addressed in another issue #1055
