### ISSUE TITLE
Add a 'View all search results' link if entries go over 1 page

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#1052]
Currently the 'View all' button takes users back to the full data, not the search results. A a "View all search results" option too if search results go over 1 page.

![capture](https://user-images.githubusercontent.com/6169940/35002674-5545d870-fae2-11e7-8d53-74015586ea85.PNG)

**Comment by jollopre** [comment]
The PR #1057 add the functionality requested. The links underneath any paginable table are presented as follow whenever an user click search:
- View All search results followed by Clear search results (when paginable is enabled)
- View less search results (when all the search results are presented)

Note, I have replaced "View All" by "Clear search results" since:
1. Permits the user go back to the initial table rendered
2. Discourages presenting the entire set of table results (which reduces server burden)

@sjDCC, @stephaniesimms, please let us know if you are happy with the change.

**Comment by sjDCC** [comment]
Sounds fine. Will comment in full when PR accepted and can see this deployed. Thanks @jollopre

**Comment by stephaniesimms** [comment]
appears to be working as expected. closing and leaving here for @sjDCC to test.

**Comment by sjDCC** [comment]
Looks great - thanks @jollopre Removing from board
