### ISSUE TITLE
Hide language switcher if only one language installed

### ISSUE THREAD

**Issue by vyruss** [DMPRoadmap/roadmap#110]
- Related to #98 
- If only one language exists in database, hide language switcher from Front Page/User Profile

**Comment by jollopre** [comment]
I have created a new initialiser which contains two constants. Despite the fact that having global variables is not a best practice, I don't currently know any other way to avoid hitting the database to retrieve all the languages available at any single request made. I'm open to suggestions.

**Comment by briri** [comment]
Perhaps this is a case where we should use some low level caching. http://edgeguides.rubyonrails.org/caching_with_rails.html#low-level-caching

I think the constant approach will work but I think that if a language is added/removed then the application would need to be restarted in order for the constant to be updated.

Note that caching is turned off in development mode by default. You would need to update your config/environments/development.rb to enable it.

**Comment by briri** [comment]
It looks like Rails 5 has a better caching option for ActiveRecord collections though. They're 5.1 though is still in beta :/
http://blog.bigbinary.com/2016/02/02/activerecord-relation-cache-key.html

**Comment by jollopre** [comment]
@briri before the latest commit the app supposed to cache that query :) (e.g. https://github.com/DigitalCurationCentre/roadmap/commit/5d9b810fd770e2c87fa226e5905f22f362241c24#diff-55c5b7aecfb519d0e4880eaf2788eb6eL26) according to the low-level-caching for production. 

I can revert those bits but I've just noticed that if we want to add a new languages without restarting, we will need to replicate https://github.com/DigitalCurationCentre/roadmap/blob/development/config/initializers/fast_gettext.rb#L17 into application_controller in order to update the set of available locales

**Comment by briri** [comment]
That makes sense @jollopre. Setting the fast_gettext.default_available_locales in the application controller would be a better choice

**Comment by raycarrick-ed** [comment]
Removed all but default from the languages table. Languages menu disappears. Looks good.

**Comment by stephaniesimms** [comment]
thanks to @briri for enabling testing on roadmap stage—looks good to me. closing this out.
