### ISSUE TITLE
Adjust create plan logic to present correct templates

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#1102]
- If a user selects a Funder for question 3 then they should only be presented with funder templates (in most cases there is only one funder template). Current behavior includes Org templates in a dropdown menu - these should only be displayed if user ticks the box that no funder is associated. 

![default-template-logic](https://user-images.githubusercontent.com/12703638/35573440-06797cf6-058c-11e8-9e26-7a9de049f9e0.png)

**Comment by sjDCC** [comment]
Part 2 of this logic is incorrect @stephaniesimms The default template does not appear in the dropdown for selection. It is only given when no funder and no org template applies.

**Comment by stephaniesimms** [comment]
thanks @sjDCC - i updated the issue accordingly and pinged @briri who diagrammed it out and plans to fix this one

**Comment by stephaniesimms** [comment]
all template logic seems to be working now except for one thing @briri :
- if I select USGS as my Org AND as my funder I should see a dropdown that contains both internal and the public template. current behavior only displays the public template.

![screen shot 2018-02-08 at 5 06 01 pm](https://user-images.githubusercontent.com/12703638/36006589-b16191d6-0cf2-11e8-9461-29d253dbd99b.png)

**Comment by briri** [comment]
Ok. New finalized logic for the create plan template selection code:

Logic:
- Default template is used if 
  - User ticks both the 'no research org' and 'no funder' boxes 
  - User selects a Research Org that has NO templates and ticks the 'no funder' box
  - User selects a Research Org that has NO templates and a funder that has NO templates
  - User ticks the 'no Research Org' box and selects a funder that has NO templates
  - User selects a Research Org that has template(s) and a funder who has NO templates
- The research org template is used (or user is presented with list if more than one is available)
  - User selects a Research Org that has template(s) and ticks the 'no funder' box
- The funder template us used (or user is presented with list if more than one is available)
  - User ticks the 'no research org' box and selects a funder who has template(s)
  - User selects a Research Org that has NO templates and a funder who has template(s)
  - User selects a Research Org that has template(s) and a funder who has template(s)
- The user is presented with a list of both organisational and public funder templates (USGS edge case)
  - The user selects the same Org in both the Research Org and Funder boxes and that org has templates that are public and organisational

**Comment by stephaniesimms** [comment]
I can't test this fully until it's deployed to dmp2 stage with USGS data @briri . but I already noticed that USGS has to be marked as an "institution" Org type in order to appear in the list for "Select primary research organisation." previously it was set to Org + Funder and didn't appear in the orgs list. 

So we need the logic to account for cases like USGS, DataONE, DOT, etc where the type is Org + Funder. these are the same cases where we need the "internal only" flag for templates and the last bullet point you list above.

**Comment by sjDCC** [comment]
A couple of corrections to the logic @briri 
![logic](https://user-images.githubusercontent.com/6169940/36158378-1c101ef0-10d4-11e8-91b0-f1c8d7db40fa.PNG)

To explain the scoring out / highlighting above:
- At present, only funders that have templates are listed in the third dropdown box afaik. We did consider preloading this with data from elsewhere e.g. fundref, but at the moment I think the logic is that funders only display when they have a published template so the “and a funder that has NO templates” bit doesn’t make sense. In contrast, research orgs are listed irrespective of whether they have templates and/or guidance
- The third bullet is incorrect. If a research org has a template, this should be displayed instead of the default template
- In the highlighted case, only the funder templates should display in the dropdown choice. These take precedence over org templates. The only case where there is a mix of funder and org templates is the USGS edge case for funders that have internal-only templates.

**Comment by sjDCC** [comment]
Despite what I say above, the logic seems to be working correctly e.g. if I select Edinburgh and no funder I get a dropdown with the two published Edinburgh templates to choose from rather than the default template.

And the funder and org templates don't seem to be mixed e.g. for Cancer Research UK and ZonMw (both of which have 2 templates) I only see their options in the template dropdown, not Edinburgh ones or the default template.

All seems to be working fine, but probably worth checking logic in light of comments above @briri and testing USGS use case. I'm happy to close this out though.

**Comment by stephaniesimms** [comment]
hooray - working as expected! closing issue.
