### ISSUE TITLE
Published Org templates not available when I create a new plan

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#1116]
Please complete the following fields as applicable:

**Expected behaviour:**
All of the "Published" Org templates should be available to users when creating a new plan (screenshots 1-2 below). 

**Actual behaviour:**
As an Org Admin, when I edit templates and publish the changes I receive a success message that the templates are published. But when I try to create a plan the templates appear and disappear from the dropdown list seemingly at random. Only 2 of the 6 published templates for Univ of Edinburgh are available (screenshots below), e.g.

I noticed this while testing a different bug #1063 that is now fixed - unsure if they're related

1 - Templates table shows 6 published templates for UoE
![screen shot 2018-02-01 at 9 39 10 am](https://user-images.githubusercontent.com/12703638/35693881-6d52add6-0734-11e8-9d6b-58476c5736f0.png)

2 - only 2 of 6 published UoE templates appear in the dropdown list
![screen shot 2018-02-01 at 9 38 35 am](https://user-images.githubusercontent.com/12703638/35693839-4edb05ba-0734-11e8-971e-bc1fd620b818.png)

**Comment by stephaniesimms** [comment]
this is working as expected now, except for Univ of Edinburgh templates. I assume it's just bad data. will close and leave here for @sjDCC to confirm all good.

**Comment by sjDCC** [comment]
Reopening this as I've done some testing with Glasgow and it still seems to be wrong.

Glasgow had 3 unpublished templates so I published 2 to test this and all three showed up in dropdown. The text notes that these are templates from the funder too, whereas it should say organisation.

![picture1](https://user-images.githubusercontent.com/6169940/36149853-47d17e1e-10b9-11e8-9837-c1c1835c4670.png)

![templates](https://user-images.githubusercontent.com/6169940/36149858-4d7cf744-10b9-11e8-9726-34b5e1c496d1.PNG)

**Comment by sjDCC** [comment]
I don't know if this is linked to the logic of which templates are shown in the dropdown, but on doing testing I noticed that a newly published and then re-edited version of an Edinburgh template didn't show up. Perhaps it's because there's a fault in the logic on which templates are published and should be shown? It may be worth checking that published templates with an unpublished new version (e.g. unpublished changes) do still show. The earlier published version should remain active unless specifically unpublished by the admin.

**Comment by briri** [comment]
@sjDCC this seems to be related to our collection of test data. Some of the old records had the wrong visibility setting which is something we've added to the database recently. I have updated the UoE templates so that they have the correct visibility now. Please take another look. I updated the 'test template' name and it versioned properly and appears to be offering up the correct templates now when I go to create a plan.

**Comment by sjDCC** [comment]
Perfect! Good to know this is a data issue. Thanks @briri 

I've just checked and all the Edinburgh ones are now displayed. 

I temporarily thought too many were coming through as the backend says 7 published 1 unpublished and 8 are showing, but the unpublished one has unpublished changes so perhaps that is what this category means? It's still technically 8 published.

![templates-published](https://user-images.githubusercontent.com/6169940/36219026-0c79d758-11ae-11e8-9aad-59bcb11ca9d5.PNG)
![templates](https://user-images.githubusercontent.com/6169940/36219034-11053790-11ae-11e8-99b7-ac91db1ad7dc.PNG)

This is a kleinigkeiten so guess the ticket can be closed out now.
