### ISSUE TITLE
Error exporting to PDF

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#1127]
I get the following error exporting to PDF. I thought it may be due to legacy data, but occurs on new plans too.
![capture](https://user-images.githubusercontent.com/6169940/35861543-02986110-0b40-11e8-8621-053f3e5ebce5.PNG)

Other export / download formats seem to work fine

**Comment by briri** [comment]
FYI @stephaniesimms and @sjDCC. The docx, pdf and html download options are all working. The csv and text export options have a minor issue. I will submit the fix for them as a separate PR. Please take a look at the PDF, DocX and HTML options and let me know if they need any adjustments.
They share the same code now (each one had its own logic before) so it should be easier to maintain going forward.

**Comment by stephaniesimms** [comment]
all of the formats are giving me the same error msg when i try to download plans from the "Download" tab. i can download public plan PDFs only.

![screen shot 2018-02-14 at 9 02 41 pm](https://user-images.githubusercontent.com/12703638/36241390-e0682f8a-11ca-11e8-9187-1780fdb60dca.png)

**Comment by briri** [comment]
submitted a fix for this error message and also updated the public plan version so that it does not show the question text.

**Comment by stephaniesimms** [comment]
i can download all file formats successfully now. i noticed a few weird formatting things w/DOCX but it may just be weird/test data. will wait for external testers to point out major issues. closing this one.

**Comment by sjDCC** [comment]
The various downloads I've done have all been ok too. I wasn't scientific in checking each in turn, but agree users will flag if anything is amiss. Removing from board.
