### ISSUE TITLE
Display message on Share tab instead of sending email for Request feedback

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#1163]
USABILITY TESTING FEEDBACK
Request expert feedback… has no idea who this would go to. He would like to know who this is going to. Wants to know what to expect when he clicks it. Clicks it… He barely notices the notification message. He has no idea who receives the message and how long it will take for him to hear back. Would like Request feedback to provide more context.

- suggestion to display the email message created by org admins below the heading for "Request feedback" on Share tab page so users have more context for what happens here. revise the request feedback tab as follows (screenshot below). 
    - revise heading above editor to "Request Expert Feedback - Message Displayed on Share Plan Tab"   
    - remove "Subject" field   
    - make Message a mandatory field (related issue #1197 )
    - Revise tooltip text: "Someone will respond to your request within 48 hours. If you have questions pertaining to this action please contact us at [insert email address]."
- display the message instead of sending the email to the user (but admins should still receive an email when a user clicks the Request Feedback button)
    - display the Message created by admins on the Share plan tab (screenshot 2 below) between the two lines of text (after "Click below to give..." and before "You can continue to edit...")

![screen shot 2018-05-21 at 2 25 26 pm](https://user-images.githubusercontent.com/12703638/40330899-567fe676-5d03-11e8-8bda-bfcaa31a1314.png)

![screen shot 2018-05-21 at 2 29 39 pm](https://user-images.githubusercontent.com/12703638/40331010-ccbda58a-5d03-11e8-8c41-4d7fb49a8ae6.png)

**Comment by stephaniesimms** [comment]
this looks and works great. I like the additional touch of displaying the feedback msg in the top banner msg when a user clicks the button to 'request feedback.' i just have a tiny revision for the tooltip, which i'll note in a new issue. closing this one.

**Comment by briri** [comment]
Reopening for verification after git cherry-pick

**Comment by stephaniesimms** [comment]
still working nicely. closing again.

**Comment by sjDCC** [comment]
I like the display of the message on the 'share' page rather than emailing out, but I noticed that sometimes this field is blank. 
![default-message-not-pulling-through](https://user-images.githubusercontent.com/6169940/42878417-e17f9588-8a84-11e8-9cb1-25406014bf4c.PNG)

It seems you can turn on the guidance configuration without saving a message. Ideally the default message would be stored automatically and available for edit. I think the text needs to be changed on the tooltip/default message too.  @stephaniesimms suggested "Revise tooltip text: "Someone will respond to your request within 48 hours. If you have questions pertaining to this action please contact us at [insert email address]." above

i have raised a separate ticket about this - #1743
