### ISSUE TITLE
Retain default sorting for tables when user clicks 'View all'

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#1214]
This is an outstanding part of issue #1187 - Default sorting was completed. But we still want to retain default sorting when user clicks 'View All' to expand the tables.

- on My Dashboard: default sorting should be by plan 'Last edited' date, most recent first
- all other tables: default sorting should be alphabetical by first field (Template Name, User Name, etc)

**Comment by stephaniesimms** [comment]
this doesn't appear to be working. when I click "View All" on plans tables on My Dashboard, DMP Templates, Public Plans, etc the sorting still changes. moving back to in progress.

**Comment by jollopre** [comment]
@stephaniesimms I don't think the server has deployed any of this stuff yet

**Comment by stephaniesimms** [comment]
clicking 'View All' retains default sort for all tables visible to logged-in users (plans, templates, etc). But this doesn't appear to be working for the DMP Templates or Public DMPs tables @jollopre

**Comment by jollopre** [comment]
@stephaniesimms, any page that is 'paginable', i.e. has search, sorting and page links behaves in the same way. I have tried the two cases that you described and the sort is properly retained.

Your comment suggest 'default sorting' which indeed these two pages don't have and therefore you have to click to any sortable column to be retained. What is the default sorting you want to apply to these? 

I would create a new issue to address the default sorting of these two views, since the retaining of the sorting I believe it works properly.

**Comment by stephaniesimms** [comment]
thanks for the clarification @jollopre - i thought these tables had a default set, but it appears that they do not so i'll create an issue as you suggested. all other tables look good so i'll go ahead and close this issue.
