### ISSUE TITLE
Can't change email address

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#1218]
I was trying to change my email address to include capital letters to test #1200 and found it isn't possible to change it at all. On saving you are warned that you need to enter your password, but this is on another tab. I'm sure previously a modal used to popup to ask for password when changing certain fields but this seems to have been lost. Need to reinstate.

![capture](https://user-images.githubusercontent.com/6169940/36608808-d424f1be-18c2-11e8-898c-98b483b93814.PNG)

**Comment by stephaniesimms** [comment]
when I test on roadmap-stage I do get a confirmation popup asking me to input my pw before changing my email address (screenshot 1). as an Org Admin I get an Error message (screenshot 2) that prevents me from saving the change, however. I assume this is because of admin privileges but I need to do more testing later with a non-admin account...

@sjDCC - it looks like you're testing on dmponline-dev. let me know what behavior you experience in roadmap to help define the bug here and determine which repo is the correct place to make which fix(es).

![screen shot 2018-03-01 at 1 55 12 pm](https://user-images.githubusercontent.com/12703638/36872003-c1d058e2-1d58-11e8-937e-643971dcaa00.png)

![screen shot 2018-03-01 at 1 56 54 pm](https://user-images.githubusercontent.com/12703638/36872011-c4f2b1d2-1d58-11e8-85b3-c733a95a7c7b.png)

**Comment by sjDCC** [comment]
Yeah, I was using DMPonline as it was to test a shib issue (#1200). I got the password confirmation popup earlier on roadmap-stage when changing email address to test #1060 so we can close this one out. The new code will fix the issue for us. Thx

**Comment by briri** [comment]
removing from the board since the ticket has been closed.
