### ISSUE TITLE
Numeric question type for templates not working

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#1219]
This requires further investigation but I noticed that a "Numeric" question type for one of the DMPTool funder templates didn't display anything on the plan writing page. When I selected the template there was just a blank space with a 'Save' button where the Numeric question should have been.

@sjDCC you might want to check this in case it's a high priority for DMPonline templates and should be fixed before you migrate

**Comment by sjDCC** [comment]
I'm not sure what you mean by 'numeric'question type @stephaniesimms Does this refer to radio button or dropdown answer formats? We definitely use those in a few templates so I'll need to check if so.
![picture2](https://user-images.githubusercontent.com/6169940/36628843-0fda4bae-1946-11e8-8d47-6c5ffcd08d38.png)

We also have a question number which is used to order the questions but is intentionally not displayed on the front end. Funders on our end use different ways to number questions (e.g. 1, 2, 3 / a, b, c / 1a, 1b / 2.1.1, 2.1.2...) or many just apply bullets instead. We just replicate whatever their system is in the question text field rather than auto-applying numbers via the tool.

**Comment by stephaniesimms** [comment]
weird. below is a screenshot from dmptool-stage that includes a "Numeric" question type, which is clearly not available on roadmap. I assumed it should be the same...? whatever the case it's not working so we should go ahead and fix/remove it from the code wherever it's coming from.

![screen shot 2018-02-24 at 10 44 30 am](https://user-images.githubusercontent.com/12703638/36633769-fbd6ecde-194f-11e8-8f14-a570133ec942.png)

**Comment by sjDCC** [comment]
Very strange! Worth figuring out where it's appeared from to make sure it doesn't inadvertently work its way back into the main branch.

**Comment by jollopre** [comment]
The question format combobox it's populated with the question formats present in question_formats table. We should have the following types right now:
```
[{:title=>"Text area", :formattype=>"textarea", :option_based=>false}, {:title=>"Text field", :formattype=>"textfield", :option_based=>false}, {:title=>"Radio buttons", :formattype=>"radiobuttons", :option_based=>true}, {:title=>"Check box", :formattype=>"checkbox", :option_based=>true}, {:title=>"Dropdown", :formattype=>"dropdown", :option_based=>true}, {:title=>"Multi select box", :formattype=>"multiselectbox", :option_based=>true}]
```
if the table has any type different from the above mentioned, it is normal to see blank areas around the question.

**Comment by briri** [comment]
yes, this is an issue with the options listed in that table. Date was added quite some time ago. I'm not sure when/why it was lost. 
@bhavi will remove the number/date options from our migration script

**Comment by stephaniesimms** [comment]
thanks for looking into it all. i assume it's okay to close this for roadmap then.
