### ISSUE TITLE
Users are able to select unpublished templates to create plans

### ISSUE THREAD

**Issue by dsisu** [DMPRoadmap/roadmap#1291]
Please complete the following fields as applicable:

**Expected behaviour:**

When I create a plan, I shouldn't have unpublished templates available to me.

**Actual behaviour:**

I'm able to select unpublished template to create plan.

**Steps to reproduce:**

![image](https://user-images.githubusercontent.com/2138956/37399497-b894236e-2779-11e8-9ac5-b96a2471f45f.png)

**Comment by vyruss** [comment]
@dsisu I can't replicate this. "Data Section Enabling Technologies Hotels" is published, while the unpublished "Gezond leven: goed voor je hart" is not selectable.

**Comment by sjDCC** [comment]
Agreed. I can't replicate this either. I think the problem at hand is confusing terms in our admin interface and the way we classify them in the publish / unpublished status numbers at top. 

ZonMw has three templates. Two of their own - Datamanagement ZonMw and Data Section Enabling Technology Hotels. These are both published but have unpublished changes. Very misleadingly this means they show in the 'unpublished' tally at top of table. I think there is an existing ticket to fix this.

There is a third template (Gezond leven: goed voor je hart) which they started to create on behalf of the Dutch Heart Foundation but they have since got admin rights themselves. This template is unpublished and doesn't show on front end.

All is displaying correctly so I'm closing this ticket out.

![capture](https://user-images.githubusercontent.com/6169940/37401062-cf01aec8-277e-11e8-94b3-d30a0dbe0e46.PNG)
