### ISSUE TITLE
Creating a funder template makes it privately visible by default

### ISSUE THREAD

**Issue by vyruss** [DMPRoadmap/roadmap#1342]
Please complete the following fields as applicable:

**Expected behaviour:** When a funder creates a template, it should get visibility: Public

**Actual behaviour:** When a funder creates a template, its visibility is automatically set to Private

**Comment by stephaniesimms** [comment]
as a funder (e.g., NIH) I can create a new public template and it appears in the create plan wizard. but I don't have the ability to select any guidance (see screenshot below). when I click to "See full list of guidance" there's nothing there. everything works as expected when I create a new plan with any other template, just not the newly created public one.

![screen shot 2018-04-05 at 10 12 27 am](https://user-images.githubusercontent.com/12703638/38380948-1f8f6fe6-38ba-11e8-95b4-db7655270d4e.png)

**Comment by stephaniesimms** [comment]
testing again on roadmap stage. i created a new NIH template with themed questions and it appears on the public DMP Templates page. i can also create a new plan with the template, but I only see the option to select default guidance (UCOP in screenshot). the expected behavior is to see the full list of guidance.
![screen shot 2018-04-06 at 1 38 05 pm](https://user-images.githubusercontent.com/12703638/38443245-eb1e110e-399f-11e8-888f-acd03aac0b96.png)

**Comment by sjDCC** [comment]
tested too and all working for me - both under create plan and public templates page
