### ISSUE TITLE
Add a 'view customisation' button

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#1386]
Universities that have customised funder templates may wish to view these customisations. At present you can only edit, publish or remove.
![view-customisation](https://user-images.githubusercontent.com/6169940/38823824-5f2b118a-419f-11e8-8d14-c22de9d00d20.png)

To view the existing content you need to click edit which automatically changes the status of the customisation to unpublished. I think this is really 'unpublished changes' though no changes had been made yet as I only viewed. 

I trialled creating a plan after hitting 'edit' and and the existing cutomisations were still overlaid on the funder template so the status here is misleading.

**Comment by jollopre** [comment]
@sjDCC with the work we are doing regarding the new versioning this will no longer happen (I wish) since edit effectively will bring a viewable template with the option to update something, i.e. the status of the template will remain published unless you effectively trigger a change by:
- change title/description
- add phase,
- etc

**Comment by sjDCC** [comment]
Great thanks @jollopre Look forward to closing it out then ;-)

**Comment by stephaniesimms** [comment]
no longer an issue. closing out!

**Comment by sjDCC** [comment]
edit lets you view without creating a new version so this is sufficient. thanks
