### ISSUE TITLE
Export template and guidance via API

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#147]
@sjDCC - I seem to recall you have some requirements for this? 

Pivotal ticket: https://www.pivotaltracker.com/story/show/119417279

**Comment by sjDCC** [comment]
I think there are two, possibly three requirements here:

1. Users have a desire to export the template so it can be used in a paper-based setting. Current plan export just gives you the questions, not guidance, so we want a PDF / doc version of the full (blank) template with any associated guidance and suggested answers etc built in. I think we need a button within the tool for this, so I wouldn't restrict it to API

2. We'd like to have a page like your public templates page. I assume the ability to generate a PDF noted under item 1 covers what's needed for this. Otherwise, let's flesh out what else is required. Does this auto-generate new PDFs to update the public page when new versions are released, or do you push things manually? I think this task is needed for your MVP

3. There's also a lot of interest in exporting templates for reuse elsewhere (and I assume the ability to import templates). This is covered by suggestion #95 [Allow sharing of public DMP templates between installations](https://github.com/DMPRoadmap/roadmap/issues/95) I think we should host a central library for templates. Some we will administer, but others could be maintained via community effort.

**Comment by sjDCC** [comment]
I've been reviewing notes from our user group meeting to clarify what the requirements are here. The primary use case of having downloadable versions of templates is already met by the functionality added to the codebase for the Public DMP templates page. 

There was also a request from institutional admins to have an option to export their own templates, together with guidance, so they have a downloadable document format to share. This isn't met by the existing public DMP templates as they are only based on funder templates. The functionality I'd suggest we add here is a download option in the actions list under an org admin's 'own templates' table. This should include the full content they've added to their template (i.e. questions, guidance, example answers etc)

![picture1](https://user-images.githubusercontent.com/6169940/32491362-541447e0-c3ae-11e7-81f7-b757be30e0f0.png)

The third option to allow templates to be exported from one tool and into another is out of scope. It's certainly not needed for MVP, but I think it's questionable anyhow as we don't share content currently and aren't encouraging / supporting other instances.

**Comment by stephaniesimms** [comment]
follow-up notes after the call today: we implemented public/funder template export for MVP. I like the suggestion @sjDCC to explore a mechanism for allowing Org Admins to export their own templates and guidance post MVP. and I agree that everything else is out of scope unless it becomes part of API machine-actionable work.

**Comment by magdalenadrafiova** [comment]
Admin users have a desire to export their templates so they can be used in a paper-based setting. Current plan export just gives you the questions, not guidance, so we want a PDF / doc version of the full (blank) template with any associated guidance and suggested answers etc built in. I think we need a button within the tool for this, so I wouldn't restrict it to API.

= > already possible to download

We'd like to have a page like your public templates page. I assume the ability to generate a PDF noted under item 1 covers what's needed for this. Otherwise, let's flesh out what else is required. Does this auto-generate new PDFs to update the public page when new versions are released, or do you push things manually? I think this task is needed for your MVP

=> we have public funder plans page under reference

There's also a lot of interest in exporting templates for reuse elsewhere (and I assume the ability to import templates). This is covered by suggestion #95 Allow sharing of public DMP templates between installations We could host a central library for templates. Some we will administer, but others could be maintained via community effort.

=> covered by the most recent hackathon? 
closing here
