### ISSUE TITLE
Revise email notification on plan feedback

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#1492]
We've had two helpdesk tickets this week asking where plan comments can be found. I suggest we amend the email notification to add the line: "Plan comments can be found adjacent to your answers in the tabbed panel next to guidance"

What do you think @stephaniesimms?

Hello [Name]
[Name] has finished providing feedback on the plan [TITLE]. To view the comments, please visit the My Dashboard page in DMPonline and open your plan. [INSERT NEW TEXT]
All the best 
The DMPonline team

**Comment by stephaniesimms** [comment]
more ideas @sjDCC ...
To view the comments, please visit the My Dashbaord page in DMPonline and open your plan. Comments can be found in the Write plan tab adjacent to your answers (Guidance/Comments). 

OR

Comments can be found in the Write plan tab on the right side of the page (Guidance/Comments).

**Comment by sjDCC** [comment]
I think the second is better. The first instruction takes them to My Dashboard and that's where they seem to have got lost

**Comment by stephaniesimms** [comment]
I should have been more explicit. I was proposing the second sentence as interchangeable with the full text above. That is assuming that the process of finding comments must involve opening a plan from My Dashboard. @briri would it be possible to insert a link that opens a plan on the "Write plan" tab?

If not, we may need the full instructions. We can also customize the email text differently since these are translated files.

Hello [Name]
[Name] has finished providing feedback on the plan [TITLE]. To view the comments, please visit the My Dashboard page in DMPonline and open your plan. Comments can be found in the Write plan tab on the right side of the page (Guidance/Comments).
All the best
The DMPonline team

**Comment by dsisu** [comment]
There should be a 'view comments' option somewhere, on the actions drop-down list perhaps. Another feature we could have is news on the dashboard 'You have comments on plan X'.

**Comment by sjDCC** [comment]
Great to see the link added, but can you make another couple of tweaks to this if possible please @Bodacious?

1. Ideally the link would open in the 'write plan' tab if possible (rather than 'plan details') so the user is taken directly to where the guidance/comments panel is visible. Is this feasible?

2. Since we've added a link direct to the plan, we can drop the sentence "To view the comments, please visit the My Dashboard page in DMPonline and open your plan." The final sentence also needs adjusting to meet Stephanie's latest text. Email should read:

Hello [Name]
[Name] has finished providing feedback on the plan [TITLE]. Comments can be found in the 'Write plan' tab on the right side of the page (Guidance/Comments).
All the best
The DMPonline team

**Comment by stephaniesimms** [comment]
Clicking the link takes me to the Write Plan tab if I'm already logged in. If users are not logged in and have trouble finding comments, we can adjust the email message accordingly. Closing this issue.

**Comment by briri** [comment]
Reopening for verification after git cherry-pick

**Comment by stephaniesimms** [comment]
working as expected. closing again.
