### ISSUE TITLE
Step 1 to create a plan

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#150]
As a researcher, I would like to select a template and begin writing a plan. This step involves selecting/confirming a user's org affiliation and/or which funding agency they are applying to.

See UX wireframe @JEK-III : http://h90c3m.axshare.com/#g=1&p=create_plan

* reorder selectors (select2 replacement): first selector is pre-populated w/user org if it exists; can also tick a box to skip it (see functional spec in blue notepad icon in wireframes)
* second selector to choose a funder
* if there are subdivisions for a specific funder (mainly an issue for NSF), a second drop-list appears in same selector to choose the subdivision 
* (optional) third selector for other circumstances where there are multiple templates for specific funder (multiple org templates, CRUK, etc)

Pivotal ticket: https://www.pivotaltracker.com/story/show/120866325
Related to the story for copying a plan:
https://www.pivotaltracker.com/story/show/120864879

Screenshots of existing DMPonline create plan steps: 1) select funder, 2) subsequent steps to select guidance from institution and other sources
![dmponline_plan_create1_funder](https://cloud.githubusercontent.com/assets/12703638/23566082/36dc1c6a-0005-11e7-8825-b862444c92cf.png)

![dmponline_plan_create2_guidance](https://cloud.githubusercontent.com/assets/12703638/23566111/5bf05eb2-0005-11e7-8a2a-670381a2d90c.png)

**Comment by JEK-III** [comment]
Wireframe: http://h90c3m.axshare.com/#g=1&p=create_plan

**Comment by briri** [comment]
![screen shot 2017-04-27 at 4 33 00 pm](https://cloud.githubusercontent.com/assets/1204467/25508496/503f92f8-2b67-11e7-84d0-2cebce16d340.png)

This isn't deployed yet, just wanted to run the screenshot by everyone first to see if the layout, wording, etc. all look good. @stephaniesimms @sjDCC @JEK-III

**Comment by briri** [comment]
same as #261

**Comment by stephaniesimms** [comment]
@briri this looks great to me. let's wait until Monday for @sjDCC to have a look too.

**Comment by briri** [comment]
bringing over @sjDCC comments from the duplicate #261 
"I would also prefer that you could pick guidance to include at this point too, even though you can switch it off later. It would make the optional guidance more prominent because it's very hidden otherwise. Many unis recommend that researchers select the DCC checkbox, so by removing it from this stage, we're requiring all their guidance be rewritten.

There's also no way to get the generic template now"

**Comment by JEK-III** [comment]
@briri This looks great. Ideally, we'd hide the clear field [X] buttons when the field is blank, and I'd style them a little differently (using the font awesome times-circle icon or something similar, but that's all cosmetic and non-critical.


As far as the comments from #261 go, in reverse order:

You get the generic template if you select no organization and no funder (or if neither has a custom template). If there is a significant use case for users wanting the generic template even when one of the others is available, then we can either

- make the currently conditional final "select a template" dropdown something that always appears with the generic template as an option, or
- add a third plan creation button to the My Plans page. Currently, the options are [create plan] and [create test plan], but we could make it [create custom plan], [create generic plan], [create test plan]. 

I'm hesitant to do either unless we're sure we need it, but if we do, we do.


I recommend agains selecting guidance on the plan creation page because I think it's important to get users into the plan workflow as quickly as possible and keeping a clean separation between the permanent template-choosing step and the changeable decisions that follow. We could highlight guidance options by 

- putting them on the initial Plan Details panel that comes right after plan creation, or 
- somehow highlighting guidance configuration when a user arrives at the plan writing page. 

I suppose that whether the first option is compatible with uni guidance will depend on how specific the language is. For the specific case of DCC guidance, could we turn it on by default (either for all of DMPOnline or on an organization-by-organization basis)? All of that said, if we really do need to select guidance on the create plan page, we can certainly add a chooser (probably checkboxes) as a last step in plan creation

**Comment by briri** [comment]
I added some javascript so that if one of the checkboxes is clicked, its corresponding dropdown is cleared and disabled.
I also set it so that the 'Create Plan' button is disabled until a decision is made in both the org and funder sections.

So the possible scenarios and their outcomes are:
- User selected an organisation and specified a funder - _will use the funder's template OR the organisation's customized version of the funder template if available_
- User selected an organisation and specified that no funder was applicable - _will use the organisation's template if available otherwise will use the generic template_
- User specified that no organisation was appropriate and selected a funder - _will use the funder's template_
- User specified that neither an organisation or funder was appropriate - _will use the generic template_

Here's the updated screenshot showing the disabled funder dropdown
![screen shot 2017-04-28 at 2 58 28 pm](https://cloud.githubusercontent.com/assets/1204467/25548837/454f3120-2c23-11e7-9f79-74a38a0c353d.png)

**Comment by sjDCC** [comment]
Thanks for working on this @briri The text in your screenshot with the two questions works for me. In the current roadmap code, we had removed the checkbox / link to say no funder was applicable and instead placed a 'no funder' option in the dropdown list. This is probably better for visibility as people often missed the link beneath the box.

Regarding the generic template, I expect people use/need this, but stats on how many times people click the link the 'create a generic plan' would help to bear that out. Can we pull those @vyruss? For now I'm happy to go without it and see if the question gets raised during testing. As you say, people get this generic template anyhow when no other more relevant one is available. 

If there's a call to reinstate the generic template as an option, my hunch is that @JEK-III's suggestion to "make the currently conditional final "select a template" dropdown something that always appears with the generic template as an option" will work best. Giving too many initial routes in will lead to inevitable questions about the different between custom, generic and test plans.

I agree with @JEK-III that it's better to separate out the template and guidance selection, particularly as guidance can now be switched on/off whereas the template is a fixed setting. We've just jumped a bit ahead of ourselves here by removing it without fully having the guidance selection options working smoothly post plan creation. I think there are a few things we need to do here:
1) ensure some guidance is switched on as default. If the user's org (or the institution selected in the first dropdown) has themed guidance or annotations on the specific template chosen, this should be on by default (based on the settings / question responses in the create plan wizard) but able to be switched off later
2) we should highlight the guidance configuration options once a plan is started. This is a new and unfamiliar workflow so we need to raise awareness of it
3) we may want to allow certain guidance (e.g. DCC) to be switched on as default. This is probably best at an organisational level rather than per installation
4) we should improve the layout of the guidance options as these can be unwieldy and ones that should be more prominent (e.g. subsets for the given institution) can be lost in the list. See #288 

I think #1 should be done for MVP0.3 whereas 2 and 3 could come in MVP or later. Does that work?

**Comment by briri** [comment]
Here are the latest screenshots of the create plan page (note the addition of the plan title):
![screen shot 2017-05-05 at 11 44 44 am](https://cloud.githubusercontent.com/assets/1204467/25760188/719cd2fc-318a-11e7-910e-b4d12538405a.png)
The above is what it looks like on initial page load

![screen shot 2017-05-05 at 12 02 23 pm](https://cloud.githubusercontent.com/assets/1204467/25760247/cc0f0638-318a-11e7-8dfc-88b9576f40fb.png)
The above shows the new accessible jquery autocomplete dropdown

![screen shot 2017-05-05 at 11 46 16 am](https://cloud.githubusercontent.com/assets/1204467/25760189/719e9baa-318a-11e7-94aa-99aef389d429.png)
The above shows what clicking 'no funder' looks like

![screen shot 2017-05-05 at 11 50 58 am](https://cloud.githubusercontent.com/assets/1204467/25760187/7199aeb0-318a-11e7-95f0-512c61f9bde1.png)
The above screenshot shows the additional dropdown the user is presented with when there are more than one template available for the funder.

I added some messaging to the page after the plan is created that lets the user know that they got the generic template. Not sure this is necessary or not. I seem to recall Ray doing some work around this to make things a bit clearer. Its easy to change the wording or remove.
![screen shot 2017-05-05 at 11 58 47 am](https://cloud.githubusercontent.com/assets/1204467/25760404/779e82a8-318b-11e7-9b6f-4b1b7fd86ad2.png)

**Comment by JEK-III** [comment]
Looks great!

**Comment by stephaniesimms** [comment]
@sjDCC We added a question to the plan creation workflow for your consideration (see screenshots above). Despite tooltips, it's difficult to get DMPTool users to provide an appropriate plan title although this is a required step. In DMPonline it's not a required step and the default title "My plan (template name)" is not so great. I wonder how many users just click through with the default title or don't know what to enter and write things like "Data Management Plan"? One possible solution is to ask for the name of the project in the wizard and use this as the edit-able pre-populated title once a user clicks through to the Plan Details page. Please let us know what you think about this approach.

**Comment by sjDCC** [comment]
This looks good. I'm happy with the addition of a project name question. I think most people just leave the auto-generated title in place, which isn't helpful.

Regarding the messaging, I think it would be best to call it a generic template, not plan i.e. "The funder you selected does not have.... provided you with the generic template."

There is some existing messaging in roadmap, but it's not very clear what template you're getting and why. In ticket #207 I've suggested reworked text for this. Perhaps use that to adjust the second line of the message for different scenarios?

**Comment by stephaniesimms** [comment]
After a round testing on dev I have the following corrections/changes:

- On first step to Create Plan, remove the grayed text "Stephanie's Plan" for Project Title. This isn't a best practice title and users might think it is appropriate. I think it's fine to leave blank.
- Change text above selector 2 to the following: "Primary research organisation" (Note: edit mixture of GB and US English spelling for "org" on page) 
- Change text above selector 3 to the following: "Funding organisation"
- Once the plan is created the user should be driven to the Edit Plan Details page (as in DMPonline currently) - right now they have to take the extra step of clicking the button to edit 
- Under Plan Details: the Principal Investigator/Researcher field should autopopulate w/ First and Last Name (not email address as it does now - screenshot below)
- Delete explanatory sentences at top of Plan Details page "This page gives you an overview..." - I don't think this is necessary and overall this page is kind of busy
- When editing plan details the message at the top of the page should say "Please fill in...and click 'Save' to update. (current text says "click 'Update' to save.")
- Specific to NIH template: once a plan is created, the Funder and Org names are inverted (screenshot below - NIH is listed as customizing org and Funder name is org)
- Guidance +/- accordions on Answer questions page: when multiple guidance sources are listed only the first/top accordion works; the lower ones don't expand
- When I Share Note and click Save, the browser flickers a few times (just something to note, not a fatal flaw)
- When I advance to answering questions in a new section w/o saving and click through the modal that prompts me to Save previous answers, I observe the same browser flickering
- For the radio button question on NIH template I cannot save my answer. I just get a "Saving..." message (no timestamp save confirmation) and when I navigate away from the page and return my selection is not saved

Design/UX things:

- Guidance choices on plan details page aren't very prominent - this needs some thought about how to highlight availability of guidance for users. One solution is to expand the accordion by default...or maybe this is related to other UX changes but I don't see any in @JEK-III wireframes...?
- Question: Is it possible/advisable to have the type ahead selector AND a dropdown list? Esp. for funders I'm not sure users will always know what to type/how to find what they need (screenshot of wireframe below w/ one example of how to do this, probably not the best way...)
- When a user clicks the "Export" button at the end of Answering questions they should be driven to the Export page (I don't think we need/want to keep the modal)
- When I get the default template, maybe it should say This plan is based on "Funder: None" instead of DCC or Tuuli (screenshot below)?

Remove suggested Project Title - leave blank
![no-name-title](https://cloud.githubusercontent.com/assets/12703638/25864226/8b416102-34a3-11e7-8693-3a669d1d45e1.png)

Prepopulate PI/Research First and Last Name instead of email
![prepop-pi-name](https://cloud.githubusercontent.com/assets/12703638/25864291/bee84502-34a3-11e7-911b-935b301b27d9.png)

NIH template: Funder and Org inverted
![wrong-funder](https://cloud.githubusercontent.com/assets/12703638/25864250/9d89a70c-34a3-11e7-8434-21efe748d983.png)

Example of selector AND dropdown list
![see-full-list](https://cloud.githubusercontent.com/assets/12703638/25864208/7c540668-34a3-11e7-8889-30f5adb041bc.png)

Default funder - List as "None"?
![default-funder](https://cloud.githubusercontent.com/assets/12703638/25864345/ea7893e8-34a3-11e7-8b5e-f3319fe64482.png)

**Comment by JEK-III** [comment]
I did a quick run-through with VoiceOver. The Select2 replacement is working really well(!), but I did come across a few issues:

- The link order in the global header is slightly weird when tabbing– it goes from the DMP Roadmap logo up to the "Signed in as..." dropdown, then back down to "View Plans." Not a big deal, but it would be better if we went all the way across the nav bar, _then_ up to "Signed in as..."

- The labels on the checkboxes aren't getting read– looks like they're not associated properly. 

- There appears to be a bug in which if a user checks the "No funder" box and tabs to the _active_ Create Plan button, nothing is read. If I get there by any other route, it's read correctly.

- When the Create Plan button is disabled, it's no longer a tab target, so a user tabbing through the form misses it entirely. This may be actually be standard behavior, but it's a problem for us because users who have left any fields blank won't know what's wrong or how to proceed. I'm not sure what the best solution is here, but I can look into it.

- The "select a template" label is not read (or associated with its dropdown)


WAVE turns up a couple of other issues:

- The three/four big questions ("What research project are you planning?" etc.) are h3 when, semantically, they should be h2. It's not a big deal, but best practice for screen readers is not to skip heading levels.

- The three/four fieldsets corresponding to each big question are missing legends. I think that the big question text for each one should also be set as a legend for that group of controls. 

Despite the number of bullet points above, the page is in good shape! The missing/disassociated labels are the only really critical obstacles to basic accessibility.

**Comment by briri** [comment]
@stephaniesimms how do these look for a revised (hopefully less confusing) version of the 'The plan is based on' section
![screen shot 2017-05-09 at 11 56 17 am](https://cloud.githubusercontent.com/assets/1204467/25867673/2ad086a2-34af-11e7-9baa-e72e39af2447.png)
![screen shot 2017-05-09 at 11 59 30 am](https://cloud.githubusercontent.com/assets/1204467/25867674/2ad0c342-34af-11e7-8243-8a7072cb384e.png)

**Comment by briri** [comment]
Ok @stephaniesimms and @JEK-III I just deployed some changes to the server based on your feedback above.

**Comment by briri** [comment]
@stephaniesimms I did not address the following as they are beyond the scope of plan creation. We should create separate tickets for these:
- Guidance +/- accordions on Answer questions page: when multiple guidance sources are listed only the first/top accordion works; the lower ones don't expand
- When I Share Note and click Save, the browser flickers a few times (just something to note, not a fatal flaw)
- When I advance to answering questions in a new section w/o saving and click through the modal that prompts me to Save previous answers, I observe the same browser flickering
- For the radio button question on NIH template I cannot save my answer. I just get a "Saving..." message (no timestamp save confirmation) and when I navigate away from the page and return my selection is not saved
- Guidance choices on plan details page aren't very prominent - this needs some thought about how to highlight availability of guidance for users. One solution is to expand the accordion by default...or maybe this is related to other UX changes but I don't see any in @JEK-III wireframes...?
- Question: Is it possible/advisable to have the type ahead selector AND a dropdown list? Esp. for funders I'm not sure users will always know what to type/how to find what they need (screenshot of wireframe below w/ one example of how to do this, probably not the best way...)
- When a user clicks the "Export" button at the end of Answering questions they should be driven to the Export page (I don't think we need/want to keep the modal)

**Comment by briri** [comment]
@JEK-III I think the following issue should be addressed when we redo the global navigation
- The link order in the global header is slightly weird when tabbing– it goes from the DMP Roadmap logo up to the "Signed in as..." dropdown, then back down to "View Plans." Not a big deal, but it would be better if we went all the way across the nav bar, then up to "Signed in as..."

Instead of changing those h3 headings to h2 I simply made them the fieldset's legend (didn't know there was such a thing ... learn something new every day ;))

I believe the labels are all now correctly associated with their fields.

I also added an 'aria-disabled' attribute to the button that should inform the screen reader about its presence/status. Let me know if that works or not.

**Comment by JEK-III** [comment]
@briri Agreed that we should not worry about the header now

Sounds like a good solution to the fieldset label problem. It turns out that VO doesn't read the legends with Chrome, but it does with Safari. I _think_ VO users generally use Safari (specifically because it does better with VO), and the individual field labels are reasonably descriptive, so I think we've done what we can. It does look like the legend text is too close to the top of each box– it would look better if you could drop it to about where it was (by 10 or 20px?) or even just pad it with some white space.

Labels are working great.

The button is still not focusable by tabbing. Users will be able to hear it if they're having VO read the page, but they'll miss it if they're just filling out the form. 
I'm still not sure what the best course of action is– a recent [Stack Exchange thread](https://ux.stackexchange.com/questions/103239/should-disabled-elements-be-focusable-for-accessibility-purposes) about a similar situation seems to conclude that even though you shouldn't be able to put focus on a disabled button in principle, in practice it's probably the least bad thing to do.

**Comment by stephaniesimms** [comment]
@briri Re "This plan is based on..." can we resolve the template template issue by renaming the templates to just use the funder name? i.e., National Institutes of Health, Wellcome Trust, National Science Foundation, etc. 

The rest looks great and thanks to @JEK-III for the accessibility check. I didn't have a chance to test everything fully before leaving today so unfortunately it will have to wait until I'm back in the office on Mon (time to get VPN working ...).

**Comment by briri** [comment]
I'm not comfortable renaming the templates @stephaniesimms since we don't own/manage all of them. Its also not really something we would then have to enforce all the time just to accommodate this messaging. I added some logic to add 'template' only if the name of the template doesn't end with 'template'.

- A version of "Tekes" template that has been customised by Åbo Akademi University 
- A version of "NIH template" that has been customised by University of Turku 
-  The "NIH template" provided by National Institutes of Health
- The "Tekes" template provided by Tekes
- The "Tuuli DMP" generic template provided by Tuuli

**Comment by briri** [comment]
hey @JEK-III 
I added some spacing to the top of the legend. I also took some time to throw together a submit button that is hopefully more accessible. I'm no longer using the 'disabled' attribute, so the user should be able to tab onto the button where it will display the following message:
![screen shot 2017-05-10 at 1 05 35 pm](https://cloud.githubusercontent.com/assets/1204467/25919000/284cf388-3582-11e7-88c7-067f74880e4c.png)

Let me know how it functions within the screen reader. The button is visibly greyed out and continues to act as though it were disabled for users clicking on it.

**Comment by sjDCC** [comment]
I think all of this is covered and really like the look of the revised create plan wizard - thanks all!

The issues @stephaniesimms raised about pre-populating PI field with name not email and the explanation of what template all seems to be working on DMPonline test. I don't see them on staging yet but guess that's because @briri is on leave so leaving open for now for Steph to check and close
![roadmap-staging](https://cloud.githubusercontent.com/assets/6169940/26301345/d380e886-3ed8-11e7-9c66-6491ffef7bab.PNG)

**Comment by stephaniesimms** [comment]
this all appears to be working as expected on Roadmap stage now. closing out.
