### ISSUE TITLE
Creating and editing questions refinements

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#1502]
As an admin creating new questions for templates, a couple of behaviors are different now and should be revised to function as they did previously.

1. the default selection for Answer format should be 'Text area' (currently it defaults to Check box; screenshot 1)
2. after I enter text and click Save, the system should close the editors and just display my entries in read only. current behavior keeps all editors open and active, even when I click to create a new question below the first. this is confusing and produces a huge cascade of editors for a full template.
3. I noticed the same behavior when I click to edit an existing template question - all editors remain open. Desired behavior is to display existing content as read only and only open editors if a user clicks to Edit a question.

![default-answer-type-textarea](https://user-images.githubusercontent.com/12703638/40138087-c5a015dc-5900-11e8-8b96-77176465d969.png)

**Comment by briri** [comment]
ok. I had removed all of the show/edit toggles and cancel buttons during the refactor because they had different behaviors and seemed like unnecessary steps for the user when we know whether or not they have permission to edit. The old section cancel button completely reloaded the page while the phase and template ones simply hid the edit form (didn't actually clear any changes made).

I take your point though with the questions. The page can get exceedingly long if the section has multiple questions and its hard to tell which save button belongs to which question. Will reintroduce the show/edit toggle for questions.

**Comment by stephaniesimms** [comment]
these issues all appear to be resolved @briri - closing out and creating new issues for remaining things i noticed when creating and editing questions
