### ISSUE TITLE
Allow users to request admin feedback on plans in Share tab

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#153]
UX wireframe @rhu001 - all wireframes are in progress
1. Organizational Profile (Admin view) showing the ability to turn on "review" feature near bottom of the organizational profile page along with a template email space where an automated email could be sent to users. (Need generic text for this email): http://h90c3m.axshare.com/dmp_organizational_profile__admin_view_.html
2. On the user's side, once the feature is turned on they have an area where they can send a request for review on the Write plan wireframe (Share tab): http://h90c3m.axshare.com/#g=1&p=write_plan
3. Admin dashboard view with notification of a request for review: In progress
4. Once admin follows notification link to the write plan page for the plan that they are going to review, whenever they attempt to leave the write plan tab, they will see the following modal box pop up asking them if they are "done" with the review and ready to send notification back to user or if they just want to save existing comments and return later. http://h90c3m.axshare.com/admin_finish_review_dialog_box.html

Requirements in Google doc: https://docs.google.com/document/d/1fxx5qMAfnmcz39YY3hn2N7EIz3X5hZzH0_P9RsafVUc/edit

If Org admin turns on functionality, user sees option to request feedback on plan under Share tab 
- Need some text to clarify what this does e.g. 
“Your University has support staff who are willing to offer feedback on your DMP. If you would like someone to review your approach and offer comments and feedback, please click the link below to share you plan. The University support staff will be alerted and provided with access to your plan. You can continue to edit and download the DMP in the interim.”
- Org admins will already have access to all Org plans - they just need a notification for which plans are awaiting feedback (related issue #434 )

**Comment by briri** [comment]
related to #442

**Comment by sjDCC** [comment]
This is a slight aside to this ticket, but seeing the organisational details profile wireframe above made me think we should try and copy what we have in Roadmap currently so it's not too big a change for existing users. 

Two screengrabs for comparison below and a few suggestions:
![org-details-dmponline](https://user-images.githubusercontent.com/6169940/29624714-be50cbb0-8821-11e7-9233-30d99913a204.PNG)
![ord-wireframe](https://user-images.githubusercontent.com/6169940/29624715-be56f0a8-8821-11e7-9d4a-7f540bd19b6c.PNG)

- Perhaps reorder so we have things like full name and abbreviation together
- Can things that are for one use case only (e.g. shib, entity ID, parent dropdown) be configurable so they're switched off in other instances?
- I think we agreed to remove the 'top banner text' field. Is that the same as 'descriptive text?'
- Will the other tabs (org resources, assign permissions, usage) come under here or other pages? I think 'org resources' is your equivalent of guidance so is covered elsewhere, permissions are currently assigned under the 'user' page, and I think the 'usage / stats' area was a separate page in DMPTool?

**Comment by rhu001** [comment]
@sjDCC In the one that was shown yesterday, I had as I mentioned in the call just put in the page exactly as I found it in the DMPTool since I knew that we had more fields that needed to be accounted for than DMPOnline. In light of the new agreed upon global navigation header and no longer the need to have groupings for individual admin or super admin pages, I think it's fine to remove the tabs. In my updated version of the wireframe I have done so and stubbed in a screenshot of the new header. I have added some drop down menus in order to make the wireframes navigable but in terms of visual design they can be the same drop down menu treatment as it is currently on DMPOnline. I have also re-ordered the full name and abbreviated names together and moved the shib, entity ID, and parent dropdown further down the page so as to have those grouped separately from the core elements that are more common. We do however need those items to remain in the main Roadmap codebase since those are requirements for the DMPTool.  Those fields could be hidden though when the DMPOnline customization work is completed. @briri please confirm the above.

Of note, I have laid out the labels and form fields so they are stacked on top of each other. I did this to match the consistency of the existing profile wireframes and create plan fields that were laid out by John K and were signed off on earlier in the project. This layout is also more usable and easier for users to scan.

**Comment by briri** [comment]
Yes @rhu001 that is correct. These fields can be easily excluded from DMPOnline if they are not desired (as simple as making a copy of the file and deleting the lines that aren't needed). They should be a part of the core Roadmap codebase though as agreed upon during the project's inception and the analysis that was done to determine what functionality needed to come over from the DMPTool into the shared codebase.

**Comment by stephaniesimms** [comment]
UX wireframes revised by @rhu001 w/suggestions above. Additional things noted during our call on 5 Sept:
- Org admins don't need to see the detailed entityID and Shib info (only Super Admins). It might be possible to subsume these under some kind of "Shib enabled: Yes/No" field. If displayed, they should be grayed out and not editable by Org Admins.
- Remove 'Parent organization' field - this is not needed

**Comment by stephaniesimms** [comment]
transferred to new issues - closing UX global issue
