### ISSUE TITLE
Add Super Admin functions to Admin area

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#157]
Currently this is not part of DMPonline UI. Need to add something like DMPTool "DMP Administration" tab to Admin area. 

Super Admins need to be able to:
1) add organizations 
2) assign privileges to other users 
3) copy and edit funder templates; full view of Org templates
4) change plan visibility (remove public DMPs) - triggers email
5) administer themes (update name, add new); view of guidance by theme
6) administer languages (define language options for an installation); possibly remove language selection?
...

UX wireframe @rhu001 : http://h90c3m.axshare.com/#g=1&p=dmp_templates__admin_view_

Pivotal ticket: https://www.pivotaltracker.com/story/show/121675903

Screenshots of DMPTool DMP admin UI
![dmptool_dmpadmin_usersroles 1](https://cloud.githubusercontent.com/assets/12703638/23570536/69602afa-0019-11e7-8790-ef3ce1c98cb1.png)

![dmptool_dmpadmin_institutions 1](https://cloud.githubusercontent.com/assets/12703638/23570543/7488fbbe-0019-11e7-98df-5bee8719ac76.png)

Adding a new Institution (note: revise fields, not all of these are necessary)
![screen shot 2017-10-09 at 11 59 09 am](https://user-images.githubusercontent.com/12703638/31353962-62f44be2-ace9-11e7-8d2b-a851b19dc543.png)

**Comment by stephaniesimms** [comment]
reevaluate this global issue post MVP and identify any remaining work. many things have already been completed.

**Comment by briri** [comment]
just making some notes here for the languages screen: We should generate the list of languages based on the translation folders present in `config/locale` so that an admin can simply enable/disable them.
```
|  Language     |  abbreviation  | enabled  | default  |
---------------------------------------------------
|  English (GB) |   en_GB           |   true       |    true    |
|  Japanese      |   ja                   |  false      |    false   |
```
Where enabled means that the app.po is available and the language appears in the `languages` table. Disabling would remove the entry from the table (which is what drives the language selection box) but not remove the app.po.

We could also add a button to 'Add a language' that could kick off the `gettext:add_language[xx]` rake task which will generate the app.po file. We should also include a link to an ISO-639 language code reference so that admins use a valid code

**Comment by stephaniesimms** [comment]
@sjDCC - reviewing this catch-all Super Admin issue and the only thing we didn't address yet is administering languages. do we still want/need to be able to do this? I think it could just be something we ask devs to configure for each installation. I don't necessarily need to add/remove languages myself.
