### ISSUE TITLE
Create documentation for tests

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#1612]
For external contributors guide, create documentation for tests based on current strategy. Devs can discuss future/ideal strategy but in the interim we need something that enables folks like DMP OPIDoR to contribute effectively.

**Comment by briri** [comment]
Started off on this document here: https://github.com/DMPRoadmap/roadmap/wiki/Testing-Conventions

**Comment by xsrust** [comment]
Great content there @briri. Perhaps we should point out to some test files where we do this well and follow the standards we set for the community.
That way they'll have a reference for what's currently expected

**Comment by xsrust** [comment]
for UI testing, would we want to move to something like capybara? 
https://github.com/teamcapybara/capybara
It integrates with both minitest and rspec, but the integrations are different, so I'd lean towards waiting until we begin to shift to rspec before adding it.

**Comment by Bodacious** [comment]
Hi all.

I'd like to open up this thread for discussion about what standards we put in place for testing.

I've prepared the following suggestions. Each suggestion is listed as a separate Issue on this repo to allow for conversation on that particular topic.

---

# Ruby testing convention suggestions

## General principles

### Use RSpec

RSpec is a more feature-rich testing framework than MiniTest, and can offer better readability for developers (e.g. examples can be nested within contexts).

Further discussion: https://github.com/DMPRoadmap/roadmap/issues/1664

### ...with BetterSpecs.org

There's a great online guide called [BetterSpecs](http://www.betterspecs.org/) that should help any contributors understand the best way to submit their tests when creating a PR.

Further discussion: https://github.com/DMPRoadmap/roadmap/issues/1665

### Factories > Fixtures

Factories (e.g. [FactoryBot](https://github.com/thoughtbot/factory_bot)) are a lot more flexbile than fixtures, and should be used for most testing scenarios. By implementing factories within the current codebase we would be able to remove quite a lot of code from the existing tests and simplify them ([example](https://github.com/DMPRoadmap/roadmap/blob/master/test/unit/user_test.rb#L8-L26) )

Further discussion: https://github.com/DMPRoadmap/roadmap/issues/1651

### Faker

The [Faker](https://github.com/stympy/faker) gem is a library that generates safe, random content for testing.

Used with FactoryBot, this allows for the creation of thousands of unique test objects, without the developer having to manually code attribute values or worry about those attributes being valid and/or unique.

Further discussion: https://github.com/DMPRoadmap/roadmap/issues/1666

## Unit tests

### Use Shoulda

[Shoulda](https://github.com/thoughtbot/shoulda) provides macros that make it much simpler and faster to create tests for common rails behavaiour (associations, validations, etc.). This gem would be really helpful in the quest for most rhobust unit tests.

Further discussion: https://github.com/DMPRoadmap/roadmap/issues/1667

## Integration tests

### Capybara

[Capybara](https://github.com/teamcapybara/capybara) provides a DSL for automated integration/acceptance testing for web applications. Capybara loads the webpages and immitates user behaviour to test how features are working together.

Capybara should be used with Selenium, since this supports [Headless Chrome](https://developers.google.com/web/updates/2017/04/headless-chrome) (faster and less annoying to run the tests).

There are a few alternative framework options for integration testing in Ruby, notably [Cucumber](https://cucumber.io), but I believe Capybara strikes the right balance between readability and abstraction.

Further discussion: https://github.com/DMPRoadmap/roadmap/issues/1668

## What to test

### Coverage

The application already has [SimpleCov](https://github.com/colszowka/simplecov) installed. This should be used to monitor the quality of code as we progress. We should agree a healthy minimum level of coverage (e.g. 80%) to ensure the quality of the code is preserved over time.

SimpleCov can be set up to use a service like [Code Climate](https://codeclimate.com), which is free for Open Source projects, and provides stake holders with a web interface through which they can track the quality of the code over time.

Further discussion: https://github.com/DMPRoadmap/roadmap/issues/1669

**Comment by Bodacious** [comment]
Here's a first draft of test coding conventions. Feedback and suggestions welcome:

---

# DMPRoadmap Testing Conventions

This project started out with close to zero tests. Please help us improve our test coverage by ensuring that any new code you push is well-tested, and by adding additional tests where you see they are needed.

## Running the tests

We use [RSpec][rspec] for unit testing, and [RSpec][rspec] with [Capybara][capybara] for integration testing.

You can run the entire Ruby test suite with the following command: 

``` bash
$ bundle exec rspec spec
```

(Using the bundle keyword helps to ensure we're using the rspec executable in the bundled [RSpec][rspec] version).

## Basic Guidelines

- Tests MUST pass before a PR can be accepted and merged
- Format your tests as recommended in the [Better Specs][better-specs] guide
- Test any methods that have been defined for both positive and negative outcomes 
- Test model associations (use [Shoulda][shoulda])
- Test model attribute validations (use [Shoulda][shoulda])
- Test model callbacks: `after_save`, `before_validation`, etc.
- Test model scopes to ensure that they filter the correct data
- Do not test private methods
- Do not unit test controllers. These tests are normally difficult to maintain and rely heavily on stubbed data
- Use [RSpec][rspec] feature specs for testing controllers with UI endpionts
- Use [RSpec][rspec] request specs for testing controllers with JSON endpoints
- Define one assertion per [RSpec][rspec] example (unless in feature specs)

## Factories, not fixtures

This test suite relies on [Factories][factory-bot], not fixtures. This is preferrable, since fixtures are inserted to the database without running ActiveRecord validations and checks. Factories allow us to run each test on a unique record, whereas fixtures give us only a small set of pre-defined test objects. This allows us to catch more potential bugs.

To learn more about how to use Factories, please read the [Getting Started guide](https://www.rubydoc.info/gems/factory_bot/file/GETTING_STARTED.md)

## Fake it when you make it

Use the [Faker][faker] gem to generate dummy data for testing.

**Bad**

``` ruby
@user = User.new(email: 'foo.bar@example.com')
expect(@user).to be_valid
```

**Good**

``` ruby
@user = User.new(email: Faker::Internet.email)
expect(@user).to be_valid
```

## Headless Chrome

Running the feature specs requires [Headless Chrome][headless-chrome]. 

You can check you have the minimum requireqments by running the following bash shell command:

``` bash
chromedriver --version
```

This should be at least `ChromeDriver 2.41.578706 (5f725d1b4f0a4acbf5259df887244095596231db)`

To update your ChromeDriver version, use: 

``` bash
chromedriver-update
```

## Coverage

The test suite has SimpleCov installed. This should be used to monitor the quality of code as we progress. We are aiming for a healthy minimum coverage level of  80% to ensure the quality of the code is preserved over time.

## UI Tests

UI tests are written in [RSpec][rspec] using the [Capyabra][capybara] gem. Tests are run using [Selenium][selenium] with [Headless Chrome][headless-chrome].


### UI Tests With JS 

**NOTE:** Ensure the `:js` flag is used in any feature Specs that rely on Javascript to run. For performance, we run feature specs in a lighter driver unless Javascript testing is required. To run a given test in Capybara with Selenium **you must explicitly specify the js flag**.

Example:

``` ruby
require "rails_helper"
describe "Account creation", type: :feature do 
  scenario "User creates an account", :js do # <= see the :js flag here?
    # Run tests that require Javascript in the browser.
  end
end

```

## JS Tests

Explanation of `npm test` and our very spotty coverage coming soon ...


---

[faker]: https://github.com/stympy/faker
[factory-bot]: https://github.com/thoughtbot/factory_bot_rails
[rspec]: http://rspec.info
[better-specs]: https://betterspecs.org
[shoulda]: https://github.com/thoughtbot/shoulda
[capybara]: https://github.com/teamcapybara/capybara
[selenium]: https://www.seleniumhq.org/
[headless-chrome]: https://chromium.googlesource.com/chromium/src/+/lkgr/headless/README.md

**Comment by sjDCC** [comment]
Thanks for all your work on the testing @Bodacious Closing out
