### ISSUE TITLE
Remove mandatory field asterisk for Co-owner on Share tab

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#1646]
The red asterisks for email and the first radio button below "Permissions" in the screenshot below are misleading since it's not mandatory to invite collaborators. If someone does choose to share their plan I understand that it's mandatory to input an email address and make a permissions selection below that, but we need a better way to display these asterisks that won't confuse users. 

As they appear now it suggests that you have to make any collaborator a Co-owner since this is the only option with an asterisk. It would be better to remove/hide the asterisks. If we have to use asterisks, it would be better to only have one next to "Permissions" rather than on the radio buttons themselves. If they have to be on the radio buttons, they should appear next to all three options, not just the first one.

![screen shot 2018-07-02 at 11 12 07 am](https://user-images.githubusercontent.com/12703638/42179588-634158fc-7de9-11e8-9301-c612266f97b7.png)

**Comment by xsrust** [comment]
We use the asteriskes to denote fields which must be completed to submit the form.  They also tag to our Javascript that there.

I think it makes sense to keep the asterisk on the email for the time being.  
On the subject of the radio buttons, There is no easy way to make this asterisk display next to the permissions label.  I think a simpler solution would be to just set a default of read-only access on this form.  Since they are radio buttons, if they select another option, it deselects read-only, and this ensures there is always one selected.
I've submitted a PR which does the above.
![screen shot 2018-07-03 at 3 38 07 pm](https://user-images.githubusercontent.com/7352616/42226545-204a3962-7ed7-11e8-9a82-71014a58fcbd.png)

@stephaniesimms if you would perfer another approach, just let @briri know to reject the PR

**Comment by stephaniesimms** [comment]
@briri will investigate a JS approach. but if the best solution turns out to be a default permissions selection, I think it would be better to make it "Co-owner."

**Comment by briri** [comment]
yes, turned out to just be an issue with the new HTML structure. I sent a PR with an update that places the asterisk next to the fieldset legend "Permission" in this case. The form validation still works now and it applies to all required radio button sections (e.g. guidance theme selection)

**Comment by stephaniesimms** [comment]
Asterisks look good. I concur w/ @sjDCC that the ideal is to NOT pre-select any permissions. if this is required @briri , co-owner is the best option.

**Comment by sjDCC** [comment]
This looks great as it is now. Thanks @briri. Closing out

**Comment by stephaniesimms** [comment]
Asterisk looks great, yes. I just have a tiny cosmetic request @briri - is it possible to reduce the font size of 'Permissions' so we don't have such a mixture on this page? No need for a hierarchy here unless accessibility requires it. See screenshot below of roadmap stage and current implementation in dmptool prod.

![screen shot 2018-07-10 at 8 15 49 am](https://user-images.githubusercontent.com/12703638/42519891-d978d97e-8419-11e8-8423-f83d14e9fcc6.png)

![screen shot 2018-07-10 at 8 16 22 am](https://user-images.githubusercontent.com/12703638/42519895-dd48c492-8419-11e8-848d-9809e48995d6.png)

**Comment by stephaniesimms** [comment]
looks good. closing.

**Comment by briri** [comment]
Reopening for verification after git cherry-pick

**Comment by stephaniesimms** [comment]
double check is good. closing again.

**Comment by sjDCC** [comment]
New layout looks good
![capture](https://user-images.githubusercontent.com/6169940/42877703-76b764f8-8a82-11e8-8393-b7a622e8288e.PNG)
