### ISSUE TITLE
Add plans/template report to Usage dashboard

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#1679]
Org admins also want to know how many plans have been created by their users with each template. On the Usage dashboard, add option to download a new CSV report w/ plans/template/month.

@sjDCC it would be nice to visualize these data if the design for users and plans graphs extends easily here. dmptool has 36 templates currently. dmponline has 17. thoughts on adding a third graph?

**Comment by sjDCC** [comment]
Yeah, I agree that adding a plans by template graph would be great. displaying the data by month would also indicate when certain funders have call deadlines to help target training etc.

Since many UK unis have their own templates too, this graph should also include plans for these. That should be scoped to the institution though so you're only showing data for templates owned by them.

Given the co-ownership of DMPs, I assume some plans written to templates owned by other orgs could fall into each institutions statistics too. These could be lumped under an 'other' category unless it warrants splitting each out

**Comment by sjDCC** [comment]
From what I can see this looks good and is probably ok to close. Download works well. I found the layout a bit confusing at first, but probably as the example I had was a uni with no plans. @stephaniesimms should we be accurate and record the exact date data was pulled each month or just say 'Jan 2018' 'Feb 2018' etc. That may be more readable and user friendly
![plan-by-template](https://user-images.githubusercontent.com/6169940/49465767-3a7baf80-f7f6-11e8-9a2e-b57536313124.PNG)

I noticed we have a different view on Roadmap-stage and DMPonline-test here so don't know if there's an issue our end @xsrust or if you deployed an earlier version of code? Comparisons below. We're missing overview stats and third graph / download.
![dmponline-test](https://user-images.githubusercontent.com/6169940/49465828-6139e600-f7f6-11e8-907f-4069ddd5f65e.PNG)
![roadmap-stage](https://user-images.githubusercontent.com/6169940/49465829-6139e600-f7f6-11e8-8647-976b8ae8613d.PNG)

**Comment by stephaniesimms** [comment]
the download button works well and i agree w/ @sjDCC that some minor modifications would make the resulting CSV more readable and user friendly:
- instead of full dates in the date column just say 'Jan 2018' 'Feb 2018' etc. 
- revise capitalization of template titles in columns to adhere to the UI display, so e.g. instead of just caps for the first letter of each template title use "Digital Curation Centre" "NSF-GEN: Generic", etc.

the graph seems like it isn't going to work for dmptool template data. especially if we include all historical templates, which is what i get currently from the CSV output and probably what we want to provide to users. if we only include active templates there are 36 total and w/inactive templates the total is 55 - either way the total number and length of template names poses design challenges. might be easier just to include the report in the single dropdown menu at the top #1690 do you have a preference for whether we include all templates (active and inactive) or just active templates @sjDCC ?

the 'time picker' is not included in the requirements and can be removed.

**Comment by johnpinto1** [comment]
Attached are screen shots: 
First with no data for Last month
![NoData](https://user-images.githubusercontent.com/8876215/55009258-285a9280-4fda-11e9-976a-938edba4cf6a.png)
With data for Last Month
![LastMonth](https://user-images.githubusercontent.com/8876215/55009310-38727200-4fda-11e9-9739-ab1c719eeae3.png)

3 Months
![3Months](https://user-images.githubusercontent.com/8876215/55009282-314b6400-4fda-11e9-8d64-3242821689a5.png)

6 Months
![6Months](https://user-images.githubusercontent.com/8876215/55009407-63f55c80-4fda-11e9-96d0-0b60188be4df.png)

9 Months
![9Months](https://user-images.githubusercontent.com/8876215/55009431-6f488800-4fda-11e9-9252-b53326432169.png)

12 Months
![12Months](https://user-images.githubusercontent.com/8876215/55009461-7a031d00-4fda-11e9-96bb-d038acfdc34e.png)

Also CSV Headers changed for "No of Templates" now:
Date,Standard CRUK Template,Hartstichting,AHRC Data Management Plan,Horizon 2020 DMP,LSE Data Management Plan for undergraduate and master's students dissertations,MRC Template,ESRC Template,LSE Data Management Plan for an undergraduate dissertation,LSE Bureau van Dijk Hard drive/Historical dataset access form,LSE Data Management Plan,ERC DMP,LSE Data Management Plan for taught master's students,Copy of LSE Data Management Plan for taught master's students,DCC Template,EPSRC Data Management Plan,Wellcome Trust Template,BBSRC Template,LSHTM DM Plan for research projects,NSF - generic,AHRC Template,NERC Template,Count 
Feb 2019,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,8 Jan 2019,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1 Dec 2018,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 Nov 2018,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 Oct

**Comment by magdalenadrafiova** [comment]
this does not work for me - I can see that there is now option for no of plans by template, but when I am trying to choose the topic in the drop down menu I am unable to select template - I can only select users and plans... 
![template - not showing](https://user-images.githubusercontent.com/47178106/55472731-c36bf180-5604-11e9-9340-a2c4524b5ac6.PNG)

**Comment by johnpinto1** [comment]
@xsrust The rake task *rake stat:build* will need to be run. to display data for @magdalenadrafiova issue.

**Comment by johnpinto1** [comment]
My mistake. Pressed wrong button and closed issue.

**Comment by dsisu** [comment]
I get same error as Magdalena (i.e. option to select template is not present). In addition, the 'Time Picker' function returns a 'page unavailable' error.

**Comment by xsrust** [comment]
@dsisu @magdalenadrafiova I re-ran the task as John asked so this should be working now, can you test

**Comment by dsisu** [comment]
Hi, the graphic at the bottom of the page displays some data but it's not correct. If you select view last month's data vs view last three months, it outpust different number of templates for March.

In terms of usability:
- it is not obvious that you only get the figures (number of plans per template) if you hover over the graphic;
- please insert space before the title 'No. of plans by template' and put it in line with the time picker and download function. Without the space above it, the heading ends up looking like a caption for the graphic above (rather than the title for the graphic below).

**Comment by johnpinto1** [comment]
@dsisu There is a bug in the code for retrieving the Stats data. Hence the discrepancy.
The usability issues should be easier to fix.

**Comment by johnpinto1** [comment]
@xsrust @briri I have identified the cause of the discrepancy in the "No. of templates" statistics for the same month in different time periods. The cause is that each version of the same template has its own count, e.g., in my local Stats table I have the row

**id	count	date	type	org_id	created_at	updated_at	details**
`39 832	8	2019-02-28	StatCreatedPlan	1 005 339 509	2019-04-08 13:25:20	2019-04-08 13:25:20	{"by_template":[{"name":"Standard CRUK Template","count":1},{"name":"Hartstichting","count":1},{"name":"AHRC Data Management Plan","count":3},{"name":"AHRC Data Management Plan","count":1},{"name":"AHRC Data Management Plan","count":1},{"name":"AHRC Data Management Plan","count":1}]}`

`39 833	2	2019-03-31	StatCreatedPlan	1 005 339 509	2019-04-08 13:25:20	2019-04-08 13:25:20	{"by_template":[{"name":"Horizon 2020 DMP","count":1},{"name":"AHRC Data Management Plan","count":1}]}`
`

Each of the data items with name "AHRC Data Management Plan" represents a different version of the template with name "AHRC Data Management Plan" and since `{"name":"AHRC Data Management Plan","count":3}` is first it is displayed in the chart. The other version counts for "AHRC Data Management Plan", are lost.
![NoOfTemplates-Feb2019](https://user-images.githubusercontent.com/8876215/55786828-eab33a80-5aac-11e9-87a1-68d7e4ab03aa.png)

I will fix this issue by merge all the different versions of a templates data.

**Comment by johnpinto1** [comment]
@xsrust @briri Also noticed that the figures for a particular month period the *No. plans by template* by *No. plans during last year* sometimes differ. So there are several bugs.

The hart  for *No. plans by template* does not correctly display the Json sent back. I think it is a *time period* .

**Comment by briri** [comment]
seems like we would need to aggregate the counts at the template family level

**Comment by johnpinto1** [comment]
@xsrust Yes your right @briri I managed to do that (need to clean code before committing). Found the bar chart data was incorrectly being displayed with correct data in because each time period needs to have the same template names with count set to 0 if they do not have data.

**Comment by johnpinto1** [comment]
@sjDCC @xsrust @sjDCC @dsisu @dsisu  I still not quite there but I think the **No. plans by template
** bar chart stacked is visually better, e.g., 
![Selection_184](https://user-images.githubusercontent.com/8876215/55950759-8da2ba80-5c4d-11e9-95d2-9dfa1823b589.png)
![Selection_185](https://user-images.githubusercontent.com/8876215/55950836-bdea5900-5c4d-11e9-9aaf-f22079293ab9.png)
![Selection_187](https://user-images.githubusercontent.com/8876215/55950947-fa1db980-5c4d-11e9-83c0-78806e249c85.png)

**Comment by johnpinto1** [comment]
Current changes screen shots
![Selection_190](https://user-images.githubusercontent.com/8876215/56119781-b637f680-5f64-11e9-876a-fcf55e7d1050.png)
![Selection_189](https://user-images.githubusercontent.com/8876215/56119782-b637f680-5f64-11e9-953c-8f576731c0e3.png)

**Comment by sjDCC** [comment]
Hi @johnpinto1 

This looks good thanks. It doesn't seem to have data for the last 2 months though. Is this an error or because we haven't updated stats?

Also, I expected to see a different popup per colour of the bar so there's a label for AHRC, another for BBSRC etc. It's one label for them all so you have to count through the list to find the relevant colour. Is it possible to have a label per segment?

![Capture](https://user-images.githubusercontent.com/6169940/56305244-cbb14a00-6137-11e9-8f11-65fcb18412f1.PNG)

Think it's good to deploy. We can always improve in light of feedback

**Comment by xsrust** [comment]
Hi @sjDCC The lack of data since January is because -dev isnt actively used, and we last cloned the database over in January

**Comment by johnpinto1** [comment]
Hi @sjDCC. I used the default popup display. I am sure there must be a way to configure the chart to show each a different popup for each colour. I will need to find some examples.
