### ISSUE TITLE
URL in confirmation email is invalid

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#169]
The 'confirm your email' notification contains an invalid link. It looks like its just grabbing part of the hostname (e.g. uc3-roadmap-stg instead of uc3-roadmap-stg.cdlib.org) and so its resolving to www.hostname.com in the browser (e.g. www.uc3-roadmap-stg.com).

**Comment by xsrust** [comment]
Currently, the link is defined in application.rb, line 84:
`config.action_mailer.default_url_options = { :host => "#{Socket.gethostname}" }`

I propose we add a hostname to the branding.yml and use this to resolve the host address instead.

ex:
`config.action_mailer.default_url_options={host: Rails.configuration.branding[:application][:hostname]}`

**Comment by xsrust** [comment]
thoughts on this approach @briri @vyruss?

**Comment by raycarrick-ed** [comment]
what about using request.host - would that do it? that should give the full hostname including domain and without port. You could define as a constant from that as it can't change without a restart.

**Comment by xsrust** [comment]
It seems like request can only be used in the context of controllers and throws an error when used in application.rb

**Comment by vyruss** [comment]
We could put it in `production.rb` or `application.rb`, I'm not fundamentally opposed to `branding.yml` but I don't feel configuration settings belong in there. Since it's a thing that is set only once at deployment time I don't think it's too much trouble. We will of course need a fallback to avoid 500 errors if the value is missing, so: either the above variable or the default if it is undefined (what you get now).

@briri it would copy what the user is seeing, so if I'm accessing the server locally using `http://dmp-kb/` it would think that `dmp-kb` is the FQDN, leading to `www.dmp-kb.com` in the browser I believe

**Comment by briri** [comment]
I agree with @vyruss I would prefer to see it placed in the environments/production.rb etc.

**Comment by xsrust** [comment]
since production.rb gets committed back to the repository, do we want to just leave it implemented as is?  
We could add a commented example line to production.rb and make a note in the installation-instructions on the wiki that it will need to be defined during installation.

**Comment by briri** [comment]
Yes. that makes sense @xsrust. Wouldn't want to hard-code one of our domain names and then have a bunch of instances running in the wild that end up randomly sending traffic to us by accident ;)

**Comment by xsrust** [comment]
perfect.  I'll add it to the post-installation instructions and update production.rb accordingly.

**Comment by vyruss** [comment]
Recommend closing as done.
