### ISSUE TITLE
Remove sort name from Orgs

### ISSUE THREAD

**Issue by Bodacious** [DMPRoadmap/roadmap#1735]
Orgs are sorted in one dropdown column by the `sort_name` column

This adds additional steps for admins who have to manage an additional field.

Im sure we could manage this better, by writing a SQL query to achieve the same effect.

**Comment by magdalenadrafiova** [comment]
@briri and @xsrust is still still relevant?

**Comment by briri** [comment]
The field still exists in the database and we have begun using it to store the org name without the URL/abbreviation/location in parenthesis. For example "University of California, Berkeley" instead of "University of California, Berkeley (UCB)" or the new ROR style of "Instituto Mauá de Tecnologia" instead of "Instituto Mauá de Tecnologia (maua.br)".

I'm not sure that its even in use though, so it may be something we could delete.

**Comment by xsrust** [comment]
Yep, we've got the same content in there.

It looks like it's being used by the template_options controller, along with the new ROR hash->Org service currently.
I agree with the original comment that we could achive the same behavior with SQL though

**Comment by aaronskiba** [comment]
The `sort_name` has since been deleted. Closing this issue.
