### ISSUE TITLE
Guidance subgroups not distinguished in tabs when writing plan

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#1738]
I noticed that guidance subgroups appear with the full and appropriate name in the Guidance Selection on Project details page. But only the Org name is displayed in the tabs on the Write plan page. This prevents users from identifying the source of the guidance. In the screenshots below the UCD guidance tab should be identified as UCD Institute of Transportation (we may need to restrict the length of this field or ask for a short name), as opposed to just top-level UCD guidance.

This bug may have been introduced w/related issue #1409 
Display name for guidance subgroups is correct in DMPTool production currently (screenshot 3) - just truncated

![screen shot 2018-07-16 at 3 46 52 pm](https://user-images.githubusercontent.com/12703638/42787705-8f4c170c-8910-11e8-8af5-f6bc8925a64c.png)

![screen shot 2018-07-16 at 3 45 00 pm](https://user-images.githubusercontent.com/12703638/42787712-94812208-8910-11e8-8407-ab4eec6d191d.png)

![screen shot 2018-07-16 at 4 02 38 pm](https://user-images.githubusercontent.com/12703638/42788046-14a1c360-8912-11e8-9bfe-b4230ebba489.png)

**Comment by briri** [comment]
This will unfortunately turn out to be quite a bit of work to organize in the way you describe @stephaniesimms. Right now it groups all guidance by Org and loops through those orgs to create the tags. All of the underlying helper methods key off of the Org id as well. We would need to completely restructure the logic to raise it to the guidance group level. 

In this screenshot you can see that both of my guidance groups appear within the UCOP tab:
![screen shot 2018-07-18 at 2 25 29 pm](https://user-images.githubusercontent.com/1204467/42908969-4356fb36-8a97-11e8-93ab-7d1d659e25ec.png)

Another option might be to group the thematic guidance by guidance group within the Org tab. Maybe something like this (we would have to play around with the layout):
![screen shot 2018-07-18 at 2 33 53 pm](https://user-images.githubusercontent.com/1204467/42909068-aff0b1a6-8a97-11e8-8d03-d5dcba4cc329.png)

**Comment by briri** [comment]
@stephaniesimms refactoring to achieve the separate tabs for optional subsets would would require quite a bit of refactoring. Right now everything is keyed off of and grouped by Org. The optional subset designation has seemed to have lost its relevance now. It appears at the same level as regular guidance.

In the following screenshots, DMPTool is a top level guidance group and School of Astrophysics is a subset (both belonging to the UCOP org).
![screen shot 2018-07-18 at 2 44 58 pm](https://user-images.githubusercontent.com/1204467/42909491-31b71e7c-8a99-11e8-91ad-5df230a2d08c.png)


![screen shot 2018-07-18 at 2 46 34 pm](https://user-images.githubusercontent.com/1204467/42909551-69acbe4a-8a99-11e8-9eee-ebceba4cfc4f.png)

A lost cost approach to making things at least a bit clearer would be to simply append the guidance group name before the theme name on the accordions:
![screen shot 2018-07-18 at 2 48 22 pm](https://user-images.githubusercontent.com/1204467/42909652-bdebb9c0-8a99-11e8-9ff3-ccea34dbb43d.png)

Note though that our guidance selection will now look like the one above instead of the:
    DMPTool
       |
       ------- School of Astrophysics

**Comment by stephaniesimms** [comment]
we talked about this during the admin webinar and i don't think it will be acceptable to admins to lump all guidance subgroups in w/guidance for their org. it's also highly undesirable for dmptool to be restricted to using the "UCOP" label for generic guidance in the tool. end users don't know what UCOP is necessarily so we need to be able to display some batch of guidance as "DMPTool" - sounds like this requires more discussion.

**Comment by stephaniesimms** [comment]
the "dmptool" guidance is the same issue as that for subgroups: both use the guidance group name as the display name, but this is no longer possible w/the approach taken in #1409

**Comment by xsrust** [comment]
Hi all,
Re-factoring this piece of code to display tabs as guidance-groups instead of orgs is trivial.
The data structure created is [orgs][guidance_groups][themes][guidances], so it's easy to change the display to whatever we agree on.

@stephaniesimms , I believe your suggestion of guidance-group names as tab titles has some limitations and kindof contradicts what we were doing in #1409.  

The goal was to concatenate the annotations into the same tabs as the themed guidance from the org.  Which tab would annotations go into?  the main group or the optional subgroup, each of which may have names unrelated to the org's which could confuse end-users.

I like @briri's suggestion of showing the group in the accordion, if there are multiple groups.
Notationally, if 'School of Astrophysics' guidance isnt a sub-category of UCOP, or if the 'DMPTool' guidance belongs in a different org, the solution should be to move those guidance-groups to separate orgs, not shoehorn in a display-name for guidances which dont belong as part of that org.

For separating out the subgroups within the org-labeled tab, If @briri's suggestion isnt acceptable, perhaps we could have a heading with the title of each subgroup within the org which groups the themed guidance from that group together.  That way it's clear where the guidance comes from.

**Comment by xsrust** [comment]
To summarize my understanding of the above more formally:

### Just Annotation:
- tab titled after org-short name
- only annotation in tab
### Annotation + main group
- tab titled after main guidance group
- Annotation and themed guidance in tab
### Annotation + n gudiance groups(Main + subset(s))
- Tab per guidance group
- Tabs titled after guidance group name (inc main group)
- Annotation in main guidance group tab
### Annotation + n guidance groups(All subsets)
- Separate tab, titled after org for the annotation
- Tab per guidance group, titled after guidance group

## lingering questions
- We are now using the `guidance_group.name` field as a limited display field.  Would we prefer to concatenate this name, or to add an additional field to guidance groups for their short (N-Character) display name?  
- Do we care that annotations from an org will appear in differently named tabs? i.e. if one question has no themed guidance, the tab will be the org-name, and if the next question does, the tab title will be the main guidance group name.  A possible solution, if we do care, would be @sjDCC 's suggestion that we re-name the 'main' guidance group's tag to the org's display name.

**Comment by sjDCC** [comment]
Thanks for this @xsrust 

My only suggested change is indeed to make the 'Annotation + main guidance' adopt the org-short name so it's consistent throughout the interface. I would only apply guidance group names to subsets. It would be good to give a short display name for this, but if we don't want to add another field we can just crop the name at the set number of characters.

**Comment by stephaniesimms** [comment]
just chiming in to confirm that i agree w/ @sjDCC - and glad to know refactoring is straightforward @xsrust

**Comment by sjDCC** [comment]
This looks good to close out. I created some sub-group guidance for UCD and confirmed that this filters into a separate tab. I haven't been able to add an annotation though to check the combination of question-specific guidance and themed guidance.

![capture](https://user-images.githubusercontent.com/6169940/44219491-11b2aa00-a174-11e8-873c-bf3e82f666b5.PNG)

**Comment by sjDCC** [comment]
This is filtering properly and combines annotations and themed guidance. Closing out
