### ISSUE TITLE
GET plans/export/:id

### ISSUE THREAD

**Issue by jollopre** [DMPRoadmap/roadmap#174]
When trying to export a Plan, an error is raised at app/models/exported_plan.rb (line 69) which prevents from exporting a plan.

**Comment by raycarrick-ed** [comment]
adding this in because it's blocking other work and looks like a quick fix

**Comment by raycarrick-ed** [comment]
exported plan no longer has owner field but was using it. Now has owner method which goes through roles and grabs the first creator of which there should only be one. Likewise access to template now goes through plan.

**Comment by raycarrick-ed** [comment]
fixed by https://github.com/DigitalCurationCentre/roadmap/commit/250b58ab54c9bf983f0710a52553f3cdb405e5e3

**Comment by stephaniesimms** [comment]
This might be fixed but I can't confirm because neither route for plan export is working. Clicking Export from the My plans page results in screenshot 1 below and the Export button from the plan writing/editing page throws the error below in screenshot 2 below:

![export-button](https://cloud.githubusercontent.com/assets/12703638/24380315/95256968-12ff-11e7-8dfd-a272822648dc.png)

![export-modal](https://cloud.githubusercontent.com/assets/12703638/24380333/9cb9e028-12ff-11e7-9d77-f2e96a31b936.png)

**Comment by jollopre** [comment]
@stephaniesimms, the issue #197 is addressed to fix the problems with exporting into different formats. At a first glance, there are references in code to 'projects' which no longer exist.

**Comment by stephaniesimms** [comment]
This is working now. Remaining export issues noted in related tickets.
