### ISSUE TITLE
`rails s -e production` should accept asset file with fingerprint in their name too

### ISSUE THREAD

**Issue by Yu-Chieh-Henry-Yang** [DMPRoadmap/roadmap#1799]
In other words, `rails s -e production` doesn't work with `npm run bundle -- -p` but work with `npm run bundle` while it is meant to work `npm run bundle -- -p` from my understanding.

**Expected behaviour:**
`rails s -e production` with `npm run bundle -- -p` together should display a functional website with correct image and layout

**Actual behaviour:**
It doesn't. It display this:
![screen shot 2018-08-09 at 3 38 06 pm](https://user-images.githubusercontent.com/19463606/43881385-2f68810c-9beb-11e8-9a9d-9440854acf42.png)

**Steps to reproduce:**
Follow the wiki installation guide and use `npm run bundle -- -p` instead of `npm run bundle` because we are going to run the app in production environment (`rails s -e production`). 

**Note**
For files inside `public/javascripts` and `public/stylesheets`, if I remove the `-fingerprint` part in their filename, then the pages shows correctly. I don't know why this is because `def fingerprinted_asset(name)` inside `app/helpers/application_helper.rb` seems to work correctly, as I have checked using byebug. I was expecting it to be buggy so that it can produce the observed bug

**Comment by Bodacious** [comment]
Hi @Yu-Chieh-Henry-Yang 

This is a configuration feature of Rails, not an issue with this codebase.

By default, in production mode, Rails will not serve static assets from the application. This is because developers are expected to configure their server (NGINX or Apache) to serve these static files instead. This improves performance, as the request for a static asset is handled at a higher level than the Rails app.

Look at the environment configuration file for the production environment.
https://github.com/DMPRoadmap/roadmap/blob/master/config/environments/production.rb#L25

You can override this configuration by setting the `RAILS_SERVE_STATIC_FILES` ENV variable:

``` bash
RAILS_SERVE_STATIC_FILES=true rails server -e production
```
