### ISSUE TITLE
Plan edit: Missing translations and spacing issues

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#182]
The edit plan page has some missing translations and some spacing issues on the answer status messages. The last one is on an answer that has yet to be created. 

![screen shot 2017-03-17 at 1 46 41 pm](https://cloud.githubusercontent.com/assets/1204467/24062282/3aca51f2-0b18-11e7-8a38-7bdc963ddbc9.png)
![screen shot 2017-03-17 at 1 46 20 pm](https://cloud.githubusercontent.com/assets/1204467/24062283/3acbfdfe-0b18-11e7-82de-18431a386772.png)

**Comment by raycarrick-ed** [comment]
https://github.com/DigitalCurationCentre/roadmap/commit/ea71f05769f349664752efeabca17df9c7dbb1cd
fixes the spacing issue and introduces untranslated strings for the status update. Still need to work out a way to get the translated strings into the JS but better than an error string for now.

**Comment by raycarrick-ed** [comment]
fixed in https://github.com/DigitalCurationCentre/roadmap/commit/436a250aff79c2bc9d16bcd14609d7b7a477dd43
but internationalisation still to do in ticket #204 

This turned into a bigger change than I anticipated:

- the answer status line was being written on page load (but with all sections closed you couldn't see it) and it was wrong in that it didn't use the "time ago" style

- when the section was opened the answer status was overwritten by the JS based off plan/status which was doing a lot more work than needed and was really there for the pessimistic locking.

- answer status is no updated only on page load and answer save so no longer needs page/status calling

- the progress bar was also running off plan/status but now gets drawn on page load and page save so again no longer needs page/status.

- The progress bar is now separated out into a partial so it can be called in the two places

- the space used bar is removed as it seemed no one was sue we want it. If that changes it can be reintroduced.

- the section progress (X questions Y answered) is much the same. updated on page load and question save and so doesn't need page/status

so the page status no longer gets called here. Howvere I have left it in place for now as I am not 100% sure it isn't used anywhere else. The plan.js gets simplified a lot now. opening an accordion should involve less work. But I an sure there will need to be some optimisations again in the stuff I have added.
I have added a note into ticker #204 that it needs to take acocunt of these as well.

**Comment by sjDCC** [comment]
We may have introduced a bug here @raycarrick-ed as legacy data is showing as 47 years old...

![capture](https://cloud.githubusercontent.com/assets/6169940/24516958/5ea00a7a-1574-11e7-9e40-9e815014004e.PNG)

**Comment by raycarrick-ed** [comment]
@sjDCC could you recheck this. I suspect the latest changes had not yet been deployed at that point (see Brian's slack meesage on 31st). I was seeing this error myself before but not now. If it does still happen could you let me know which install, plan, phase and question you're seeing it with and I can then dig into it more.

**Comment by stephaniesimms** [comment]
Working as expected
