### ISSUE TITLE
Show comments by default w/o having to click "Show" link

### ISSUE THREAD

**Issue by xsrust** [DMPRoadmap/roadmap#1873]
Please complete the following fields as applicable:

**Expected behaviour:**
All comments for a question display beside that question.
A user should be able to read each comment without clicking a 'show' button
A user should be able to read multiple comments at the same time
Newest comments display at the bottom of the list

**Actual behaviour:**
![screen shot 2018-09-12 at 11 34 19 am](https://user-images.githubusercontent.com/7352616/45419707-f60dc700-b67f-11e8-8bca-b1f80e29b75d.png)

**Comment by stephaniesimms** [comment]
this is a known issue and something we planned to address when implementing the substance editor. if there's a short-term, low-effort solution feel free to make suggestions @xsrust

**Comment by xsrust** [comment]
Something like:
<img width="374" alt="screen shot 2018-09-13 at 19 58 34" src="https://user-images.githubusercontent.com/7352616/45509433-7c64fe80-b78f-11e8-9526-cffb84b80ed1.png">

**Comment by stephaniesimms** [comment]
i created a new issue #1886 to capture anything not addressed here and any new suggestions to be addressed as part of next sprint.

**Comment by dsisu** [comment]
I guess this particular issue is solved, as far as I can see. However, we still have a lot of white space under the question and can't see the full answer. We have to click on the answer box to see the full text. The second question of my particular plan won't expand whatever I do. It was temporarily fitted with a vertical scroll bar. I understand the answer display will be fixed in the new release. Is that right?

**Comment by stephaniesimms** [comment]
Show comments by default is working as expected. this is a good first step @xsrust - closing this issue. And yes @dsisu there's a separate bug issue to fix the text editor sizing/display problems for questions in the next sprint #1683
