### ISSUE TITLE
Unable to switch on feedback as org admin

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#1877]
To test #1845 I tried to configure feedback for a few different orgs and found I couldn't switch this on. Initially I got an error that there had to be an email message (my message text was deleted on save) and then I got an error about the logo.
![turn-on-feedback](https://user-images.githubusercontent.com/6169940/45599305-0d7ee400-b9e1-11e8-9fe5-e5682bb5b4a6.PNG)
![request-feedback](https://user-images.githubusercontent.com/6169940/45599304-0d7ee400-b9e1-11e8-860d-9bc37e77d93d.PNG)

**Comment by stephaniesimms** [comment]
I can't enable the 'Request Feedback' function either. It seems to be trying to validate the email subject line, which we removed recently (see error msg). The feedback function should be validating the following only:
- a Contact email on the org profile  
- a Message on this page

![screen shot 2018-09-16 at 4 01 25 pm](https://user-images.githubusercontent.com/12703638/45601965-2a5bed00-b9ca-11e8-95ea-e07ebc83e3bc.png)

**Comment by briri** [comment]
The error about the logo is due to the fact that Dragonfly stores the logo files on disk and then stores a reference to those files in the database. When you redeploy the application these logos can be lost (also can happen when restoring the database from a backup). The reference the DB has does not match a file on disk.

I'm not sure what the best approach for dealing with that would be. If this were to happen in a production environment then its a legitimate error and likely something we would want the org admin to fix.

**Comment by stephaniesimms** [comment]
hopefully it's a non issue @briri since a logo should not be required to create/save an Org. it's completely optional and should not affect switching on feedback.

**Comment by sjDCC** [comment]
Still get the logo error on this. The message text I entered is wiped and the yes/no reverts back to 'no'
![logo-error](https://user-images.githubusercontent.com/6169940/46549779-0efa4880-c8cb-11e8-9cc8-a6521e480635.PNG)

If I remove the logo this saves properly so validations are ok otherwise. If the logo is sorted by Dragonfly I'm happy to close out. Or remove the need for a logo to exist as it's optional. We don't want admin to have to re-upload.

**Comment by stephaniesimms** [comment]
yes the logo is optional and shouldn't prevent saving anywhere in this area. hopefully that's the cause of the error msg and you can just remove the validation requirement @briri

**Comment by sjDCC** [comment]
The error message is gone which is great. I noticed that the save action deleted the logo though too, which ideally it wouldn't. Is it possible to avoid this?

**Comment by briri** [comment]
Hey @sjDCC. This is an issue with use copying databases from one server to another and is really very unlikely to happen in the real world. 

The code (dragonfly gem) we use saves the physical logo file onto the hard disk and then stores the location of that file in the database. When you interact with the website it looks for the logo and tries to load it. In these scenarios you will notice that the logo does not display but instead shows some text like `University of Edinburgh logo`. 

When we copy the database from production to roadmap-stg for example the database thinks your logo should be here: `/public/system/dragonfly/production/2018/01/01/4g8453h3hg_my_logo.png` but because the database was copied and the logo files were not copied over to the new server, it cannot find them. 

This was producing the old error message. We have introduced code to try and locate the file (it could be there but with a different location, e.g. `/public/system/dragonfly/stage/2018/03/20/otkrhh_my_logo.png`). If it cannot find it however it needs to remove it to get the system to save your record.

**Comment by sjDCC** [comment]
Great. Happy to close out then. Thanks for explaining :)
