### ISSUE TITLE
Change msg text for removing User permissions 

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#1880]
As an admin, when I remove user permissions on the Users page and click 'Save' the banner message is weird (see screenshot). Please update text to the following for all permissions changes:

"Successfully saved permissions"

![screen shot 2018-09-16 at 4 08 44 pm](https://user-images.githubusercontent.com/12703638/45602013-34cab680-b9cb-11e8-9eb2-3f53f66b2802.png)

**Comment by sjDCC** [comment]
This is fine when you save on the full users list viewed as super-admin. We have 'permissions' in the message not nilclass. Since the error was on the org admin page though, I'll leave open to test there too

![nilclass](https://user-images.githubusercontent.com/6169940/46549102-dce7e700-c8c8-11e8-9f81-8229bf9935a8.PNG)

**Comment by sjDCC** [comment]
Looks good. Closing out
