### ISSUE TITLE
Guidance switcher 

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#198]
The new guidance options to tun on/off guidance display blank for existing plans. For new plans, the full list appears but messages don't display when changes are saved (they all save accurately though). Also, the cancel button is misformatted.

Think this item needs some UX input to determine how it forms part of the create plan workflow and how users are driven to turn on/off guidance. It probably needs an icon/button to direct people to this from the plan editing interface as they won't necessarily think to look under plan details.

![capture](https://cloud.githubusercontent.com/assets/6169940/24198082/38df84f6-0efc-11e7-91b9-c79c2f343962.PNG)

**Comment by raycarrick-ed** [comment]
poss add rake task to migrate old plans

**Comment by xsrust** [comment]
It looks like the reason these arent displaying is, as Ray said above, that we need a rake task or change to the migration so that this relationship exists between the previously created plans and the guidance groups.  

A potential other fix is to change the way we determine this relationship.  Currently, there is a record in `plan_guidance_groups` for each possible guidance group, with a field for whether or not these are selected.  This means, in DMPonline, we will have 45 records in this table per plan. Additionally, if guidance groups are added later by funder or other organisations, they will not be displayed as options for plans created in the past, as they will not exist in the `plan_guidance_groups` table.

I think it makes more sense to change the implementation so that a record in `plan_guidance_groups` denotes that the user/s who are editing that plan want to have the guidance displayed, and that the total list of guidance groups which can be selected is taken from the db when the page is loaded so that we ensure all guidance groups are displayed for past and present plans.

@vyruss @raycarrick-ed  does this change make sense?

**Comment by vyruss** [comment]
I agree with @xsrust that we should only store the `guidance_group`s selected for display, in `plan_guidance_groups`. This makes changing the "old schema" migration, in a way which keeps those per-plan guidance group display/hide selections, feasible.

**Comment by xsrust** [comment]
current implementation and front-end fixed in 
https://github.com/DigitalCurationCentre/roadmap/commit/f93eeed5a787928560dacba24f9f3ea841ca849d and https://github.com/DigitalCurationCentre/roadmap/commit/b7a43e9491056bda9509d413e1c95fdc63d98fcd

**Comment by stephaniesimms** [comment]
After various testing w/creating new plans and changing my Org affiliation, I only see Guidance if it exists for a funder template (e.g., Wellcome, Academy of Finland) or if I get my institutional template and there is institutional guidance (e.g., AMK). There seems to be no way to get the DCC Guidance, even when I set my Org to DCC. Some templates are devoid of Guidance altogether (e.g., Horizon2020, NIH).

Changing my Org affiliation has no effect on displaying guidance for previously created plans, but I suspect this is because so few actions result in any Guidance display at all... @sjDCC should clarify the expected behavior for Guidance.

**Comment by sjDCC** [comment]
Hi @stephaniesimms Have you been trying to add guidance via the choices you'd made under the create plan wizard e.g. by setting org as DCC here? I think these have essentially been disabled now and the responses to the org and funder questions just pull in the template not the guidance. The way to turn on/off guidance is now under plan details. I trialled switching on DCC guidance in a few templates and it works ok on both staging and DMPonline test.

I've made a note in ticket #150 about preferred guidance display. Ideally the users own org (or chosen org affiliation at create plan stage) would come on as default, but could be switched off again. Guidance that is part of the template (e.g. EC guidance on H2020 template or Edinburgh guidance on UoE template) should always display and not be able to be switched off.

**Comment by stephaniesimms** [comment]
@sjDCC Yes I was. Thanks for clarification re guidance. I did expect my org guidance to appear as a default - and think we might want this in the future..? At least in the US, funders offer few specifics and users need some additional guidance in order to be able to answer the questions. So it should be easier to know/find that more guidance is available. But in the short term if there's a place to switch it on and off that should work.

**Comment by sjDCC** [comment]
@vyruss can you confirm that we'll be able to have the institutional guidance automatically switched on? This would be based on the selection or org made under create plan. I'd rather this than have users need to switch it on post plan creation. Definitely good for them to be able to switch it off and select others as needed though.
