### ISSUE TITLE
Query for organizational plans inefficient

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#2007]
The newly updated query for organizational plans on the my dashboard page is inefficient especially when run against the 'is_other' org.

We should also probably skip the load of organizational plans completely when the user's org 'is_other'

**Comment by sjDCC** [comment]
How are you generating this view @briri As far as I know there is logic that prevents anyone from being an org-admin when their affiliation is 'other org' as this makes no sense. Any changes they make to the profile would affect a large group of people.

I've just tested the workflow to see if I could create a view of all plans from 'other org' and couldn't. Strangely I could assign admin rights to anyone who has an affiliation of other org, but when I did this to a new test account I created, no admin dashboard appeared. I guess the logic is filtering it out at the display point rather than the assignation of rights.
![capture](https://user-images.githubusercontent.com/6169940/51903405-fcdd7200-23b3-11e9-906a-bd6f392ae9f4.PNG)
![capture2](https://user-images.githubusercontent.com/6169940/51903406-fcdd7200-23b3-11e9-8033-a383fc2fc01d.PNG)

Happy to leave open if there's work to do on this or should we close?

**Comment by sjDCC** [comment]
Change logic to prevent admin rights being assigned to someone without a real org. i.e. if org = other

**Comment by sjDCC** [comment]
@briri is this a ticket we can close?

**Comment by briri** [comment]
Yes I think so
