### ISSUE TITLE
Stop storing the locale in the session

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#205]
@jollopre and I had a conversation about the way we are storing the locale in the session. The conversation started because we were having difficulty building a test to make sure that FastGettext was reporting the correct locale after changing the language setting for an Org or User.

The Devise test helpers do not create a session, so FastGettext always returns the default locale. Rails also warns against storing this information in the session object in its I18n documentation.

We should consider updating the ApplicationController so that it no longer relies on `session[:locale] ` and instead simply checks the current_user.language, then current_user.org.language and finally uses the default if those other 2 are not set.

We can accomplish this by replacing:
```ruby
 # Sets FastGettext locale for every request made
  def set_gettext_locale
    FastGettext.locale = session[:locale] || FastGettext.default_locale
  end

  # PATCH /locale/:locale REST method
  def set_locale_session
    if FastGettext.default_available_locales.include?(params[:locale])
      session[:locale] = params[:locale]
    end
    redirect_to root_path
  end
```
with something like
```ruby
  def set_gettext_locale
    # FastGettext.locale = default OR the Org's language OR the User's language if set
    FastGettext.locale = FastGettext.default_locale
    FastGettext.locale = current_user.org.language unless current_user.org.language.nil?
    FastGettext.locale = current_user.language unless current_user.language.nil?
  end
```
We would then need to remove the calls to the old `set_locale_session` and remove the `session[:locale]` lines from the sessions_controller.rb

**Comment by vyruss** [comment]
Or maybe?
```ruby
def set_gettext_locale
  # FastGettext.locale = default OR the Org's language OR the User's language if set
  if current_user.language.nil?
    if current_user.org.language.nil? 
      FastGettext.locale = FastGettext.default_locale
    else 
      FastGettext.locale = current_user.org.language
    end
  else 
    FastGettext.locale = current_user.language
  end
end

**Comment by jollopre** [comment]
If we want to get rid of the session. It is needed to have the state in the URL:
- either URL parameter for the locale selected (e.g. http://example.com/en_GB/foo/bar)
- or query parameter (e.g. http://example.com/foo/bar?locale=en_GB)

since we allow the registered/anonymous users to change the language for the session. I would be personally inclined to choose query parameter since it is something not mandatory in URLs.

The function at application_controller.rb could be something like:

`def set_gettext_locale
	if !params[:locale].nil?
		FastGettext.locale = FastGettext.default_available_locales.include?(params[:locale]) ? params[:locale] : FastGettext.default_locale
	elsif !current_user.nil?
		FastGettext.locale = !current_user.get_locale.nil? current_user.get_locale : FastGettext.default_locale
	else
		FastGettext.locale = FastGettext.default_locale
	end
end`

The method get_locale (e.g. https://github.com/DigitalCurationCentre/roadmap/blob/development/app/models/user.rb#L74) already takes care of choosing either user default language or his/her org default’s language. Bear in mind that this will hit the database anytime a logged in used changes page and the locale state in the URL is absent.

**Comment by vyruss** [comment]
I'm strongly against including the locale in the URL. A parameter is fine, but let's only use it for anonymous browsing and _*if*_ a language choice has been made.
