### ISSUE TITLE
Full text API

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#2086]
Extend the current plans API for authorised admins to harvest the full text of plans from their org.

**Comment by xsrust** [comment]
Adding this as a new index endpoint for the plans-api.

Using Sidekiq for background-job processing:
https://github.com/mperham/sidekiq
Sidekiq adds an additional dependancy on Redis, but will enable us down-the-line to support thinks like weekly email reports, notification batching, etc.

I'm implimenting directly via sidekiq instead of using it as an activejob adapter since documentation shows that this is much faster.

Planning on running through once per night (for specified orgs) to generate this JSON object and save it out to either disk or S3. [Rails 5.2 and ActiveStorage would make this configuration easier]

Then fetch this and send to the user via the API-endpoint.
IF the file does not exist, I'll get it to kick-off the process of generating one, and reply with 201.
Then when they check back, they will get the JSON object. (assuming processing is complete)

**Comment by sjDCC** [comment]
I'm not best placed to UAT this, but since it's been out on -dev and flagged to a couple of unis I assume all is ok. Do you know if they trialled it?

**Comment by xsrust** [comment]
Closing this as API Implimented.
Will add other issues for additional API features
