### ISSUE TITLE
Drag feature of TinyMCE boxes has disappeared

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#2093]
It used to be possible to drag the TinyMCE boxes to make them wider and longer on screen.

Please check config and reinstate this

**Comment by johnpinto1** [comment]
@sjDCC @xsrust & @briri 

Parking this for now. as various different configurations I tried did not work. It is is because the default configuration in our *tinymce.js* has parameters that currently prevent this. The difiiculty is finding the right overrides to not break other functionality we have. Will work it out as a background task whilst doing other bugs or features.

**Comment by johnpinto1** [comment]
@sjDCC @xsrust & @briri
Re-introduced only vertical expansion as horizontal dragging results in overlapping with other elements in flow.
![Selection_027](https://user-images.githubusercontent.com/8876215/59696331-b1512680-91e3-11e9-919e-c8b593644909.png)

**Comment by magdalenadrafiova** [comment]
We're not seeing the drag icon on DMP questions on front end or text boxes on admin interface. Perhaps it's being overwritten by local config. To check @xsrust

**Comment by sjDCC** [comment]
The drag and drop is displaying again on front end and admin interface.

Looks good. Thanks @johnpinto1 Closing out

**Comment by magdalenadrafiova** [comment]
Looks good

**Comment by mariapraetzellis** [comment]
Created a plan & a new template using the drag feature. Looks good.
