### ISSUE TITLE
Create Drop down for Organisations

### ISSUE THREAD

**Issue by Ebrahim1010** [DMPRoadmap/roadmap#2143]
Hi,

Is it possible to create a dropdown list for the Research Organisations section?

Thank you

**Comment by xsrust** [comment]
Hi,

I'm assuming you mean that you want to convert the typeahead box on the 'create plan page' to a dropdown type box instead?  Given how many organisations which may exist, we perfer the typeahead for clarity and usability.  Feel free to add a branded version of this view (`app/views/plans/new.html.erb`) which will use a dropdown instead for your instance.

See: https://github.com/DMPRoadmap/roadmap/wiki/Branding#views for more instructions

**Comment by Ebrahim1010** [comment]
Thanks Sam!
can you recommend a way to change the Organisation names listed under the Organisation field in the 'my profile' section as well the sign up section.

**Comment by xsrust** [comment]
Hi @Ebrahim1010 

Those names come from the `name` attribute of the `org` records on your database.  You can add more orgs to your DB in order to allow users to associate with them.

I also noticed that you guys don't have an 'Other' org

Make sure to set one up as detailed in the 'Installation Steps' In the wiki:
https://github.com/DMPRoadmap/roadmap/wiki/Installation#post-installation

**Comment by Ebrahim1010** [comment]
Hi @xsrust 

Thank you, we will try and implement this.
Can you point me to the exact location for where these Organisation sit

**Comment by xsrust** [comment]
Hi @Ebrahim1010 
 
All of the data for Ruby on Rails is stored in your Database.
There are a variety of ways to interact with this data.  

First, and easiest, would be to just add the organisation through the website.  Super-admin accounts should have the opportunity to add an organisation from the `admin/organisations` page.

Next, you can use the rails-console to add an org, see details:https://guides.rubyonrails.org/command_line.html

Finally, you could connect straight to your database (generally either Postgres or MySQL), and query/modify it via SQL statements.  

I would reccomend using either the front-end, or the console, as these will run data-validations.
Just set the `is_other` field to `true` on one org to mark it as your catch-all `other` org.

As for changing the names of others,
They can all be edited from the front-end at the table listed above.

**Comment by Ebrahim1010** [comment]
Hey @xrust

For your previous answer I was referring to create plan page as well as the sign up page.
Is there a way to keep the Organisation and templates separate.
I'm changing the Org names on the db and getting these type of errors: 
Operation failed: There was an error while applying the SQL script to the database.
ERROR 1451: 1451: Cannot delete or update a parent row: a foreign key constraint fails (`roadmap_development`.`templates`, CONSTRAINT `fk_rails_481431e1bd` FOREIGN KEY (`org_id`) REFERENCES `orgs` (`id`))
SQL Statement:
DELETE FROM `roadmap_development`.`orgs` WHERE (`id` = '8')

ERROR 1451: 1451: Cannot delete or update a parent row: a foreign key constraint fails (`roadmap_development`.`templates`, CONSTRAINT `fk_rails_481431e1bd` FOREIGN KEY (`org_id`) REFERENCES `orgs` (`id`))
SQL Statement:
DELETE FROM `roadmap_development`.`orgs` WHERE (`id` = '9')

The Organisations that I want to list are actual institutions whereas the templates are templates designed for individual departments of the University. Does that make sense.

**Comment by xsrust** [comment]
Hey @Ebrahim1010 
I'll try to respond to the separate points here:

### Modifying the DB
You might want to take a look at the data-model `db/schema.rb` and the validations in each model file in `app/models/*` before jumping over to SQL and changing things there.  

The way DMPRoadmap is designed,  Organisations create & maintain templates, so a Template without an organisation cannot exist.  This is expressed in the structure of the DB, and in the validations on the model files.

It looks like you're trying to remove organisations, rather than simply rename them.  SQL has the concept of Referential integrity, where if any of the `org_id` fields have the same value as the org your removing's `id`, you cannot remove it.  Otherwise, when searching for the Template's Org, we'd get an error.  If you do want to remove these, you need to ensure that none of the other tables reference the object your removing.

I really want to emphasize the importance of either using the `rails console` to modify the database, or using the interface as I detail below.  While SQL has foreign key validations, we have a number of other assumptions we make within DMPRoadmap about the data, which is not all captured in SQL validation.  Thus, it's quite possible to execute custom SQL which will save `invalid` data to the DB and cause errors in your application.



### Departmental templates
Within DMPonline, the instance the DCC maintains, we handle department-level templates in the following way:
1) Create an organisation for your university
2) Add multiple departmental templates for that organisation
3) Have your users select that organisation upon plan-creation
4) Have your users select the correct, departmental template from the list.

### Modeling Organisations
I'm not sure what you mean with 'actual institutions'.

In DMPonline, we have 'Funders' who's templates are appliccable to a range of users, and 'Institutions' who are essentially universities with templates, guidance, and customization available to their staff.  Both are 'types' of Organisation.

### Renaming Organisations
You should be able to navigate to https://<your.app.url>/super_admin/orgs and change these through the website.  This should be the safest way to modify the details for the organisation, as we've written and tested that functionality.
