### ISSUE TITLE
Share plan error

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#216]
I was trying to share a plan to test the locking and it threw up an error

![capture](https://cloud.githubusercontent.com/assets/6169940/24515936/f82622f0-1570-11e7-9a91-bd24929304cf.PNG)

**Comment by vyruss** [comment]
@xsrust is this `attr_accessible` related too?

**Comment by xsrust** [comment]
It's throwing a similar error.  I'll have a look

**Comment by xsrust** [comment]
it was, but there ended up also being some buggy logic in the controller, and broken mailers. 

fixed by: https://github.com/DigitalCurationCentre/roadmap/commit/aa30a45f49743913de9d28d60efc9e282b64618a, https://github.com/DigitalCurationCentre/roadmap/commit/e3cf05822b47d7322b856848f717fc0b1ac76865, https://github.com/DigitalCurationCentre/roadmap/commit/69ceb9caeced98b6db8fc4c937ed4151bbb99c53, and 
https://github.com/DigitalCurationCentre/roadmap/commit/b64fdddabd28a09764e40beab94cbe9e1f0399da

**Comment by stephaniesimms** [comment]
Working as expected
