### ISSUE TITLE
Shibboleth linking / create account error

### ISSUE THREAD

**Issue by pherterich** [DMPRoadmap/roadmap#2182]
Please complete the following fields as applicable:

My colleague is trying to link her Shibboleth account with an account she might have manually created a while ago (we forgot, sorry...)

**Expected behaviour:** 
I would expect having several attempts to do the linking after getting account credentials wrong the first time.

**Actual behaviour:**

We get to this screen once ![](https://user-images.githubusercontent.com/18707439/36552296-6c2c944e-17f1-11e8-860d-e8b4ce388152.png)

But then an error message shows and this goes away and the Shibboleth option is removed from her start page.

**Steps to reproduce:**
It's really hard to do when your account works. We tried in Chrome and then had another attempt in Explorer and are running out of browsers... is this best addressed by you just looking into her account in the backend or is this an issue more people have?

**Comment by xsrust** [comment]
Hi,

We've had this issue before and it's a peculiarity with the way Shibboleth works.  The sessions are quite 'sticky' so once you sign in to your SSO provider,  this attaches to your DMPonline session.  
When you go back to the homepage, but the option to sign in via shibboleth has been removed, This is because the service detects you already have a shibboleth session.  
Completing either the sign-in or create-account forms from that page will link your Shibboleth credentials with the account you sign into or create.

I agree that this workflow can be confusing and the user should be continuously re-routed to the sign-in/create-account split page once the shibboleth session exists.  Or we could make it explicit on the homepage when the SSO session has been created and will link to the account next logged into.

As for your colleague, if she has access to the email address, she should jsut go through the reset password workflow.  After that, she'll be able to link the account by signing-in on the page you see.  Alternatively, there is an option to link your Shibboleth account from the 'edit profile' page after you sign in with an email and password

**Comment by pherterich** [comment]
Thank you, Sam. That's super useful, we'll try those options and hope we can get her set up :smiley:

**Comment by Ebrahim1010** [comment]
@xsrust 
What are the steps for enabling the 'sign with your institutional credentials' option.
This is our new website https://dmp.lib.uct.ac.za/

**Comment by xsrust** [comment]
Hi @Ebrahim1010 
We have a wiki page on setting this up:
https://github.com/DMPRoadmap/roadmap/wiki/OAuth-Providers
