### ISSUE TITLE
Review and correct permissions for editing

### ISSUE THREAD

**Issue by raycarrick-ed** [DMPRoadmap/roadmap#220]
following on from
https://github.com/DMPRoadmap/roadmap/issues/219
these permissions ned to be implemented in the plan creation/editing workflow.

**Comment by raycarrick-ed** [comment]
Addressed in https://github.com/DigitalCurationCentre/roadmap/commit/a66f6256dbe7d1c5aa2ccd7b79f50f506dde4a64

**Comment by stephaniesimms** [comment]
I can change my own permissions on a plan, which should not be the case. I just reduced my permissions from Co-owner to Read only. I can only reduce my own permissions, not reinstate the higher level of access (i.e., I can't return my permissions to Co-owner). As a Co-owner I should be able to invite others but I should not be able to change my own perms.

**Comment by sjDCC** [comment]
This is what is currently on DMPonline live and test site (see screengrab). The original creator / owner of the plan shouldn't be able to edit their own role but can amend others. Is this how it presents for you too?
![capture](https://cloud.githubusercontent.com/assets/6169940/25620735/4aad7664-2f47-11e7-83b3-54e94f4baefa.PNG)

Stephanie, did you create the plan you're talking about. Perhaps you shared it with a secondary account you have since you described yourself as co-owner? It is confusing if co-owners reduce their own permissions as they wouldn't then have rights to change them back, but the original plan owner always would have the ability to do this.

**Comment by stephaniesimms** [comment]
yes @sjDCC , as a Co-owner I was able to reduce my own position which seems weird/undesirable (screenshot below). I think the solution is to prevent any user attached to a plan from editing their own role. 

![screen shot 2017-05-02 at 10 36 00 am](https://cloud.githubusercontent.com/assets/12703638/25630807/3992f15c-2f23-11e7-9251-481cbab7752f.png)

**Comment by stephaniesimms** [comment]
@sjdcc Just to confirm: new ticket looks good. This is definitely a bug and should be part of MVP. A user should never be able to edit their own perms.
