### ISSUE TITLE
Reset password functionality

### ISSUE THREAD

**Issue by Ebrahim1010** [DMPRoadmap/roadmap#2214]
Good day,

The reset password functionality is not working and some users are not able to log in. How do I correct this? Where do I set this?

Thank you

**Comment by briri** [comment]
Hi @Ebrahim1010, 

The password reset functionality should be working if you've correctly configured your application. Be sure that you've replaced any default values in `config/branding.yml` and the `config/initializers/devise.rb` files. 

You may also find useful information in the logs that will lead you to the underlying problem.

**Comment by Ebrahim1010** [comment]
Thank you Brian!
Which one should be enabled to get the default functionality working?
Thanks

**Comment by xsrust** [comment]
This project is using the Devise gem's recoverable for password-reset functionality.
You can read more here: https://github.com/plataformatec/devise/wiki

It's hard to say what's going wrong without seeing those files, and without knowing in what way the functionality is not working.  Unfortunately there's not one 'enable' switch but rather a working configuration.  We've already enabled this on the project side, so the last things to tweak would be environment/deployment specific settings.  You might want to have a look at your mailer settings within that file if the users are not recieving emails, or check through issues on Devise's github to see if anybody else has experienced similar behavior with their configuration options.

**Comment by norman-smith** [comment]
Hi xsrust

Thanks for this response. If we've migrated from DMPOnline and never configured the password reset functionality. What specifics do we need to do to get the reset functionality to a working state?
You mention "We've already enabled this on the project side, so the last things to tweak would be environment/deployment specific settings." so where do we tweak these things?

Regards
Norman

**Comment by xsrust** [comment]
It should work by default with the settings from the example devise.rb file.  

You will, however, need to ensure your mailers are working correctly, or your users cannot recieve the recovery email.  Maybe have a look at your logs and see what's going wrong.  I signed-up for your service thismorning and did not recieve a welcome email, so that's where I'd start troubleshooting if I were you.

It's difficult for our team to troubleshoot/support deployment-specifics like this as they are dependant on files not part of the open-source project, and can depend on your server environment as well.  Appologies we can't be more helpful

**Comment by norman-smith** [comment]
Hi Sam

Thanks for the assistance. I managed to get it working.

Regards
Norman

**Comment by xsrust** [comment]
That's great news @norman-smith!

Would you mind sharing how you solved the problem so that future contributors running into the same issue can benifit from your solution?

**Comment by norman-smith** [comment]
Hi Sam

Yes sure, I just manually specified the :smtp use in the development.rb file. There after mail was delivered as usual.

Regards
Norman
