### ISSUE TITLE
Exporting to .xml, .json, .csv, .txt, .docx and .pdf

### ISSUE THREAD

**Issue by jollopre** [DMPRoadmap/roadmap#222]
The following exporting options:
- .xml
- .json
- .csv
- .txt
- .docx
- .pdf

are no longer working after the code-refactoring. These should be fixed and consequently display data according to the exporting settings saved.

**Comment by vyruss** [comment]
I'm not convinced some of these are useful. @sjDCC how would you feel about dropping `.xml`, `.csv` and `.json` - do we know usage patterns?

**Comment by briri** [comment]
I agree with @vyruss. The json format should and will be supported by our future API. The xml and csv files don't seem to fit with the process of writing a grant. Perhaps they were being used by someone trying to generate statistics or something. We should figure out what their use cases are and determine if we will be meeting those needs by introducing the API and a dashboard.

**Comment by sjDCC** [comment]
The main ones researchers would use are pdf, docx and maybe txt. If others are superceded by API I'm happy to lose them, but perhaps double check stats first. I seem to recall csv was asked for but can't recall by whom or why.

**Comment by stephaniesimms** [comment]
I'm hesitant to drop xml and csv without first determining if these are being used. I can imagine use cases for csv, particularly if plans contain abundant tables. We can start by getting some anecdotal feedback at the RDA this week.

**Comment by jollopre** [comment]
The exporting formats docx, pdf, txt and csv with commits e72ebf3, c26ec79, e7007b9, 41d896b are now working.
 
I have disabled XML and JSON from the interface as per the conversation held here. @sjDCC and @stephaniesimms if you want me to fix/enable them, let me know.

In addition, the exporting functionality no longer raises an error for an invalid exporting format (	0a02df9).

**Comment by sjDCC** [comment]
Great stuff @jollopre! Happy to test once reviewed and deployed.

**Comment by briri** [comment]
@stephaniesimms and @sjDCC we should now be able to export in multiple formats. We removed XML and JSON as options because these would be better served through the API (since we're going to write API methods for maDMP) We can add them back in though if they are needed straight away

**Comment by stephaniesimms** [comment]
Available export formats are appropriate (csv, html, text, pdf, docx). Issues remain:

- All exported files contain both questions and answers—they should only contain answers.
- pdf export throws an error (screenshot below)
- docx export has problems, recorded in related issue #217
- html export contains weird formatting, especially for bullet lists (screenshot below).

![screen shot 2017-04-10 at 8 49 36 pm](https://cloud.githubusercontent.com/assets/12703638/24892254/f9f35b12-1e2f-11e7-9520-fd06e0f1746b.png)

![screen shot 2017-04-10 at 8 55 43 pm](https://cloud.githubusercontent.com/assets/12703638/24892274/2dcb7d48-1e30-11e7-97cd-a3c67c427e53.png)

**Comment by jollopre** [comment]
Thanks @stephaniesimms for the feedback. 

@briri the error thrown for pdf export is related to missing libraries in your system. I remember facing same problem in my local development. 

The rest of formats will be re-visited again since changes in Question model were not considered (e.g. options association rather than question_options remain in the code).

**Comment by sjDCC** [comment]
I think the odd bullet formatting is due to this being the H2020 template. The question box isn't a rich-text field so to add bullets we needed to enter html directly. Initially bullets weren't being displayed so Ray added a class for these. Now we seem to be getting two bullets.

For reference, the text in the related question boxes should be:
(I've taken this from the live DMPonline service as I can't get into edit my rights to view the H2020 on stage)

<p>Provide a summary of the data addressing the following issues:
<ul class="bullet">
<li>State the purpose of the data collection/generation</li>
<li>Explain the relation to the objectives of the project</li>
<li>Specify the types and formats of data generated/collected</li>
<li>Specify if existing data is being re-used (if any)</li>
<li>Specify the origin of the data</li>
<li>State the expected size of the data (if known)</li>
<li>Outline the data utility: to whom will it be useful</li></ul></p>

and
<p>2.1 Making data findable, including provisions for metadata:
<ul class="bullet">
<li>Outline the discoverability of data (metadata provision)</li>
<li>Outline the identifiability of data and refer to standard identification mechanism. Do you make use of persistent and unique identifiers such as Digital Object Identifiers?</li>
<li>Outline naming conventions used</li>
<li>Outline the approach towards search keyword</li>
<li>Outline the approach for clear versioning</li>
<li>Specify standards for metadata creation (if any). If there are no standards in your discipline describe what metadata will be created and how</li>
</ul>
</p>

**Comment by briri** [comment]
updated the location of the wkhtmltopdf executable on the server. should be working now

**Comment by stephaniesimms** [comment]
PDF export and other formats all working now.
