### ISSUE TITLE
Expand annotation capability for Guidance

### ISSUE THREAD

**Issue by vyruss** [DMPRoadmap/roadmap#223]
I believe that right now annotations only cover suggested answers etc. and not "pure" guidance - so it makes sense to update front-end to cover other Annotation types as coded in the data schema.

**Comment by xsrust** [comment]
I dont think we migrated the suggested_answers to annotations because we were waiting on knowing the format that would be used by substance editor.  Currently suggested/example answers are stored in this table:
`create_table "suggested_answers", force: :cascade do |t|
    t.integer  "question_id"
    t.integer  "org_id"
    t.text     "text"
    t.boolean  "is_example"
    t.datetime "created_at"
    t.datetime "updated_at"
  end`

There is also a guidance field which is stored on the question.guidance field and displayed for editing as below.  What changes would you suggest be made?

![image](https://cloud.githubusercontent.com/assets/7352616/25040927/4ef706dc-2104-11e7-8753-63418b056d70.png)

**Comment by vyruss** [comment]
I thought we'd gotten rid of the `question.guidance` column. Can we move this into rows in the `annotations` table (type `guidance`) and `suggested_answer`s similarly (as type `example answer`)?

**Comment by xsrust** [comment]
Addressed by PR: Annotations

**Comment by sjDCC** [comment]
Not entirely sure how to test this one, but I don't think it's working as planned.

Guidance by question / question annotations aren't displaying as noted in #341 

Suggested or example answers seem to have mismapped with guidance, see #372 and maybe #381

**Comment by xsrust** [comment]
I'm not sure that @vyruss has updated the server yet, but #372 should be fixed now

**Comment by dsisu** [comment]
Please note: the funder guidance from funder templates has disappeared.

**Comment by xsrust** [comment]
funder guidance not displaying fixed in https://github.com/DigitalCurationCentre/roadmap/commit/81351396a5ddda753d481ab8cad5d4372b3e7ff8

**Comment by sjDCC** [comment]
Closing out this ticket as the outstanding issues are recorded elsewhere. For reference these are:
- Guidance by question / question annotations having not mapped through #341. Sam is addressing in migration
- Example answers associated with wrong org #381 This is a data issue so needs to be solved separately. Will hold up DMPonline migration but not Tuuli

The issue @dsisu encountered that funder guidance disappeared is fixed
