### ISSUE TITLE
Supporting unis to tag existing users with dept/school/faculty affiliation

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#2235]
Since adding the ability to affiliate users with their dept/school/faculty as listed by org admins, we need to find simple ways to update existing user data. @xsrust to explore an API option with Manchester and Utrecht in the first instance

**Comment by xsrust** [comment]
I see the  API side of this as follows:
1) endpoint to export list of departments w/ ids for your org
2) endpoint to export list of users-emails for your org (because people have aliases, we will need this to figure out which version of your email they should assign the user to.)
3) Endpoint which accepts email+department_id pairs, and assigns them if the user's email was found in your organisation.

On the UI side of this, we could maybe make this either editable for admins on the user's profile, OR make the text in the users-table a dropdown that sends off an update-request when changed. (similar to marking  plans as test or users as active)

**Comment by sjDCC** [comment]
Hi @xsrust @mariapraetzellis Am just adding this to our current board as we want to be able to cover this in training on 23rd April

**Comment by sjDCC** [comment]
I'm not sure we can test this as I don't know how to use the API. Do you @mariapraetzellis

**Comment by mariapraetzellis** [comment]
I don't know how to test this via the API 

Most of our users don't use the API, so I think a UI method to do this is important. I like Sam's idea (from Sep 20, 2019) to make the text in the users-table a dropdown that sends off an update-request when changed. This would be an easy way for admins to add affiliations with out having to click into individual profiles. Sound doable @xsrust?
