### ISSUE TITLE
Support for multiple contributors

### ISSUE THREAD

**Issue by mariapraetzellis** [DMPRoadmap/roadmap#2349]
Currently the application allows for 1 PI and 1 "Data Contact Person." In order to support machine actionability of DMPs, we need to expand the number of people that can be linked to a DMP. This could be a repeatable field so that a user could add as many PIs and Data Curators as applicable. This may need a specific own tab in the application. We'd like to make the PI & data contact mandatory.

**Comment by mariapraetzellis** [comment]
@briri  to look at the Credit taxonomy- was a recommendation from a user

**Comment by briri** [comment]
UI work will be done as part of #2408

**Comment by sjDCC** [comment]
I'm happy with the separate tab and think the functionality to add contributors works well but have a couple of suggestions.
![Capture](https://user-images.githubusercontent.com/6169940/80204446-c925e200-8620-11ea-9af1-1b857ad0118e.PNG)
![new-contrib](https://user-images.githubusercontent.com/6169940/80204777-62ed8f00-8621-11ea-8870-b56b00cf84c1.PNG)

1. We should rename the tab "Collaborators" not "Contributors" as that's more even. Maria, Magdalena and I discussed this on a Product Manager call

2. We should pre-enter the plan owner as PI like we did previously on project details and allow them to amend entry. Pre-fill as much as possible from edit profile e.g. ORCID etc

3. Can we do a look-up integration with the ORCID field instead of this being a text entry?

4. Are the terms "Data Manager" "Principal Investigator" and "Project Administrator" from CRedIT Taxonomy? May be good to link out to that here or show them as indexed, controlled terms somehow? On the overview table like for RoR entry?

5. We discussed merging this with the table under "Share" and having the Collaborators tab be where users can list team members and assign plan editing roles. This may be a secondary piece of work to avoid delays now. It could fit under actions feasibly.

![credit-link](https://user-images.githubusercontent.com/6169940/80204889-98927800-8621-11ea-96bf-27e91134eb38.PNG)
![collab](https://user-images.githubusercontent.com/6169940/80204957-b8c23700-8621-11ea-97fc-8a938e24cf7f.PNG)

**Comment by briri** [comment]
Added a new ticket #2481 for these adjustments. 

See #2350 for the ORCID question. ORCID does not provide a lookup API. We can pre-populate the value for the user who is logged in. ORCID's workflow though requires that the individual in question asserts that they are associated with the plan. Dryad has solved this by sending out an email to any contributors with a link that lets them assert this information. 

For 4) above, those are not the exact terms from CRediT, we can change them to match exactly and can of course easily show the url.

**Comment by sjDCC** [comment]
Request captured in new ticket so closing out
