### ISSUE TITLE
Restrict privileges to external users 

### ISSUE THREAD

**Issue by Ebrahim1010** [DMPRoadmap/roadmap#2385]
Hi Developers,

We want to restrict access to our University[(University of Cape Town -UCT) instance](https://dmp.lib.uct.ac.za/) of the DMPonline tool to University members only. So we want to remove the generic sign up page and stay with the SSO for internal users only.

We do however want to allow co-ownership of a DMP plan to be possible with external users(people outside the University). For example if a UCT user shares a plan with an external member - we would like that external member to have access to the shared plan but not allow that external user to create plans etc. Is there a way to grant restrictive privileges to external users to only see,view, and edit shared DMPs by creating an account that only allows them these rights when trying to access a shared DMP?

**Comment by briri** [comment]
Hi @Ebrahim1010, there is not an easy configurable way to accomplish that. 

You would need to customize the code in your fork of the repository. To do that you would need to make copies of the appropriate Rails ERB templates in the `app/views/shared/` folder and place them into a `app/views/branded/` folder (you may have already done something similar for your custom home page and nav/footers). You could then just remove the non-SSO sign in options and replace the logic when the user clicks the 'Institutional login' button so that it just goes directly to your SSO.

When a user shares a plan with someone who does not have an account, it sends that person an invitation email with a link to a special 'create account' page that they use to login. To prevent those users from creating their own plans, just make copies of the `app/views/plans/index.html` and the navigation bar and hide the 'Create Plan' button for any user whose `org_id` is not your institution.

**Comment by Ebrahim1010** [comment]
@briri Thank you!
Should the copy of the index.html file should go into the branded folder as well? if not where should it go?

**Comment by briri** [comment]
Yes. You should follow the same folder structure as well, so a copy of `app/views/plans/index.html.erb` should go into `app/views/branded/plans/index.html.erb`

**Comment by sjDCC** [comment]
Hi @Ebrahim1010 I think this advice should answer your query - thanks @briri Closing out now

**Comment by Ebrahim1010** [comment]
Thank you @briri 

Okay so can we make use of the Branded folder and alter the HTML to do a check to see if the logged in user belongs to other org. if he does render specific HTML. otherwise render default HTML?
At the moment anything in Branded folder is used by default whether you are a UCT user or not
​so there is no logic in the HTML at the moment. 
​
Should we use the same HTML file and specify the requirement in the one file or have multiple files that will be rendered based on org membership. If the latter prevails how would we separate the files
​
I would imagine the branding folder was purely for changing the look and feel and not the functionality which is why it is applied to everyone.

Is it possible to have a views folder for all UCT users and a second folder for all non-UCT users where all content is rendered from either folder based on membership?

**Comment by briri** [comment]
Hi @Ebrahim1010 it would likely be easier to place that logic in the branded view file. If the differences in HTML between the 2 scenarios is significant enough I would recommend creating 2 separate partials and then have the logic in your branded view pull in the appropriate partial.
```ruby
<% if org.is_other %>
   <%= render partial "branded/plans/_other_org", locals: { user: user, etc. } %>
<% else %>
   <%= render partial "branded/plans/_uct_org", locals: { user: user, etc. } %>
<% end %>
```
