### ISSUE TITLE
User has all privileges (super admin) but cannot list plans

### ISSUE THREAD

**Issue by mirkh** [DMPRoadmap/roadmap#2428]
**Expected behaviour**
I have super admin privileges in our installation. In the admin menu, I select the Plans option and I see our plans.

**Actual behaviour for another user**
I gave super admin privileges (all checkboxes are checked) to my colleague. When she select Plans under Admin, she gets "We're sorry, but something went wrong.".

When I check the log it prints

> [roadmap]   ESC[1mESC[35mUser Load (0.9ms)ESC[0m  SELECT  `users`.* FROM `users` WHERE 1=0  ORDER BY `users`.`id` ASC LIMIT 1
[roadmap]   Rendered org_admin/plans/index.html.erb within layouts/application (9.6ms)
[roadmap] Completed 500 Internal Server Error in 40ms (ActiveRecord: 8.2ms)
[roadmap] 
ActionView::Template::Error (undefined method `name' for nil:NilClass):
    24:                 
    25:                 <tr>
    26:                   <td><%= link_to notice.name, plan_path(notice) %></td>
    27:                   <td><%= notice.owner.name(false) %></td>
    28:                   <td><%= _('Feedback requested') %></td>
    29:                   <td><%= link_to _('Complete'), feedback_complete_org_admin_plan_path(notice), 'data-toggle': 'tooltip', title: _('Notify the plan owner that I have finished providing feedback') %></td>
    30:                 </tr>
  app/views/org_admin/plans/index.html.erb:27:in `block in _app_views_org_admin_plans_index_html_erb__4071094879628423551_47409162833220'
  app/views/org_admin/plans/index.html.erb:22:in `_app_views_org_admin_plans_index_html_erb__4071094879628423551_47409162833220'

Does anyone have an idea of how to test this further to find what is wrong?

**Comment by briri** [comment]
Hi @mirkh 

From the error message above, it's failing on this line: 
https://github.com/DMPRoadmap/roadmap/blob/2aec36cfff386e79882584ce541d0fc46f452db4/app/views/org_admin/plans/index.html.erb#L27

That would happen in a scenario where someone requested feedback for their plan and then removed/deleted the plan (plans are not actually deleted if they have been shared).

You will need to manually determine which plan is causing the issue and change it's `feedback_requested` column in the `plans` table to a value of `0`.

If you're unable to determine which plan is causing the issue you may be able to get around it by adding an ampersand `&` character after the `owner` portion of that line so that it looks like this: `notice.owner&.name(false)`

We will add this as a bug. You should do one of the above fixes though for now.

**Comment by magdalenadrafiova** [comment]
I am not sure whether this is for us to test (?)

**Comment by sjDCC** [comment]
No, this is a local installation and we have advised how to fix. Closing out
