### ISSUE TITLE
Move all constants out of the code and into the new initializer

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#2467]
**Constants:**
Remove any hard coded values into the new `config/initializers/dmproadmap.rb` file.

Use the `config.[category].[variable] = "[value]"` syntax. Be sure to add a comment explaining what the variable is used for.

Then update the place where the variable was removed from with `Rails.configuration.x.[category].[variable]`

If the variable is used often, consider adding a helper method to the `ApplicationService`. For example `Rails.configuration.x.application.name` is used all over the codebase so it was simplified to `ApplicationService.application_name`

**Credentials:**
Go through any config and config/initializer files we have that are samples and move their sensitive values into the new `config/credentials.yml.enc` file.

Also look into switching references to these values over to ENV variables so that installations can either use the `config/credentials.yml.enc` or environment variables.

Here are some articles to read before starting that work. I would suggest we err towards the Rails6 approach:
https://medium.com/cedarcode/rails-5-2-credentials-9b3324851336
https://blog.capsens.eu/rails-5-2-imperfect-credentials-4ef03934aea4
https://blog.saeloun.com/2019/10/10/rails-6-adds-support-for-multi-environment-credentials.html

**Comment by briri** [comment]
need to move the new Recaptcha flag and Google Analytics tracker stuff into the new `config/initializers/dmproadmap.rb`

**Comment by briri** [comment]
related to #2036. The Dragonfly initializer also has a secret that should be moved to the credentials file

**Comment by raycarrick-ed** [comment]
There is a sample config/credentials.yml.enc file which contains brief instructions on how to set it up. In the current set up the credentials are in the one file with a single RAILS_MASTER_KEY env variable. When we move to Rails 6 this will get split out into environments.
Because the credentials are now encrypted the devise.rb. and recaptcha.rb files can now be standard so they don't need .example version and they can be safely checked in.
There are a couple of other constants pulled out and set in dmproadmap.rb
