### ISSUE TITLE
rake task data_cleanup:find_known_invalidations fails when validating OrgIdentifier 

### ISSUE THREAD

**Issue by nicolasfranck** [DMPRoadmap/roadmap#2591]
Please complete the following fields as applicable:

**Expected behaviour:**

**Actual behaviour:**

```
[..]
Checking OrgIdentifier records
      0 records that are not unique per (identifier_scheme_id, org_id)
    rake aborted!
    ActiveRecord::StatementInvalid: Mysql2::Error: Unknown column 'org_identifiers.identifier_id' in 'on clause': SELECT COUNT(*) FROM `org_identifiers` LEFT OUTER JOIN identifiers ON identifiers.id = org_identifiers.identifier_id WHERE `identifiers`.`id` IS NULL
```

Inspecting the task, it looks like it fails in the function check_presence.
I think because attribute identifier of OrgIdentifier is an exception?

**Steps to reproduce:**

**branch**: master
**Ruby version**: 2.4

```
bundle exec rake data_cleanup:find_known_invalidations
```

**Comment by nicolasfranck** [comment]
the function `check_presence` assumes that every validation with option `presence` implicates an external relation, not?

At least: the attribute `identifier` of model `OrgIdentifier` is not a relation.

**Comment by briri** [comment]
Looks like this is due to the introduction of the `identifiers` table in v2.2.0 and logic in this task that attempts to determine if the the column is an fkey: https://github.com/DMPRoadmap/roadmap/blob/58f6b7692c29e2d1af4a189ae244a55a8557e495/lib/tasks/data_cleanup.rake#L140

@nicolasfranck are you in the process of upgrading from an older v1.x version of DMPRoadmap? If so, it is imperative that you run through the various upgrades individually due to database table changes and the occasional need to run data transformations like this one.

**Comment by nicolasfranck** [comment]
* I've done the migration from DMPonline_v4 to v1.0.0, as described here https://github.com/DMPRoadmap/roadmap/wiki/Upgrading-From-DMPOnline_v4.

* Then I started part one of migration from v1.0.0 by switching to the master branch (https://github.com/DMPRoadmap/roadmap/wiki/Upgrading-from-v1.x-to-2.0.0#part-one)

* run `rake db:migrate`

but the rake task `upgrade:v2_0_0_part_1` failed due to a subtask `data_cleanup:find_known_invalidations`

I do not see anything in the migration files that would introduce a field like `org_identifiers.identifier_id`

**Comment by nicolasfranck** [comment]
Or should I have run this task BEFORE any db:migrate?

**Comment by xsrust** [comment]
Hi @nicolasfranck 
Our reccomended method of upgrading the tool is to go through each minor-release sequentially:
https://github.com/DMPRoadmap/roadmap/releases

For big changes, such as the migrations to v1.0.0 and v2.0.0,  we additionally added those wiki-pages you've linked as there were extra or non-standard steps involved in the upgrade.

I think the first issue you'll hit is with jumping straight from v1.0.0 to v2.0.0.  You'll actually first want to pull the tagged-releases in between these two versions and follow-along with the upgrade notes on each.

Next, when you've pulled the master branch to start the upgrade to v2.0.0, you may have pulled the current Master, rather than the tagged v2.0.0 release.  This would explain the presence of the `org_identifiers` model. Additionally, the `upgrade:v2_0_0_part_1` task will run the `rake db:migrate` for you, so there's no need to invoke this yourself on that step.

I've actually recently helped another organisation through this migration recently and written up a [wiki-page](https://github.com/portagenetwork/roadmap/wiki/Migration-to-DMProadmap) along with some issues to walk them through the process.  Please note that I've also written a docker-compose wrapper for the application to ease that upgrade process, so some of the instructions on the wiki/issues pages are specific to that rather than the Roadmap application

**Comment by nicolasfranck** [comment]
@xsrust You're right, I should have followed the release flow. I just got there from the wiki page. Thanks for your help. Now it works ;-)
