### ISSUE TITLE
Allow org admins to filter machine-actionable questions

### ISSUE THREAD

**Issue by mariapraetzellis** [DMPRoadmap/roadmap#2594]
For maDMP questions that are pulling from external controlled vocabularies or identifiers, admins should be able to filter the option set that displays for users. 

For example, an admin should be able to specify which repositories are displayed as options in a question or which licences are listed.  Also, in the case of the  RDA metadata standards directory, an org admin could define which metadata standards are applicable for a specific discipline or directorate.  

This should be configurable at the organization and school/department level.

**Comment by briri** [comment]
This would be difficult to accomplish since we do not control the list of possible options. If the 3rd party makes changes we would have no way of detecting if these refinements were still applicable or if the admin should make further refinements

If the admin wants a refined set of options it might be better to just have them use a select box and manually enter the options they want their users to pick from.

**Comment by briri** [comment]
It looks like the re3data repository records contain supported metadata standards and license types. This could conflict or negate the specifications defined by the admin. They could also be used to help refine the repository search (based on metadata standards and licenses chosen by the admin) and it could also be used to refine the options available for the license and metadata standard if the repository is selected first.
