### ISSUE TITLE
Add UI components that allow user to acquire a DOI

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#2601]
We need to update the Write plan section of the site to allow a user to publish their DMP (acquire a DOI). 

See #2351 for discussion of the UI options. 

@mariapraetzellis @magdalenadrafiova and @pherterich we need to answer the following questions for this:
- Should we rename the 'Downloads' tab for this to 'Finalize/Publish' and integrate the existing Downloads functionality with a new 'Publish' button? If not how should we implement it?
- When should a user be allowed to 'publish'? We have discussed some workflows where this should only happen after a review period. We need to define the workflow(s)
- Do we allow user's who do not belong to a "managed" Org (no Org Admin defined) to publish their DMP?
- Where do we display the DOI? 
- Where should the DOI resolve to, what is the landing page? Who is the primary audience? Right now, to view a plan the user must be logged in (unless the plan is public) but I think we want something that does not require login here. The various options I can think of are:
  - the new RDA Common Standard JSON output
  - the PDF of the DMP
  - a new page that is similar to our normal DMP page
- We need to define policies around which elements of the plan are visible on the landing page under different circumstances (e.g DMP is set to organizationally visible but the page is being accessed by a user who is not logged in).
- Should we include the DOI on the downloaded versions of the DMP (PDF, DOCX, etc.)? If so where/how should it be displayed?

**Comment by mariapraetzellis** [comment]
@briri The DOI should resolve to the RDA Common Standard JSON output for implementations of this w/o the hub

**Comment by mariapraetzellis** [comment]
To be discussed with @briri @pherterich @magdalenadrafiova but here are my thoughts on the UI components of the DOI  feature.

**_Should we rename the 'Downloads' tab for this to 'Finalize/Publish' and integrate the existing Downloads functionality with a new 'Publish' button? If not how should we implement it?_**

I propose we move the “Share” tab to the end and rename it “Publish”. (Sarah described our prior conversations on this topic in a comment on https://github.com/DMPRoadmap/roadmap/issues/2351)

![image](https://user-images.githubusercontent.com/27511575/88110784-a0e74a00-cb61-11ea-9d59-e299fadb8be3.png)

**_When should a user be allowed to 'publish'? We have discussed some workflows where this should only happen after a review period. We need to define the workflow(s)_**

In order to mint a DOI the DMP should be completed with the following:

- ORCIDs
- ROR
- Funder 
- Some text included for at least 50% of all questions within a DMP

At this point we don’t need to incorporate a review period. We can present this as an item to get community feedback on going forward. 

**_Do we allow user's who do not belong to a "managed" Org (no Org Admin defined) to publish their DMP?_**

For now only users from managed orgs should be allowed to publish their DMP. We can always expand to unmanaged orgs after we roll it out.

**_Where do we display the DOI?_**

- Downloaded versions of DMP should include the DOI on the coversheet
- On the Project Details page 
- Can we also display DOIs on the Plans listing page? 
- On the My Dashboard listing table
- Would be good to include the number of DOIs as a metric on Usage Statistics (can add this later)

**_Where should the DOI resolve to, what is the landing page?_** Who is the primary audience? Right now, to view a plan the user must be logged in (unless the plan is public) but I think we want something that does not require login here. The various options I can think of are:
the new RDA Common Standard JSON output
the PDF of the DMP
a new page that is similar to our normal DMP page

The DOI should resolve to RDA Common Standard JSON output

**_We need to define policies around which elements of the plan are visible on the landing page under different circumstances (e.g DMP is set to organizationally visible but the page is being accessed by a user who is not logged in)._**

We are going to allow org admins to make visibility determinations. This is being tracked in https://github.com/CDLUC3/dmphub/issues/10

**_Should we include the DOI on the downloaded versions of the DMP (PDF, DOCX, etc.)? If so where/how should it be displayed?_**

Downloaded versions of DMP should include the DOI on the coversheet

**Comment by mariapraetzellis** [comment]
Need to define how we're recording versioning
