### ISSUE TITLE
rake task upgrade:migrate_other_organisation_to_org fails with LocalJumpError when Org "is_other" does not exist

### ISSUE THREAD

**Issue by nicolasfranck** [DMPRoadmap/roadmap#2612]
Please complete the following fields as applicable:

**Expected behaviour:**

**Actual behaviour:**

**Steps to reproduce:**

* make sure there is no `Org` with the flag `is_other` set to `true` (should that even happen?)
* `git checkout tags/v2.2.0`
* advance migration steps up until rake task `v2_2_0_part2``
* subtask `upgrade:migrate_other_organisation_to_org` fails with error:

```
[install@localhost roadmap]$ bundle exec rake upgrade:v2_2_0_part2
"Upgrading to v2.2.0 (part 2) ... A summary report will be generated when complete"
"------------------------------------------------------------------------"
"No is_other Org defined, so no orgs need to be created!"
rake aborted!
LocalJumpError: unexpected return
/home/install/roadmap/lib/tasks/upgrade.rake:992:in `block (2 levels) in <top (required)>'
/home/install/roadmap/lib/tasks/upgrade.rake:18:in `block (2 levels) in <top (required)>'
/home/install/roadmap/vendor/bundle/ruby/2.4.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.4.10/bin/bundle:23:in `load'
/usr/local/rvm/gems/ruby-2.4.10/bin/bundle:23:in `<main>'
/usr/local/rvm/gems/ruby-2.4.10/bin/ruby_executable_hooks:24:in `eval'
/usr/local/rvm/gems/ruby-2.4.10/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => upgrade:v2_2_0_part2
(See full trace by running task with --trace)
```

Apparently using `return` from a subtask generates this error. I tried `abort` but that permanently exists the script ;-)

**Comment by briri** [comment]
Thanks for reporting this @nicolasfranck. 

The 'is_other' Org was the default organization that all users who clicked on the old 'other organization' (my Org doesn't appear in the list) became attached to. It would then store whatever they typed into the text field in the `users.other_organization` text field. This wasn't a particularly useful way to store that info so we updated the code in v2.2 to just create an Org record from the value they type or the selection they've made from the typeahead list. Since you're coming from the old dmpOnline_v4 code I'm guessing that the data structures were different.

We will patch this `return` issue. If you haven't already, you can comment out that `return` line and then change the `users = User.where(org: is_other)` line to `users = is_other.present? ? User.where(org: is_other) : []` and that should get you past that step of the upgrade process.

**Comment by briri** [comment]
you'll also need to add an `if is_other.present?` guard to the 'Processing x records' line below that as well

**Comment by nicolasfranck** [comment]
rake task `upgrade:results_2_2_0_part2` may also fail in this case
