### ISSUE TITLE
User accounts table display goes rogue when displaying shibboleth identifier

### ISSUE THREAD

**Issue by pherterich** [DMPRoadmap/roadmap#2647]
**Expected behaviour:**
I'm not entirely sure, none of the previous versions seem to display the shibboleth identifier in that table but I guess the table should still align with the rest of the design.

**Actual behaviour:**
The user accounts table layout doesn't wrap properly when a shibboleth identifier is displayed in the "identifiers" column.
![dmponline table wrap](https://user-images.githubusercontent.com/8457675/90662628-7fe94600-e240-11ea-80d2-9fdfc5426cd1.png)

**Steps to reproduce:**
E.g. go to https://dmponline-test.dcc.ac.uk/org/admin/users/admin_index and filter by "show only admins" or sort by Last activity.

**Comment by xsrust** [comment]
replace Shibb Identifier in table w/ a presence message
(retain display of identifier on user-profile)

**Comment by mariapraetzellis** [comment]
Let's show the logs for Shibb and ORCid. The user can click through to view the actual id.

**Comment by raycarrick-ed** [comment]
Fixed in:
https://github.com/DMPRoadmap/roadmap/tree/issue_2647
in the table it will now just have the names of any identifiers present
when you click through to the user edit page it will display those identifiers
the identifiers are just displayed as I don't think it makes sense to allow them to be edited. The shibb ids can still be long so depending how people find it we may need to revisit their display. But this should do for now.

**Comment by mariapraetzellis** [comment]
Looks good now.
