### ISSUE TITLE
20161122152339_new_plan_template_structure.rb removes answers

### ISSUE THREAD

**Issue by nicolasfranck** [DMPRoadmap/roadmap#2744]
Please complete the following fields as applicable:

**What version of the DMPRoadmap code are you running? (e.g. v2.2.0)**

branch dmponline4_upgrade_step2

**Expected behaviour:**

Keep as many `answers` in new table `new_answers`

**Actual behaviour:**

In my installation there are 119011 records in table `answers`,
but only 77736 in table `new_answers`.

**Steps to reproduce:**

* fill database with data from a DMPonline_v4 instance
* `git checkout dmponline4_upgrade_step2`
* `bundle exec rake db:migrate`

I see [here](https://github.com/DMPRoadmap/roadmap/blob/master/db/migrate/20161122152339_new_plan_template_structure.rb#L255) that an old answer is only copied to a NewAnswer in order to attach notes (which were comments) to it. Not?

**Comment by xsrust** [comment]
Hi @nicolasfranck 

That behavior is intentional.  in dmponline4, multiple answers were stored for each question, but only the latest was accessible via the frontend.  When we re-modeled the DB for DMPRoadmap, we decided that there would be exactly one `answer` for each combination of `question` and `plan`.  This meant that the final set of answers may be smaller than your original set.


I've pulled out the relevant lines from your link:
```
old_ans = Answer.where(question_id: new_question.question_id, plan_id: old_plan.id).order("created_at DESC").first
comments = Comment.where(question_id: new_question.question_id, plan_id: old_plan.id)
unless old_ans.nil? && comments.length < 1
    new_ans = initNewAnswer(old_ans, new_plan, new_question)
    new_ans.save!
end
```
Effectively we take `old_ans` the most recently created answer, and create a `new_ans` if this is present.
Also part of the above DB remodel was attaching `Notes`(formerly `comments` as you surmise) directly to an answer, rather than to a combination of `plan` and `question`.  Because of this change, we also need to generate a (blank) answer to attach the `Notes` to.

Let me know if that makes sense:)

**Comment by nicolasfranck** [comment]
Right, I remember fixing that in my instance of dmponline..

If I run a group-query like this

```
select plan_id,question_id,count(*) from answers group by plan_id,question_id
```

it returns 77843 records. so a difference of 107 records with the expected 77736,
but those can probably be explained differently.

Thanks for your response!

**Comment by nicolasfranck** [comment]
That double negation `unless old_ans.nil? && comments.length < 1` is a bit hard to understand, so I was curious why there were any answers left after that run ;-)
