### ISSUE TITLE
VersionHelper does not work outside of git

### ISSUE THREAD

**Issue by nicolasfranck** [DMPRoadmap/roadmap#2782]
Please complete the following fields as applicable:

**What version of the DMPRoadmap code are you running? (e.g. v2.2.0)**

3.0.1

**Expected behaviour:**

**Actual behaviour:**

When you use this application,
without the full git repository (`.git`),
then the startup crashes:

```
app/helpers/version_helper.rb:7:in `<module:VersionHelper>': undefined method `strip' for nil:NilClass (NoMethodError)
```

Reason: https://github.com/DMPRoadmap/roadmap/blob/master/app/helpers/version_helper.rb#L7

**Steps to reproduce:**

* remove the git folder
* `bin/rails server`

Why I want to do this: I want to prepackage this application (including ruby dependencies with bundler)
into an rpm. The git repository does not belong in that rpm, so that
is not included as well. Is this version helper even used?
What about prepackaged releases?

**Comment by briri** [comment]
To my knowledge that version_helper file is not used. @raycarrick-ed do you use this to display the current version somewhere in your deployments? 

The `.git` directory contains all of our automated testing, rubocop checks, etc. and cannot be removed.

Because this is a shared code base we have been very careful to keep changes/enhancements related to specific deployment strategies out of the code. If you have not already, I would recommend that you remove the directory from your own fork.

**Comment by nicolasfranck** [comment]
@briri I merely meant that the application cannot start out of the context of a git repository. Of course, one should not delete the git repository ;-)

**Comment by raycarrick-ed** [comment]
From a quick grep we don't seem to use VersionHelper anywhere.

**Comment by nicolasfranck** [comment]
crap, it is used here, but it is hard to track: https://github.com/DMPRoadmap/roadmap/blob/master/app/views/layouts/application.html.erb#L4

**Comment by briri** [comment]
I have my own approach to this for the DMPTool. We use Capistrano for deployment and I have it run the git command to write the version/tag info to a file which is then pulled in and displayed on my branded footer (we have a branded version of the `app/layouts/application.html.erb` which is why we've probably not discovered the issue).

Here is how we handle it:
```ruby
# config/deploy.rb
# Gets the current Git tag and revision
set :version_number, `git describe --tags`

namespace :deploy do
  after :deploy, "git:version"
end

namespace :git do
  desc "Add the version file so that we can display the git version in the footer"
  task :version do
    on roles(:app), wait: 1 do
      execute "touch #{release_path}/.version"
      execute "echo '#{fetch :version_number}' >> #{release_path}/.version"
    end
  end
end

# config/initializers/dmptool_version.rb
# frozen_string_literal: true
# The capistrano deploy writes out a `.version` file into the root dir
# If it exists, add it to the configuration so that it will be available
# on the `views/branded/layout/_footer.html.erb`
if File.exists?(".version")
  Rails.configuration.x.dmptool.version = File.read(".version")
end

# app/views/layouts/_footer.html.erb
<p>
  <!-- Copyright info -->
  
  <% version = Rails.configuration.x.dmptool.version %>
  <% if version.present? %>
    <br><br>
  <%= _("Version: %{number}") % { number: version } %>
<% end %>
```

And it results in this:
<img width="550" alt="Screen Shot 2021-01-22 at 9 31 54 AM" src="https://user-images.githubusercontent.com/1204467/105886097-deb8a580-5fbe-11eb-92ca-2fd5db001e07.png">

**Comment by briri** [comment]
If you have a chance, can you submit a PR to remove that line from the layout file and also the version_helper file?
