### ISSUE TITLE
ExportablePlan#record_plan_export fails silently

### ISSUE THREAD

**Issue by nicolasfranck** [DMPRoadmap/roadmap#2859]
Please complete the following fields as applicable:

**What version of the DMPRoadmap code are you running? (e.g. v2.2.0)**

`v3.0.2`

**Expected behaviour:**

`ExportablePlan#record_plan_export` should create a new record
in table `exported_plans`

**Actual behaviour:**

Validation fails silently due to missing attribute `user_id`,
which is required (`belongs_to` in Rails 5.2 validates its presence
by default unless `optional: true` is set)

**Steps to reproduce:**

* go to [line](https://github.com/DMPRoadmap/roadmap/blob/master/app/models/concerns/exportable_plan.rb#L209) and replace `save` by `save!`
* now download any plan as pdf

No idea how to fix this. Models do not have access to things like `current_user`,
and this happens so deep in the code chain.. Is it required to store this attribute?

**Comment by briri** [comment]
I can confirm that the `exported_plans` table has no new records since we upgraded to the Rails 5.2 version.

I've never seen any use for this table. There is no UI component that displays any metrics on downloads. @martaribeiro or @raycarrick-ed do either of you use this table or recall why it was there? I think it was carried over from the old dmponline v4 codebase.

@nicolasfranck I would recommend using the `optional: true` here if the information is of interest, otherwise maybe just comment out the call to that method.

**Comment by nicolasfranck** [comment]
ExportedPlan is an old component that dates back to DMPonline_v4,
but there the results were never used. I thought that the results
were meant to be shown on the page "Usage"?

**Comment by raycarrick-ed** [comment]
I'm not aware of any current use of it. So I suspect it's a historical leftover.

**Comment by briri** [comment]
Ok. I think we should just remove the table entirely then. This should include:
- [ ] migration to drop the `exported_plans` table
- [ ] removal of the ExportedPlan model
- [ ] removal of the ExportablePlan model concern
- [ ] removal of `include ExportablePlan` line from the Plan model
- [ ] removal of any related RSpec tests
- [ ] a scan of the codebase to search for any other references to those objects

**Comment by briri** [comment]
Discovered (from a user) that these records are used to generate usage statistics, so going to patch so that it begins recording again.
Unfortunately there will be a gap in the statistics.
