### ISSUE TITLE
Export bug

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#295]
When you check the settings to export plan details, these selections aren't being exported consistently across the different formats. 
![capture](https://cloud.githubusercontent.com/assets/6169940/25809616/71d8823e-3405-11e7-9bc6-343aac67452d.PNG)

The choices made are recognised and exported correctly for docx and html, but not in PDF, CSV or text. No plan details export in PDF and CSV for trials of various funder templates, while text seems to export a random mix (possibly an old list?)

This is a bug, but lower priority.

**Comment by stephaniesimms** [comment]
@sjDCC Did they ever work consistently? I ask because they aren't consistent with the plan details fields when you're writing a plan either (screenshot below). UX is working on this for Export page.

![screen shot 2017-05-08 at 11 56 05 am](https://cloud.githubusercontent.com/assets/12703638/25820248/7bfeaca4-33e5-11e7-8153-fa7dccea32b5.png)

**Comment by jollopre** [comment]
Going to amend that. I though that we still wanted to display the section heading (at least that what the code has currently).

**Comment by jollopre** [comment]
Exporting plans now prevents showing section heading (if the section does not have any question selected).

**Comment by sjDCC** [comment]
Working fine now. Closing out
