### ISSUE TITLE
Translation Language Request: Turkish (TR_tr).

### ISSUE THREAD

**Issue by hbayindir** [DMPRoadmap/roadmap#2952]
Hello,

We're currently installing DMPRoadmap in our institution and planning to use it for managing our data management plans. To be able to use it with ease, we're planning to translate the whole code base to Turkish. We'll shortly start translations of English `.po` files in the repository. Currently we're planning to use Transifex, since there'll be a team of translators. The translations will be validated by domain experts before merging.

We've already forked the repository (which is [here](https://github.com/TRUBA-HPC/dmp-roadmap)) and following your guidelines for PR compatibility.

I just wanted to learn how to integrate our efforts together and integrate these language files to upstream, so more users can benefit from these translations.

Any help and guidance is greatly appreciated,

Best regards

**Comment by briri** [comment]
Hi @hbayindir and welcome to the DMPRoadmap community!

We are now managing translations through the https://translation.io/ site. It provides a much nicer interface for interacting with the translations files in the config directory. You can find some instructions on how to use the site here: https://github.com/CDLUC3/dmptool/wiki/translations

We can add the translators you identify to this site so that they can begin translating. To do that, we will need their emails. I will contact you via email so that we can get them setup.

We typically pull down all of the latest translations from Translation.io when we generate new releases of DMPRoadmap, so the work they do will be available to everyone using the codebase. 👍🏻 

If you are hosting your own instance of the code, you will want to do the following:
- Add `tr-TR` to the `languages` table `INSERT INTO languages (name, abbreviation, default_language) VALUES ('Türk', 'tr-TR', 0);` (Note that if you want that to be your primary language you should set `default_language` to `1` in the query.
- Make sure you are on the latest version v3.0.2 or in line with the master branch
- Then wait for the translations to be completed within Translation.io and then pull down the next release once it has been created. 

If you want to test things out before all of the work is complete on the Translation.io site, you can pull down the [PR to add tr-TR to the codebase](#2953) manually change entries within the `config/locale/tr_TR/app.po` file and then refresh the page to see if the translated text appears correctly. I went ahead and translated "My Dashboard" (the <h1> title of the page after you login) and "Language" (the label for the menu to change your language) via Google translate to verify that the new langage files were working.

If you want to restrict your instance to just use the tr-TR language you can simply remove the other languages from the `languages` table in the DB. This should make the "Language" menu disappear from the menu.

**Comment by hbayindir** [comment]
> @hbayindir we will be releasing v3.0.3 later today which contains the latest translations your team have provided. You'll need to make sure you have added 'tr-TR' ton your installation's `languages` table in order for it to appear as an option.

Thanks for the heads up @briri! I will do the migration ASAP and enable the translations.
