### ISSUE TITLE
Newly created organization cannot be found in funders list while creating new plan.

### ISSUE THREAD

**Issue by hbayindir** [DMPRoadmap/roadmap#3010]
Please complete the following fields as applicable:

**What version of the DMPRoadmap code are you running? (e.g. v2.2.0)**

Forked from commit bba8a39566f3497a30db95d82d516e3c4cd86090.

**Expected behaviour:**

When creating a new plan, a new organization, marked as a funder shall be listed under funders.

**Actual behaviour:**

When creating a new plan, a new organization, marked as a funder *is not* listed under funders.

**Steps to reproduce:**

1. Login as a super admin.
2. Go to Admin &rarr; Organizations
3. Click `Create Organization`.
4. Fill all mandatory details.
5. Click `Funder` to check the selection.
6. Click `Save`.
7. Funder will be unchecked. Click `Funder` to check the selection, click `Save`.
8. Go to `Create Plans` from top bar.
9. Start writing your new organization to Funder field.
10. The newly created organization doesn't show up.

**More information:**

- Institution indexer is working. If an organization is marked as an organization, it appears in relevant places.
- Relevant changes are reflected to DB side. Marking an organization as a funder makes relevant changes in `orgs.org_type` column.
- Unable to generate/find and relevant logs under logs or browser JS console.

**Comment by briri** [comment]
Hi @hbayindir,

You're probably not seeing the new funder listed because they do not have a published template. See https://github.com/DMPRoadmap/roadmap/blob/5cd2a36e457e8532c6f8228b94fc4d284e947645/app/controllers/plans_controller.rb#L175

This is a limitation that was added when we had a single use case for users creating DMPs. Users used to only create DMPs as part of a grant proposal (when required by the funding organization), each of the major funding organizations had a template with questions tailored towards their grant proposal.

Since then we recognize that there are other use cases and scenarios where a funder does not have a template. See issue #2337 which outlines some ideas about changing this page to more accurately reflect current needs.

**Comment by hbayindir** [comment]
Hi @briri,

Thanks for the clarification. From my understanding, we already plan to have templates under the funder(s) in our instance, so there'll be no problems. I think my confusion rooted from not having (or me missing) the relevant warnings under organization's edit page.

Again, thanks a lot, and I'll take a look at the issue you referenced and contribute there, if possible.

I'm closing this issue since my report seems invalid and requires no further discussion.
