### ISSUE TITLE
Project plan's page - 'download' option to have project sheet tickbox ticked by default 

### ISSUE THREAD

**Issue by magdalenadrafiova** [DMPRoadmap/roadmap#3063]
Currently in DMPonline and in DMPTool, on the project's detail page when the user go to download the first option is not ticked by default. It has been suggested that it would be good if the project cover sheet was ticket by default, could we implement? @raycarrick @briri or was there some logic behind why this was not ticked by default?
<img width="1427" alt="Screenshot 2021-11-12 at 15 12 27" src="https://user-images.githubusercontent.com/47178106/141489340-a780fa8f-a29c-4aac-bba7-341c0600db72.png">
<img width="1415" alt="Screenshot 2021-11-12 at 15 12 06" src="https://user-images.githubusercontent.com/47178106/141489355-1b4f1ddb-5393-43a0-9fa0-44899f33b483.png">

**Comment by raycarrick-ed** [comment]
From memory, I think it was requested that the first box not be ticked. But it's trivial to change.

**Comment by mariapraetzellis** [comment]
We decided that DMPTool will not implement this (due to the 2page limit) but it can go via DMPonline.

Rather than having a separate code for this, we decided to take the approach to have a setting in the configuration of the instances that allows the implementation to determine if this will be ticked by default.

**Comment by johnpinto1** [comment]
I have a PR for this.
