### ISSUE TITLE
Email address formatting/length gives error for new account

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#317]
I received an error message (screenshot below) when creating a new account w/my bu.edu address. The system allowed me to create an account but it should not display the error message. @vyruss suspects this is happening because the uni domain is only 2 letters.

![screen shot 2017-05-12 at 9 01 59 am](https://cloud.githubusercontent.com/assets/12703638/26008249/cf0aefa0-36f8-11e7-8f3c-b91ba871da54.png)

**Comment by jollopre** [comment]
This happens because the dialog message is shown when the regex (e.g. https://github.com/DMPRoadmap/roadmap/blob/development/lib/assets/javascripts/application.js#L203) fails. 
You have been able to create the account because there is nothing preventing signing up if any field is invalid.

Should we use the default HTML5 email validation rather than the customised regex stated at application.js?

**Comment by vyruss** [comment]
@jollopre I think the HTML5 validation is not implemented consistently across the popular browsers. I'd say change the filter function `validateEmail` in `application.js` to allow a minimum of 1 character for local-part and 1 for domain-part (excluding extension) - it's currently at 3 characters for each. We could also validate against this function before Submit I guess?

**Comment by briri** [comment]
Make sure that the regex in `app/validators/email_validator.rb` matches your changes to the JS file

**Comment by sjDCC** [comment]
Working fine. Closing out
