### ISSUE TITLE
Can't create an account if email already known by system

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#322]
Sometime plans are shared and the invitee doesn't follow the link. If so, there's a stem account that lies unvalidated in the system. If the holder of that invited email address subsequently tries to create an account they get ugly error messages. See #290 

At minimum we need an error message to say their email address is already taken, but if they don't have the email invite to follow the relevant link they're stuck, so a better workflow / solution is needed. Perhaps redirect them to a page to set a password for the unvalidated account as would be done when they follow to invite?

**Comment by xsrust** [comment]
Perhaps we should redirect them via the change password workflow instead of set password?  The account has another person's plan shared with it so it's perhaps a little lax to just let them set a password without any confirmation that they own that email address.  (Just took a Computer security exam thismorning so perhaps paranoid)

**Comment by sjDCC** [comment]
@vyruss was just talking about this on slack and said that they need the token so can't redirect to set / change password like I suggested. May need to delete stem account

**Comment by vyruss** [comment]
Fixed for now by automatically deleting stem account when they try to sign up and letting them sign up normally. When a better solution comes along, we can apply that.

**Comment by sjDCC** [comment]
This works now. Closing out
