### ISSUE TITLE
[FEATURE]: Allow admins to delete a template

### ISSUE THREAD

**Issue by Danny-dK** [DMPRoadmap/roadmap#3305]
Currently, templates created by admins cannot be deleted. Only current options are:
![image](https://user-images.githubusercontent.com/45395070/230005381-dba60b71-d0ee-45a3-ac65-acfdac980c12.png)

It would be beneficial to have the option to delete unpublished templates.

**Comment by briri** [comment]
Templates can only be deleted if no plans were created from them because it would leave orphaned records in the database

**Comment by Danny-dK** [comment]
@briri  What if the DMPs on which the unpublished template (it is not a published template) were based on are all deleted from the webportal. There still is no option to delete the unpublished template.  I was the only one that created that template and was the only one to create 2 dmps based on that template.

**Comment by briri** [comment]
Here is the logic that determines whether or not a template is 'removable'.
https://github.com/DMPRoadmap/roadmap/blob/9ead17b2979d5624e57f6ce15174f7535094a080/app/models/template.rb#L366

If any version of a the template has plans, then it cannot be removed/deleted because removing it would require that all prior versions also be removed. If what you want to do is remove the currently published version of a template, you can just unpublished it which ensures that it will then not be available when a researcher creates a new plan. (Note that un-publishing does not re-publish a prior version)

**Comment by briri** [comment]
Hi @Danny-dK you'd have to look in the DB not the UI to get a clear picture of what records would be orphaned by the deletion of the template. The templates table is complex. Each template has a `family_id` which ties different versions of a template together as well as a `customization_of` field for any templates that are customizations of the template (customizations are applicable only to funder templates). If there are any other templates or plans associated with any version or customization of the template then it cannot be deleted. 

If you truly feel that it is an error, you can bypass the UI and application logic and simply delete the record manually in the DB (which I DO NOT recommend as you would need to ensure that you've deleted the appropriate records from about 1/2 of the database's tables). You will need to delete any associates, phases, sections, questions, question_options, conditional questions, notes, plans, answers, themes_in_questions, etc. for each version of your template.

Please feel free to review the code in the app/models directory to get a clearer picture of all the relationships
