### ISSUE TITLE
Guidance by question / question annotations

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#341]
Guidance by question (redefined as question annotations) does not seem to have mapped across correctly.

The University of Glasgow has specific guidance for an MRC question. You can see this highlighted in the screengrab of the live site, but it is not showing on test.
![guidance-by-question-live](https://cloud.githubusercontent.com/assets/6169940/26287938/31639982-3e7d-11e7-9c94-104e7833e811.PNG)
![guidance-by-question-test](https://cloud.githubusercontent.com/assets/6169940/26287939/3166904c-3e7d-11e7-9008-7c73910ffaaa.PNG)

This second screengrab also shows another issue. An example answer for St Andrew's is displaying for me as a Glasgow user... I couldn't get example answers to show before (see issue #334) so this needs some investigation to ascertain when they display and to make sure they show to users with the right affiliation or guidance selections.

Hmm, just realised the default value (i.e. the table displaying in the answer box on screengrab 1) doesn't appear to have transferred through either. I think this is the only question with a default value set, but perhaps worth a SQL query to check if others are missing.

**Comment by sjDCC** [comment]
These issues haven't been fixed. The screengrab shows 3 problems:
1. the guidance by question provided by Glasgow Uni for MRC q7 isn't displaying
2. A suggested answer from St Andrew's is displaying
3. Two additional sections added by Sheffield Hallam and another uni are showing
![guidance-by-question](https://cloud.githubusercontent.com/assets/6169940/26532681/a41e5d54-43ff-11e7-8a0b-27d0c0a4c136.PNG)

All I should see if the Glasgow customisations on the MRC template

**Comment by xsrust** [comment]
This is due to the migration not taking into account guidance by question when deciding which templates have customizations.

I will add this into the migration procedure which will fix this issue.

**Comment by xsrust** [comment]
underlying issue fixed by above commit, now the migration procedure makes a customization for each org with a guidance_by_question.  it seems this commit has also introduced a new issue.  It has added extra guidance by question to the template which dosent belong to the customizing org.  I'm investigating the cause.  it should be small and fixable today though.

**Comment by xsrust** [comment]
new issue caused by a change in the guidance_by_question logic.  was previously deleting ported over guidances.  I released this logic would stop the guidances from being pulled into customizer templates.  should be fixed by checking the organisation before saving the guidance as an annotation.  Technically a different issue, but capturing within this ticket.

**Comment by xsrust** [comment]
solved by the above commit, will only be testable once @vyruss re-migrates the data to deploy to the server

**Comment by xsrust** [comment]
solved by the above commit, will only be testable once @vyruss re-migrates and deploys to the server

**Comment by sjDCC** [comment]
The guidance by question is now mapping through correctly. There is still an issue with suggested answers from other orgs displays but this is due to a known data issue that I'll fix in #381 so closing this ticket out.
![known-data-issue](https://user-images.githubusercontent.com/6169940/26844183-846ccb98-4aea-11e7-8768-2eece58cc861.PNG)
