### ISSUE TITLE
Change shibboleth link text under edit profile

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#345]
Please change the shibboleth link text back to 'Your account is linked to your institutional credentials. Click here to unlink your institutional credentials' and 'Click here to link to your institutional credentials'. That'll be clearer to end users than a reference to the UK Access Federation

Grabbing a screen capture to point this out has raised another issue - where have the links gone?
![shibboleth-link](https://cloud.githubusercontent.com/assets/6169940/26303452/a18e78be-3edf-11e7-9e03-c41493e551c7.PNG)

**Comment by vyruss** [comment]
How does _UK Access Federation (your institutional credentials)_ sound?

**Comment by alexstuart** [comment]
Since this SP uses the UK federation Central Discovery Service (CDS), and the CDS lists all the IdPs in the UK federation and eduGAIN, it's possible that people can authenticate at an IdP outwith the UK federation and link their federated account with the local account. Something like _Your account has been linked to a federated account (institutional credentials)_ might be more appropriate.

Another point is that the label for this field should not be Shibboleth, as it's not just Shibboleth IdPs that can provide authentication statements to yout SP. Formally, you'd probably want to say _SAML_ but that might not have the name recognition. And whilst the omniauth provider you're using is a shibboleth provider, that's because it links to the Shibboleth **SP** software; it's not that it can only accept authentication from a Shibboleth **IdP**. For example, SURFconext appears to have IdPs which deploy ADFS or SimpleSAMLphp software.

**Comment by vyruss** [comment]
I've been advised by @dsisu that _SAML_, _Shibboleth_ and _UK Access Federation_ all mean almost nothing to our users :)

**Comment by alexstuart** [comment]
LOLOLOL. I take your point about SAML and Shibboleth, but still, I suggest that it's best not to describe the linking as "UK Access Management Federation" when the application can be accessed by researchers who are authenticating at IdPs that are registered outside the UK federation.

**Comment by vyruss** [comment]
Done.

**Comment by sjDCC** [comment]
There's a typo in this - 'your' is duplicated. It's also misleading to suggest they can create institutional credentials
![roadmap](https://cloud.githubusercontent.com/assets/6169940/26489844/ea9d31c0-4200-11e7-8ff0-cab230ea0804.PNG)

Probably best to just have an abbreviated version of what is currently in place on the live site e.g.

Link to your institutional credentials (UK users only)
OR
Unlink your institutional credentials

![shib1](https://cloud.githubusercontent.com/assets/6169940/26489751/9f069cba-4200-11e7-863d-b2e12dcd61e6.PNG)
![shib2](https://cloud.githubusercontent.com/assets/6169940/26489750/9f05c3f8-4200-11e7-86eb-49956b4dd3ac.PNG)

**Comment by vyruss** [comment]
We have to write a generic sentence that can apply to all fed.account types. If not, we have to write code to differentiate between specifically UK Shibboleth, other federations, and everything else. How does this look?

![image](https://cloud.githubusercontent.com/assets/18707439/26496994/a170950c-4221-11e7-9eec-674f89731473.png)

**Comment by sjDCC** [comment]
Yes, that's fine. Closing out
