### ISSUE TITLE
Saving multiple choice doesn't update progress bar or question calculators

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#382]
Any entries to multiple choice questions save and export fine, but do not amend the progress indicators

In the example below I have answered 3 questions - 1 text field, 1 radio button and 1 multi-choice checkbox
![saving-multiple-choice](https://cloud.githubusercontent.com/assets/6169940/26551346/f7d67a06-4479-11e7-8f48-1f67439467c5.PNG)

**Comment by jollopre** [comment]
Three things have to be tested in this issue:
- Plan progress: The code has been refactored and the N+1 queries problem has been fixed with eager_loading.
- Section progress: The code is refactored and considers what is a valid answer adequately (e.g. for option based, having any option selected and for text/textarea having any text)
- Optimistic locking: The code has been refactored. It prompts the stale answer as readonly rather than the actual answer stored in the database as readonly.

**Comment by jollopre** [comment]
See the new approach to tackle an stale answer, i.e. two users A and B retrieve the same answer, A modifies and saves, B modifies and tries to save. B is considered stale!

[snapshot.pdf](https://github.com/DMPRoadmap/roadmap/files/1048112/snapshot.pdf)

**Comment by sjDCC** [comment]
I can confirm the first two progress updates are working. Will try to invoke the co-editing conflict tomorrow

**Comment by sjDCC** [comment]
Have tested the locking and this works well, particularly as the top box is greyed out so it is clear where they combine and save their changes.

Only request is to change the language so the first sentence says the answer 'can not be saved' rather than 'can not be persisted'
![responsepng](https://user-images.githubusercontent.com/6169940/26875757-3245d9e0-4b7b-11e7-928e-324ff48ddc3b.PNG)

Thanks @jollopre

**Comment by vyruss** [comment]
@sjDCC done
