### ISSUE TITLE
UC3: Install and configure Shibboleth

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#40]
Install the Shibboleth Service Provider on the Roadmap server and configure it to work with the appropriate federation.

References: https://www.pivotaltracker.com/story/show/131902937 and https://www.pivotaltracker.com/story/show/125268081

**Comment by briri** [comment]
Need to register new roadmap domain names with federation and point the service to the EduGain federation's list

**Comment by stephaniesimms** [comment]
Shib is working! Although I noted an unrelated issue with ORCID. Will move this along and create a new issue for the other thing.

**Comment by sjDCC** [comment]
Not sure if this is working as my freshly created account suggests I have credentials assigned (possibly as recovery email is uni one?) and the link to 'unlink' doesn't do anything. Not sure if that's because I'm from a UK federation though so not right configuration? Close out if so as it's not really one for me to test.

Here's what I see for reference. Shib link would be better alongside ORCID
![credentials](https://user-images.githubusercontent.com/6169940/27613320-ce2a454a-5b92-11e7-96f6-52c4d2285875.PNG)

**Comment by stephaniesimms** [comment]
something crazy happened with this page layout! many things are awry. will cross-check w/related issues #390 for the proper way to display ORCID info

**Comment by stephaniesimms** [comment]
Shib integration is working for UCOP account testing. Closing this issue. We will address Shib workflows and profile UI things in other issues.
