### ISSUE TITLE
Data Migration - Password Conversion Issue

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#47]
The passwords are not usable once our existing data has been migrated over from the current DCC instance to the new Roadmap codebase. 

Could be related to the Devise gem, Ruby or Rails ... all were upgraded during the creation of Roadmap.

**Comment by vyruss** [comment]
`config/initializers/devise_example.rb` gets read by Rails along with `devise.rb` instead of just the latter, causing legacy passwords from migrated databases to be invalid. Propose renaming the file to `devise.rb.example` to alleviate problem.

Incidentally, the same thing happens with `config/initializers/recaptcha_example.rb`
