### ISSUE TITLE
CSS for DMPonline

### ISSUE THREAD

**Issue by vyruss** [DMPRoadmap/roadmap#490]
This issue is for comments and updates for making the CSS in MVP look like DMPonline

**Comment by briri** [comment]
Please use the existing `dmproadmap/*.scss` files for these changes when possible. I'd like to keep the `dmproadmap.scss` very simple and geared towards branding. 
If for example the font size in the tabs needs to be made smaller or have more padding just update the relevant lines in `tabs.scss` since that change would be beneficial to everyone

**Comment by stephaniesimms** [comment]
closing this issue. no longer relevant. replaced by Roadmap CSS and individual service styling issues.
