### ISSUE TITLE
Revise Guidance on Write Plan page

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#495]
UX wireframes @JEK-III : http://h90c3m.axshare.com/#g=1&p=write_plan
- one guidance/comments portion per question, but refactoring the UI to be similar to the wireframe linked above and screenshot below
- Use a slider to switch between guidance and comments and create guidance tabs by organisation
- Related issue started as #494 and continued in #943 

![screen shot 2017-12-12 at 7 36 36 pm](https://user-images.githubusercontent.com/12703638/33920665-f891e346-df73-11e7-84e8-37aa9919428b.png)

**Comment by briri** [comment]
This one needs to be worked on with close coordination with #494 

Instead of having separate guidance/comments sections next to each answer we want a single tabbed box that is contextualized based on where the user is currently working. 
- The tabbed box should stay visible as the user scrolls up and down.
- All guidance sections should be collapsed on page load or a new section is expanded
- When a user expands a section, the following should happen:
  - The Guidance reloads. All of the themed guidance for all of the questions within the section should appear
  - All guidance/annotation sections should be collapsed
  - The comments section is cleared and any old question specific annotations should be removed
- When the user clicks on a specific answer the following should happen:
  - The comments section should reload
  - Any old question specific annotations should be removed
  - Question specific annotations should be loaded and appended to the appropriate sections
  - If a guidance section was expanded and still available to the user, it should remain expanded
  - The current tab guidance/comments should remain active (e.g. if the user had the comments tab open and clicked on a different answer then the comments tab should remain open)

**Comment by vyruss** [comment]
I'm a bit concerned with changing the layout so drastically as it's not clear how we can display "annotations" (i.e. guidance and/or example answers for specific questions) aligned alongside the question

**Comment by xsrust** [comment]
I'm confused as to why themed guidance would be displayed on a per-section basis instead of a per-question one.  Templates rarely have multiple questions with the same theme in a section.  Furthermore, unless we display the theme next to the question, it will be difficult for the user to pair guidance to questions.  

The comments tab only re-loading once the user has selected an answer box may also confuse users and require extra clicks.  I also find it difficult to understand how this layout would work for a keyboard-only user.

**Comment by briri** [comment]
@JEK-III did we decide on how to display things like question specific guidance and example answers? If I remember correctly, we were going to add them as sections to each of the org tabs if I remember correctly.
Not sure of all the use cases for displaying themed guidance per section. @sjDCC and @stephaniesimms should be able to clarify.

**Comment by stephaniesimms** [comment]
we discussed all points above during UX mtg on 12 Jul and @JEK-III is revising the wireframes accordingly. we can review them together on Tues and/or Wed calls next week.

**Comment by vyruss** [comment]
I'm not too sure about the <h3> size for guidance titles - it may be a bit too large and it also produces an indentation effect on my browser 
![image](https://user-images.githubusercontent.com/18707439/28217629-b1b55ee0-68ad-11e7-8825-2fa342a3ba0d.png)

**Comment by briri** [comment]
Convert the guidance portion of the write plan page to look like the one in the wireframe. Use a slider to switch between guidance and comments and create guidance tabs by organisation.

**Comment by xsrust** [comment]
Just to clarify, The desired work here is to continue having one guidance/notes portion per question, but refactoring the UI to be similar to the wireframe linked in the first comment?

**Comment by stephaniesimms** [comment]
yes @xsrust - we can confirm this on call today

**Comment by stephaniesimms** [comment]
discussed on call and changes confirmed. closing this issue and replacing it w/a clean one #944
