### ISSUE TITLE
Create Account: Fix styling/code issues for Organisation dropdown

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#518]
- Use the auto-complete box (see `views/plans/new.html.erb` for an example) for the org dropdown list
- Update styling (add `left-indent` class, etc.)
- Make sure JS is still working to hide/show the other org box
- Make sure that org selection is saved properly

**Comment by kmcgre** [comment]
@sjDCC @stephaniesimms 
org_id and other_organisation now being saved to database. There's no text box for other_organisation in the edit personal details page for the user so I'll add that.

What should happen if a user selects an organisation from the dropdown, clicks the link to show the other org box and enters an "other organisation"?

**Comment by sjDCC** [comment]
Thanks @kmcgre Definitely good to list the other org value in a field under edit profile

I guess your second question is about the account creation process? If so, one should overrule / clear the value for the other as people can only either a) select an org from the list or b) enter an 'other org' value. They can't have an entry for each.

Just checked on DMPonline live site and this is how it works. If I select an org from the list (screengrab 1) and then click the link for "My organisation isn't listed" the dropdown value clears and is changed to 'Other' and a box appears for entering the value (screengrab 2). The same works vice versa too.

![step1](https://user-images.githubusercontent.com/6169940/28415340-2740d11a-6d47-11e7-9736-e802099efdd9.PNG)
![step2](https://user-images.githubusercontent.com/6169940/28415347-2ae2e1a0-6d47-11e7-98a0-5631732ea6e3.PNG)

**Comment by vyruss** [comment]
@sjDCC so we would want that behaviour on the Edit profile page too, correct?

**Comment by sjDCC** [comment]
Yes, definitely. We only ever want them to have one value - an org from the dropdown list, or a text entry for 'other org'

**Comment by stephaniesimms** [comment]
I'm not clear about the expected behavior - after testing here are some notes:
- I was just able to create an account without selecting an Org. I left the field blank and was not forced to select "Other" nor did I receive an error msg. When I navigate to the Edit Profile page the box for Org is blank (screenshot below)
- When I click "My organisation isn't listed" on the Create Account page and under the Edit Profile page nothing happens. Should it autopopulate the box w/"Other" when a user clicks this link @sjDCC ? 
- the only way to successfully save my profile is to type "Other" into the box after following the error prompt 
- We should also be careful if we implement autosave throughout the site (#450) that we make exceptions for things like this that require validation  

![screen shot 2017-07-26 at 3 59 51 pm](https://user-images.githubusercontent.com/12703638/28647662-4f45b2ae-721d-11e7-8974-99965f0ca3fb.png)

**Comment by sjDCC** [comment]
OK, I think we definitely want to make the org mandatory. Ideally this would be implemented as we have it in DMPonline. Selecting 'My org is not listed' autopopulates the box with 'other' and a text box appears to enter the name. This text box also appears when you enter 'other' yourself in the dropdown list.

![capture](https://user-images.githubusercontent.com/6169940/28672217-0364682a-72d7-11e7-94dc-57ac63b3c9d0.PNG)

Agree we should be careful with autosave. It's definitely not useful on these kind of actions.

**Comment by briri** [comment]
JS on this doesn't appear to be working. No other org box is displayed when you click the link. The same also applies to the edit profile page

**Comment by kmcgre** [comment]
What browser are you using?
It's working for me on firefox and chrome but I don't have Windows so I can't try it on IE.

![image](https://user-images.githubusercontent.com/29201135/28708237-6a682790-7373-11e7-9711-b189fc5e08cd.png)

**Comment by sjDCC** [comment]
Hi @kmcgre I guess @briri is on Safari as he has a Mac

Where are you testing this? Is it on your own local deployment? 

I've just tried the code on the edit profile page on staging (https://roadmap-stg.cdlib.org) and get the same issue Brian mentioned. For IE, Chrome and Firefox, clicking 'my org isn't listed' clears the selection in the box. Choosing 'other' doesn't bring up the org name box either. Same seems to apply to 'create account' functionality.

Perhaps we have a mismatch in deployed code or something different in terms of configuration?
