### ISSUE TITLE
Remove plan_sections and add replace locking mechanism with optimistic locking

### ISSUE THREAD

**Issue by xsrust** [DMPRoadmap/roadmap#55]
Current plan_sections table is the locking mechanism for a user editing a section of a shared plan.
New system of optimistic locking to be implemented as defined [here](http://api.rubyonrails.org/classes/ActiveRecord/Locking/Optimistic.html).  

Additionally requires old locking mechanism to be removed from the javascript surrounding the edit plan page.  
Additionally requires old locking endpoints to be removed from the plans controller.
Additionally requires locking logic to be removed from the model for plans.

**Comment by briri** [comment]
Being done as part of the data model refactoring project

**Comment by raycarrick-ed** [comment]
Added lock_version to answers table. This triggers optimistic locking.
If you try to save with a lock_version < the current lock_version it throws a StaleObjectException.
When an answer is saved it calls answers#update expecting a JS response.
If the save works then the JS return only updates the lock_version otherwise the next save will fail.
An empty div is added to the answer_form partial.
If a staleObject gets caught then respionse uses this to display the conflicting answer and user.
The lock_version also gets updated so that next time the user saves it will succeed.
There's a fair amount of JS which was to do with locking which is no longer needed.
The answer timestamp also gets changed. It was working of 'created_at' rather than 'updated_at' because we used to created a new answer every time.

As part of this I have also tried to rationalise the testing of question_formats. They used to always be string comps. They now use an enum field.

**Comment by raycarrick-ed** [comment]
Commits:
https://github.com/DigitalCurationCentre/roadmap/commit/51c78fcb7271491a0f4f6dcc7407967cb34a0a9b
https://github.com/DigitalCurationCentre/roadmap/commit/2a9ceade356bd0bc49f3966f71c02b6b49c406b4
https://github.com/DigitalCurationCentre/roadmap/commit/a9cc1b2c6515e7d9ab4ee62eea0e837024af104d
https://github.com/DigitalCurationCentre/roadmap/commit/a6f2a544715d9f862b713ac48bebc07a03f241df

**Comment by briri** [comment]
looks great @raycarrick-ed. moving this on to 'Ready for PR'

**Comment by stephaniesimms** [comment]
This appears to be working as expected, however, we should consider adding a message to notify users that their answer was not saved/another user was editing the plan simultaneously. At present I receive the default timestamp message if I click Save during simultaneous editing - Answered 4 minutes ago by stephanie.simms@ucop.edu

I only discover that my answer was not actually recorded when I refresh the page. 
Would it be very complicated to add a message @raycarrick-ed ?

**Comment by raycarrick-ed** [comment]
Pulling this back to 'in progress' so I can revisit this

**Comment by briri** [comment]
this was addresses by fixes made for #241

**Comment by stephaniesimms** [comment]
The message looks great and answers save/overwrite as expected. It's still too easy to accidentally overwrite a collaborator's answer, however. In the screenshot below, if I click "Save" without deleting or combining my answer text in the lower box as advised, it overwrites the answer in the upper box.

Since we think this is an edge case, maybe it's not worth messing w/now. We can target this for future usability testing. What do you think @sjDCC ?

![screen shot 2017-04-24 at 5 26 43 pm](https://cloud.githubusercontent.com/assets/12703638/25363997/ff4fc9c6-2913-11e7-85ce-92be237b6d39.png)

**Comment by sjDCC** [comment]
Yes, I agree this is a good case for future usability testing. People are likely to just hit save so it'd be easy to overwrite without incorporating changes. I also got confused about where the new text should go - in the top or bottom box (even though the guidance is clear when I re-read!).

Perhaps we need to add an additional bit of guidance text like:

"The edits in the box below will overwrite the existing answer from [user name] once you click save"

**Comment by stephaniesimms** [comment]
@sjDCC I like your suggestion about amending the message:
"The edits in the box below will overwrite the existing answer from [user name] once you click save"

**Comment by sjDCC** [comment]
Possibly grey out top box suggested by @vyruss

**Comment by briri** [comment]
Updated the messaging per @sjDCC suggestion above and greyed out/disabled the text box to prevent further confusion.
![screen shot 2017-04-26 at 1 40 29 pm](https://cloud.githubusercontent.com/assets/1204467/25455957/5ae62758-2a86-11e7-887a-3669ed82ed96.png)

**Comment by stephaniesimms** [comment]
This looks good for now. Closing issue.
