### ISSUE TITLE
Branding generalisation

### ISSUE THREAD

**Issue by vyruss** [DMPRoadmap/roadmap#63]
Allow customisation by allowing for directories with custom branding
- [ ] Define a config variable like config.branding = 'dcc' (which need not be set)
- [ ] Modify the code so that:
  - If config.branding is unset, default to basic Roadmap page templates/images
  - If config.branding is set, read page templates/images from branding/dcc folder
- [ ] Create/adapt said templates for our basic sites (DMPOnline, DMPTool, DMPTuuli, DMPMelbourne)

**Comment by raycarrick-ed** [comment]
Tried a quick mock up of a solution to this:
* add instancename to branding.yml
* add setting a variable with this in set_locale so it's available everywhere
* set it to "roadmap" if not set otherwise
* in assets/images create sub directories for the custom logos etc
seems to work ok so far

**Comment by briri** [comment]
Ok. I think I got it working with a minimal amount of modification to the underlying codebase. Please review and merge it in if it looks like a good route.

- I did some reading up on Rails' asset pipeline and discovered that anything placed in app/assets will override content in lib/assets. So I moved our current assets to lib/assets. Now, any files that appear in app/assets would be considered overrides to the default files.
- I set the application_controller.rb to check for templates in app/views/branded/ first. This will allow us to customize templates. Keep in mind that the location of the file must match the default one (e.g. to override app/views/layouts/_header.html.erb you would create an app/views/**branded**/layouts/_header.html.erb)
- I moved the static page content out of the large locale files and placed them into a new locales subdirectory called static_pages. I placed example files into that directory.
- I updated the gitignore file so that branded content in app/assets, app/views/branded and config/locales/static_pages/*.yml will be ignored

To test things out: 
- just drop a new logo into app/assets/images/logo.jpg
- create a directory called app/views/branded and add a new projects/index.html.erb to it with 'Hello World' or something. 
- Make copies of each of the config/locales/static_pages/ files (change the contents of one if you want to test that)
- Then pull up the site and verify that your new logo is being used and then login to make sure you see the 'Hello World' page
