### ISSUE TITLE
Allow funders/orgs/institutions in Create Plan page

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#665]
Allow users to select from a Funder, Org or Institution in the Primary Research Org autocomplete box.

For example USGS, DOT and other funders who also have users creating DMPs and maintain their own templates.

**Comment by sjDCC** [comment]
Hi @briri What's the use case for including a funder in the primary research org dropdown? The create plan page has two dropdowns, the second one covering funder choices. Currently the logic is set to only include institutions and organisations in the primary research org.

**Comment by briri** [comment]
Hey @sjDCC we have instances where a funder has users who would log in and create plans but at the same time are also funders

@stephaniesimms can clarify further, I cannot recall which funders in particular would fit this profile.

**Comment by stephaniesimms** [comment]
yes for dmptool. e.g., USGS, USAID, DOT...possibly others

**Comment by briri** [comment]
Now that we've setup USGS as both a funder and org I think this ticket is no longer necessary. @stephaniesimms can you confirm?

**Comment by stephaniesimms** [comment]
that is correct. i tested on DMPTool stage and USGS use case is satisfied now. closing issue.

**Comment by sjDCC** [comment]
Hi @stephaniesimms Do you mind keeping me in the loop with what's going on here please? I can't test things on DMPTool Stage and since the Roadmap staging server is loaded with DMPonline data, USGS and DOT etc aren't covered there.

It sounds like you've now switched the approach so that hybrid organisations (i.e. funders with public and internal requirements) are entered in the database twice as two separate orgs - one as a funder and one as an organisation akin to an institution.

There's an open ticket in the UAT column related to this (#845) that I left questions for you in

**Comment by briri** [comment]
hey @sjDCC hybrid organizations do not have 2 records in the the database. they are just clasified as both a funder and an org.

**Comment by sjDCC** [comment]
Ah right - has the implementation of this been discussed on a dev call? Just trying to get my head round what it'll mean for the logic at various points e.g. where things present on create plan wizard, what view is shown on admin interface etc. Perhaps one to talk through on Tuesday?

**Comment by briri** [comment]
@jollopre actually suggested it @sjDCC. It required no code changes. The system already allows for an Org to be multiple organization types (e.g. funder/org, institution/funder/org, etc.).

**Comment by stephaniesimms** [comment]
yes we covered this on a Tues call a few weeks ago and I just closed this issue since the approach suggested by devs resolved things for our use cases (USGS especially) where there is dual funder/Org status. it now works as desired when i test on our DMP stage server that contains Roadmap code but DMPTool data for USGS templates. we can create an account for you if you'd like to test.

**Comment by sjDCC** [comment]
Yes, that would be great if you could please so I can get a sense of how it works. We don't have that use case here, but I'm conscious that many Dutch users are signed up as ZonMw rather than their own institutions since that's the main funder driving DMPs there. I want to ensure their aren't any unintended consequences for these users when we migrate.
