### ISSUE TITLE
Org branding/banner must include up to 3 links

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#729]
Related issue #726 

Org admins can provide up to 3 links on the Org details page. The branding/banner design needs to accommodate these links.

**Comment by vyruss** [comment]
Add relevant code to make these links functional:
- "`links`" JSON field to `org` to give us flexibility in what org admins store there
  - Optionally display none, one or two links with both text and link customisable
  - Flexible for future use (in case we ever need more than 2 links per org).
- Code in view for layout and to make sure we only display existing links

**Comment by stephaniesimms** [comment]
Note that these links should open in a new tab. Currently they open in the same window/tab.

**Comment by sjDCC** [comment]
Will these links have icons like in the DMPTool? e.g.
![icons](https://user-images.githubusercontent.com/6169940/33175484-d9a9f63c-d053-11e7-982c-12d595266442.PNG)

I think it would be good to include this. The contact email could have the chat bubbles and any standard links the computer icon. Without them it may not be obvious that these are links to support as it just shows as text
![roadmap-stage](https://user-images.githubusercontent.com/6169940/33175550-01d32b1a-d054-11e7-9122-2aad498c7e2f.PNG)

**Comment by vyruss** [comment]
Temporarily blocked by #866

**Comment by stephaniesimms** [comment]
created issue #904 to report double redirect bug. please delete it if unnecessary/covered by #866

**Comment by sjDCC** [comment]
Tested this for Edinburgh and it looks fine

![banner](https://user-images.githubusercontent.com/6169940/34524248-b78d9982-f092-11e7-8f77-e88578b370f6.PNG)

I did generate the following error when adding the links though. It's seems there's a fairly restrictive character count so it wouldn't allow my entry of "Research Data Services" for the second link
![error](https://user-images.githubusercontent.com/6169940/34524283-da44775c-f092-11e7-81e2-d2c26ea29ac8.PNG)

Ideally we would increase the length allowed to c.40 characters and better noticing is needed. Please add a tooltip to state the character count and an error message that explains why save is disallowed instead of generic warning.

**Comment by briri** [comment]
ah yes, we discovered this restriction a few weeks ago. Its related specifically to MySQL and would likely be something that our collaborators would encounter. 
@bhavi, you were looking into removing the 255 char restriction on our VARCHAR table columns before the holiday break. Did you find a solution that we can run on roadmap-stg?

**Comment by sjDCC** [comment]
Thanks @briri It seems to be even shorter than than on this page - c.20 characters - so probably a setting we've applied rather than a MySQL thing.

Interestingly I was testing the funder links page too and the same input form fields there allow for much longer link text. Ideally the two would match, unless banner space restrictions mean we need to limit this one.

**Comment by briri** [comment]
Interesting that you're getting it after 20 characters. I just added a bunch myself and am not having any issues until I end up exceeding the 255 limitation (all the links and their text are stored together in a single column as `{"org":[{"link":"http://google.com","text":"Google"},{"link":"http://test.org","text":"Test"}]}`).
![screen shot 2018-01-03 at 8 51 06 am](https://user-images.githubusercontent.com/1204467/34530327-a8264c98-f063-11e7-886d-5972cc2ecdf3.png)

Older versions of MySQL had a very limited size for the VARCHAR field. The current versions of that database allow for much larger values (on par with Postgres now) but since the original databases we're starting from were on older versions the limitations remain in place. Anyone migrating from dmponline_v3 (and using MySQL) would likely run into the same situation so we'll record the fix for this in the migration documentation on the wiki.

**Comment by sjDCC** [comment]
Great, ta. "Research Data Services" was disallowed so i guess it must be somewhere in the region of 20 characters.

**Comment by vyruss** [comment]
@sjDCC it doesn't have to do with the length of the text - it's just that there's a 255 character limit for old MySQL versions for the _entirety_ of the "links" data (including URLs) - that can be solved by changing the column type from VARCHAR to TEXT I believe.

**Comment by sjDCC** [comment]
Hmm you're right @stephaniesimms that's weird. Have added this to the agenda for today

**Comment by stephaniesimms** [comment]
the links are back! closing issue.

**Comment by sjDCC** [comment]
Looking good. Removing from board.
