### ISSUE TITLE
Sign In from Public DMPs page opens a public plan PDF

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#764]
I clicked the link in the top right to Sign In from the Public DMPs page, entered my credentials in the modal, and when I clicked the button to Sign In I landed on Brian's public plan PDF (screenshot below). When I reload the app I have been signed in successfully.

![screen shot 2017-10-22 at 4 31 04 pm](https://user-images.githubusercontent.com/12703638/31862918-9922b098-b746-11e7-8fba-b6908cd613b2.png)

**Comment by briri** [comment]
Some more info on this issue. If your are not signed in, go to the Public Plans page. Click one of the download PDF links. Close the PDF tab/window. Click on the Sign In link. Fill out your credentials and hit the 'Enter' key. 

The PDF link in the background has focus so hitting 'Enter' in effect clicks that link not the 'Sign In' button. Update the modal logic to correct this.

**Comment by jollopre** [comment]
The root cause of the problem comes from application_controller.rb action store_location. This method updates session[:previous_url] anytime the URL changes. For example, I'm in public plans page:

1. Click to download a PDF in a new tab
2. Click Sign in popup
3. Fill out username and password
4. Click Sign in button or press Enter key

Step 1 updates session[:previous_url] with the link of the PDF I clicked to download and therefore the user is redirected to that URL when the method after_sign_in_path_for in application_controller is invoked.

Solution: Using request.referer, we always make sure to redirect to the URL that initiated the request to sign_in and moreover there is no need for using session variables since they are EVIL.

**Comment by stephaniesimms** [comment]
this is working as expected now. closing.
