### ISSUE TITLE
Check preferences before sending emails

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#811]
Update the logic for each email to first check the user's preferences to determine whether or not an email should be sent.

**Comment by jollopre** [comment]
The PR #850, addresses a subset of conditional emails that we are sending. The following table shows any message we are sending and how they relate to the notification preferences in the user profile. Note, emails from devise regarding sign up, forgot password, etc are not displayed here since I'm assuming they have to be sent always. 

We have some emails that are sent regardless of any condition (e.g. status TODO?) as well as some conditional emails that need clarification (e.g. status NEEDS CLARIFICATION). @stephaniesimms and @sjDCC, please can you give me a sense for these TODO? and NEED CLARIFICATION

Notification preferences | key associated (branding.yml) | Email subject | Status
------------ | -------------|------------ | -------------|
A new comment has been added to my DMP | users.new_comment | %{tool_name}: A new comment was added to %{plan_title} | DONE
A plan has been shared with me | users.added_as_coowner | A Data Management Plan in %{tool_name} has been shared with you | DONE
Admin privileges granted to me | users.admin_privileges | Changed permissions on a Data Management Plan in %{tool_name} | NEEDS CLARIFICATION
My DMP's visibility has changed | owners_and_coowners.visibility_changed | DMP Visibility Changed: %{plan_title} | DONE
An organisation template is published | admins.template_published | NOT FOUND | TODO?
An organisation template is unpublished | admins.template_unpublished | NOT FOUND | TODO?
A user has requested feedback on a DMP | admins.feedback_requested | %{application_name}: %{user_name} requested feedback on a plan | DONE
NOT FOUND | NOT FOUND | Feedback confirmation message (can be customised by orgs) |  TODO?
NOT FOUND | NOT FOUND | API rights in %{tool_name} | TODO?
NOT FOUND | NOT FOUND | Permissions removed on a DMP in %{tool_name} | TODO?

**Comment by sjDCC** [comment]
Here are my thoughts. @stephaniesimms can confirm too

Email subject / notification  | Who to send to and when |Comments 
------------ | -------------|------------ | 
 new comment has been added to my DMP| Alert owners and co-owners to change | Should be able to configure on email notification preferences|
A plan has been shared with me|Alert user that DMP has been shared and by whom. Email should confirm rights e.g. co-owner, editor, read-only | Shouldn't be able to opt out of this. No conditions - should send irrespective of preferences |
Admin privileges granted to me|I find the descriptions in columns 1 and 4 ambiguous and contradictory. Is this alerting a user that they now have org-admin rights or that their permissions relating to a plan have changed? We have an email about the latter but don't alert about the former afaik. User should definitely be alerted whenever permissions on a plan have been removed or changed |No conditions - should send irrespective of preferences |
My DMP's visibility has changed|Alert owners and co-owners to change | Should be able to configure on email notification preferences|
An organisation template is published|Alert org admins? | Is this one necessary?|
An organisation template is unpublished|Alert org admins? | Is this one necessary?|
A user has requested feedback on a DMP|Alert contact email specified | No conditions - should send irrespective of preferences |
Feedback confirmation message (can be customised by orgs)|Send this email to user who has requested feedback|No conditions - should send irrespective of preferences |
API rights in %{tool_name}|Send email to user who has been granted API rights|No conditions - should send irrespective of preferences |
Permissions removed on a DMP in %{tool_name}|

**Comment by stephaniesimms** [comment]
@sjDCC @jollopre - I addressed the TODO and NEEDS CLARIFICATION items below. some of the Comments in sarah's reply above for DONE items are incorrect (some are configurable) but those are already DONE and working as expected after UAT as far as i can tell.

Notification preferences | key associated (branding.yml) | Email subject | Status
------------ | -------------|------------ | -------------|
A new comment has been added to my DMP | users.new_comment | %{tool_name}: A new comment was added to %{plan_title} | DONE
A plan has been shared with me | users.added_as_coowner | A Data Management Plan in %{tool_name} has been shared with you | DONE
Admin privileges granted to me | users.admin_privileges | Changed permissions on a Data Management Plan in %{tool_name} | NEEDS CLARIFICATION
My DMP's visibility has changed | owners_and_coowners.visibility_changed | DMP Visibility Changed: %{plan_title} | DONE
An organisation template is published | admins.template_published | NOT FOUND | TODO?
An organisation template is unpublished | admins.template_unpublished | NOT FOUND | TODO?
A user has requested feedback on a DMP | admins.feedback_requested | %{application_name}: %{user_name} requested feedback on a plan | DONE
NOT FOUND | NOT FOUND | Feedback confirmation message (can be customised by orgs) |  TODO?
NOT FOUND | NOT FOUND | API rights in %{tool_name} | TODO?
NOT FOUND | NOT FOUND | Permissions removed on a DMP in %{tool_name} | TODO?

**Comment by stephaniesimms** [comment]
ADMINISTRATOR PRIVILEGES GRANTED

Email title: Administrator privileges granted in [TOOL NAME]

Hello [USER NAME]

You have been granted administrator privileges in [TOOL NAME]: [LIST PERMISSIONS]. More information about administering the [TOOL NAME] for users at your institution is available at [HELP PAGE URL]. 

All the best
The [TOOL NAME] team

Please do not reply to this email. If you have any questions or need help, please contact us at [HELPDESK EMAIL] or visit [CONTACT US URL]

**Comment by stephaniesimms** [comment]
Email title: Permissions removed on a Data Management Plan in [TOOL NAME]

Hello [USER NAME]

Your access to ["PLAN TITLE"] has been removed by [PLAN OWNER USER NAME].

All the best
The [TOOL NAME] team

You may change your notification preferences on your profile page. Please do not reply to this email. If you have any questions or need help, please contact us at [HELPDESK EMAIL] or visit [CONTACT US URL].

**Comment by stephaniesimms** [comment]
Email title: API rights in [TOOL NAME]

Hello [USER NAME]

You have been granted permission by your organisation to use our API. Your API token and instructions for using the API endpoints can be found at: https://github.com/DMPRoadmap/roadmap/wiki/API-Documentation.

All the best
The [TOOL NAME] team

Please do not reply to this email. If you have any questions or need help, please contact us at [HELPDESK EMAIL] or visit [CONTACT US URL].

---
Email title: Permissions removed on a Data Management Plan in [TOOL NAME]

Hello [USER NAME]

Your access to ["PLAN TITLE"] has been removed by [PLAN OWNER USER NAME].

All the best
The [TOOL NAME] team

You may change your notification preferences on your profile page. Please do not reply to this email. If you have any questions or need help, please contact us at [HELPDESK EMAIL] or visit [CONTACT US URL].

**Comment by stephaniesimms** [comment]
all email notices i've tested seem to be working as expected. thanks for hooking up all the things @jollopre - closing this issue.
