### ISSUE TITLE
Add links to table and database for Funder/DMP Templates

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#819]
- Revise DMP Templates table to include additional columns for Funder Links and Sample Plans as in screenshot from DMPTool below
- Add fields for a URL and link text to link out to official funder requirements pages
- Add fields for links to sample plans if provided by funder
- Add fields to Create/Edit Templates page - options in screenshots below...

![screen shot 2017-11-13 at 4 26 44 pm](https://user-images.githubusercontent.com/12703638/32756578-b0fef05a-c88f-11e7-8c62-61f3fc50131d.png)
 (optional)

@sjDCC which page do you think is best for adding these fields for funder template editing pages?

Create New Template OR
![screen shot 2017-11-13 at 4 46 13 pm](https://user-images.githubusercontent.com/12703638/32757094-85769246-c892-11e7-9e10-4c2fd9f5bbe2.png)

Edit Template Details
![screen shot 2017-11-13 at 4 46 55 pm](https://user-images.githubusercontent.com/12703638/32757096-87ec2e1e-c892-11e7-954f-bcc62f462b12.png)

**Comment by sjDCC** [comment]
Hi @stephaniesimms I think we have to be careful here as these fields only apply to funder templates, not all templates. I don't want standard org-admin users getting confused if they're presented fields that have no meaning to their context.

If we can differentiate when a template is being created for a funder as opposed to an organisation, then I think we should add these fields to the edit template details page. It would probably break the flow if we add them to the create a new template page as we're forcing the user to think about the public view of this before they've even created their template. In time (i.e. post MVP) we maybe want to set an alert/pop-up to remind the user to fill these fields in when they go to publish a funder template, otherwise they could be easily overlooked. The fields need tooltips as well so users know what info is required and where it will be presented e.g.

Funder links: Place one or more links here to share your data policy and/or DMP requirements on the public "DMP Templates" [Make this text a link] webpage.

Sample plans: If you provide example plans, place links here to display on the public "DMP Templates" [Make this text a link] webpage.

I guess we can differentiate when a plan is for a funder by the owning organisation i.e. the MRC template belongs to the Medical Research Council. @vyruss would we be able to identify the owner at template creation and only display these additional fields when it is a funder? I assume this is derived by the creators affiliation?

Will any of this be affected by the new superadmin controls e.g. in #813 Currently when I edit the MRC template, I change my affiliation to MRC first. If superadmins can create/edit all templates directly, this won't affect ownership of them will it? i.e. a new funder template that I create via the superadmin panel will still belong to that funder not DCC because it's inherited my org. Or do we need to introduce a step to associate templates to orgs if created via superadmin?

**Comment by stephaniesimms** [comment]
yes @sjDCC the fields only apply to funder templates and should be avl based on template owner affiliation. the fields should also be avl in the Funder Templates tab of the Super Admin area. the purpose of "Funder Links" and Sample Plans" link fields is straightforward to DMPTool users who are funders that manage their own templates - but we can add a tooltip if necessary.

Super Admin privileges should include editing all templates including funder templates. So you won't have to change your affiliation. But we do need to have the ability to create a new funder template, which i assume can be copied from code/process to create a new Org template. devs can discuss implementation details.

**Comment by sjDCC** [comment]
Yeah I think the tooltip is worth it for new funders or ones who administer templates in DMPonline as this will be new to them.

When creating a template via superadmin, we probably need to display the org-field to set ownership so it's not derived from us

**Comment by briri** [comment]
add a json column to the templates table that stores 2 arrays of links one for 'Funder Links' and one for 'Sample Plans'.

**Comment by stephaniesimms** [comment]
I lied - we do have tooltips (screenshot below). Proposed text for: 
- Funder Links Tooltip: Add links to funder websites that provide additional information about the requirements for this template.
- Sample Plans Tooltip: Add links to sample plans if provided by the funder. 

![screen shot 2017-11-20 at 1 17 24 pm](https://user-images.githubusercontent.com/12703638/33042100-8a802b36-cdf5-11e7-847a-3cd39588a8be.png)

**Comment by stephaniesimms** [comment]
i'm assuming the json columns have been added on the backend for funder links and sample plans @jollopre? i can't test this. but if that piece is done i'll create a new issue to add these fields to the UI.

**Comment by jollopre** [comment]
@stephaniesimms yes, we have this mechanism in place on the back end. I didn't add the links to the UI (list of templates) because was not sure where was best. Please, feel free to add a new ticket explicitly saying where do you want those links to appear. Thanks

**Comment by sjDCC** [comment]
This looks good @jollopre and those new fields only display on funder templates which is what we want. I've raised a ticket about the public display #880 so am closing this out
