### ISSUE TITLE
Clarify roles terminology across front end UI and code

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#851]
@jollopre flagged that we use different terminology in the front end UI and code which will make it hard for externals to follow and contribute. For example the read-only permission when sharing a plan is 'commentor' access in code. Or editor, is admin in code.

Ideally we would standardise these post MVP

**Comment by stephaniesimms** [comment]
@sjDCC checking in again to see if this is still an issue?

**Comment by jollopre** [comment]
Yes, it is still an issue. We got roles such as:
- creator
- administrator
- editor
- commentor
- reviewer
and after we have methods like:
- owner (users with role creator)
- owner_and_coowners (users with role creator or administrator)
- readable_by? (check whether or not the user has the role commentor)

**Comment by briri** [comment]
closing this one since we now have a full set of methods on the Plan model which should help clarify things:
- `readable_by?(user)`
- `commendable_by?(user)`
- `editable_by?(user)`
- `administrable_by?(user)`
- `reviewable_by?(user)`
- `owner` - returns the owner (obeying whether or not the role is still active
- `owner_and_coowners` - returns the owner and coowners
- 'authors` - returns owner, cowers and administrators
