### ISSUE TITLE
Phases are not very clear to navigate when writing a plan

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#859]
The way phases are represented is not very clear now when writing a plan as the tab name changes to 'write plan' and you have to navigate back to 'project details' to see the different phases and click into one to edit.
![testing phases](https://user-images.githubusercontent.com/6169940/33173187-14820a8c-d04b-11e7-9c1d-ebe0fb9e65cd.PNG)
![testing-phases-2](https://user-images.githubusercontent.com/6169940/33173192-18930266-d04b-11e7-987d-af98fcd6ab85.PNG)

For consistency can we ensure the tab titles remain the same throughout please? This is how it's represented in edit mode on DMPonline

![dmponline](https://user-images.githubusercontent.com/6169940/33173292-86b2333e-d04b-11e7-8517-6a7a1f677929.PNG)

**Comment by briri** [comment]
Hey @sjDCC, are the two screenshots from the same plan (it appears so based on the plan title)? 

We switched to show 'Write Plan' when there is only one phase for the template otherwise it will show the individual phase names (or should be). If that is the correct behavior it looks like we just need to ensure that all of the phase names are passed into the view.

**Comment by sjDCC** [comment]
Happy for 'write plan' to replace the phase name when there's only 1, but it replaces it when there are 2+ themes too so you lose the ability to switch between without navigating back to 'project details' where the different phases show. I think where there is more than one theme, the names given by the template owner should be retained instead.

**Comment by sjDCC** [comment]
Looks good. Closing out
