### ISSUE TITLE
Commenter should not be able to edit Tinymce boxes

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#872]
Please complete the following fields as applicable:

**Expected behaviour:**
The Tinymce editor should be disabled on the write plan page (or perhaps just show the answer text if that is not possible)
when the current user is a commenter

**Actual behaviour:**
The save button is disabled but the user can change the contents of the answer boxes

**Steps to reproduce:**
Share your plan with another account as a 'read-only' commenter and then login and access that plan as the commenter.

**Comment by jollopre** [comment]
@briri, the user can change the text however this does not update anything on the server since there are not events associated.

**Comment by stephaniesimms** [comment]
the user should not be presented with the option to change/edit text at all since they've only been granted read only access and been asked to leave comments. even if they can't save changes, this is confusing.

**Comment by sjDCC** [comment]
It's no longer possible to edit in read-only mode so this is fixed and good to close out. 

It's not entirely obvious at first glance since the editable area and save button still display so we may want to change it to a very static view like on DMPonline to improve usability in future, but that's not essential for now.

![grey-out](https://user-images.githubusercontent.com/6169940/33551073-1ed29cfe-d8e8-11e7-8a18-8b504cb98f9c.PNG)
![grey-out-2](https://user-images.githubusercontent.com/6169940/33551074-1ee636ce-d8e8-11e7-9286-39538d494924.PNG)
