### ISSUE TITLE
Create template layout adjustments

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#874]
Layout adjustments to standardize template creation/editing page:

Phase layout:
- reduce "Order of display" box to half column width
- shorten TinyMCE editor box to standard size (it's too long)
- Move Save and Cancel buttons to lower right
![phase-layout](https://user-images.githubusercontent.com/12703638/33338812-0a240d3a-d42c-11e7-8a2b-969543be9f3a.png)

Section layout:
- reduce "Order of display" box to half column width
- Description box should be standard TinyMCE editor box (same as phase editor)
- Buttons should be "Save" and "Cancel" across all sections (change "Delete" to "Cancel" here)
- Move Save and Cancel buttons to lower right
- Align Save/Cancel buttons with Add Question button below
![section-layout](https://user-images.githubusercontent.com/12703638/33338907-5edb7156-d42c-11e7-818b-ef8adc602ec4.png)

Question layout:
- place all form headings above the field/editor for consistency 
- reduce "Question number" box to half column width
- reduce "Answer format" dropdown to half column width
- reduce "Themes" dropdown to half column width
- reduce width of all TinyMCE editors to be same/standard for all areas of page (Phase, Section, Question)
![question-layout](https://user-images.githubusercontent.com/12703638/33339071-cbb01944-d42c-11e7-99c5-d09b1988fb2d.png)

Section/Question layout:
- align all fields in a single column

![section-question](https://user-images.githubusercontent.com/12703638/33340141-1dbb62fe-d430-11e7-95f8-a156499781b0.png)

Button alignment:
- align all buttons on lower right below entry fields
 
![button-alignment](https://user-images.githubusercontent.com/12703638/33340205-565199da-d430-11e7-8f89-8fe08900ee36.png)

Edit Question:
- when I click button to Edit Question, I'm taken to a screen w/a different layout from the Add Question page. these should be the same layout w/standardized field and editor sizes.
 
![edit-question](https://user-images.githubusercontent.com/12703638/33340324-b01c9802-d430-11e7-8e5e-852fbe3ce11d.png)

Edit Question Buttons:
- remove "Delete button" - should only have Save and Cancel buttons here

![edit-q-buttons](https://user-images.githubusercontent.com/12703638/33340455-f8a6e49c-d430-11e7-866e-2f54929f3217.png)

**Comment by stephaniesimms** [comment]
standardized widths and button placements look much better @bhavi - just one change for now:
- move Add Question button to the lower right (same position as Add Section button) and place below last question for each section. clicking the button would then open the new question editing area in the expected location, below any existing questions.
- in the screenshot below, the Add Question button should go below the Save/Cancel buttons if there is no existing question

![screen shot 2017-12-01 at 11 58 42 am](https://user-images.githubusercontent.com/12703638/33501215-a34a46d0-d690-11e7-96e6-646eb5ac0365.png)

**Comment by sjDCC** [comment]
This looks good @bhavi and most things are working. I spotted a couple that still need work, noted below:

The 'add question' button is mis-located. From @stephaniesimms earlier screengrab it used to be on the right and would probably be best in alignment with 'add section'

![add-question](https://user-images.githubusercontent.com/6169940/33600877-7baa6226-d9a2-11e7-9d07-632444e34137.PNG)

The section and question boxes aren't in alignment
![section-question-not-aligned](https://user-images.githubusercontent.com/6169940/33600902-89a774d6-d9a2-11e7-966a-d8df3ef4966b.PNG)

There was a request to remove the "Delete button" under 'edit question'. This doesn't appear to be done, which is good because I think the user needs an ability to delete questions.

@stephaniesimms final comment was to align add question and add section buttons. This doesn't appear to be done, and we have duplicate 'add section' buttons.
![add-section-question](https://user-images.githubusercontent.com/6169940/33601268-9a648f1a-d9a3-11e7-8af5-565e6f7d8f66.PNG)

**Comment by stephaniesimms** [comment]
@bhavi - the Cancel/Delete button issue we had is probably my fault for asking you to tinker w/buttons on the edit Questions page. @sjDCC 's additional comments above may not refer to the latest code since we haven't merged the templates page deployed on DMPTool stage. i'm going to close this issue & copy new comments to a new layout issue. i have additional feedback to add. all new items can be addressed after merging the new templates page.

**Comment by briri** [comment]
FYI the cancel button issue is addressed as part of PR #902
