### ISSUE TITLE
Template table revisions

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#900]
For Org Admins, tabs on the Templates page should read:
- Own Templates
- Customizable Templates - note that this table includes the default template (mark the template name w/an asterisk)
- Org Admins should not be presented w/the box to Change affiliation. They can perform all Actions on their own templates, but can only customize funder templates.

For Super Admins, tabs on the Templates page should read:
- Organisation Templates
- Funder Templates - note that this table includes the default template (mark the template name w/an asterisk)
- Add "Customise" to Actions menu for Funder Templates and enable Super Admins to add customisations to these as well as edit them (DMPTuuli use case)

Global adjustments for both Org and Super Admin views of templates page:
- Add sort functionality to Funder templates table
- Add total template counts above each table as in the DMPTool (screenshot below). Provide the total n for: "All" templates, "Published" templates, and "Unpublished" templates in each table.

![screen shot 2017-12-05 at 11 48 34 am](https://user-images.githubusercontent.com/12703638/33627417-4db649a6-d9b2-11e7-8ad4-40c06930b89e.png)

**Comment by briri** [comment]
Moving 'Add total template counts above each table as in the DMPTool (screenshot below). Provide the total n for: "All" templates, "Published" templates, and "Unpublished" templates in each table.' to a separate ticket as it requires #815 to be complete

**Comment by briri** [comment]
Hey @sjDCC and @stephaniesimms,
I implemented the changes requested above, but the logic behind it is getting quite complicated and fragile (e.g. show these links when the user is super admin and the org is not a funder ... etc.). 
So I decided to experiment with a suggestion @xsrust made when we originally started talking about this consolidated template admin page. The behavior in this version is identical for the 'Own templates' and 'Customizable templates' tables for both super admin and org admins. The super admin though now has an additional tab called 'All templates' (Sam's suggestion) which always shows all the templates regardless of who they are affiliated with. For the super admin I am showing 'Org name's templates' instead of 'Own templates' to help the user understand who they are editing as.
Let me know what you think of the screenshots below they show what the page would look like for an Org Admin and then a Super Admin affiliated with the same Org:

![screen shot 2017-12-22 at 11 15 47 am](https://user-images.githubusercontent.com/1204467/34310154-9c528ba0-e70a-11e7-8ef7-ed2270daa0e7.png)
Logged in as an Org Admin and viewing my own templates

![screen shot 2017-12-22 at 11 40 02 am](https://user-images.githubusercontent.com/1204467/34310591-37f5cf52-e70d-11e7-8a24-2f3614e22a88.png)
Logged in as an Org Admin and viewing customizable templates

![screen shot 2017-12-22 at 11 16 41 am](https://user-images.githubusercontent.com/1204467/34310129-8232bbe6-e70a-11e7-8515-73c1f4985626.png)
Logged in as a Super Admin and viewing ALL templates

![screen shot 2017-12-22 at 11 16 59 am](https://user-images.githubusercontent.com/1204467/34310130-824c1ee2-e70a-11e7-928a-94893e1cdc60.png)
Logged in as a Super Admin and my own templates (for the org I am affiliated with)

![screen shot 2017-12-22 at 11 39 25 am](https://user-images.githubusercontent.com/1204467/34310597-45ef5718-e70d-11e7-8c59-d35dd46c56a4.png)
Logged in as a Super Admin and viewing customizable templates (for the org I am affiliated with)

**Comment by sjDCC** [comment]
Hi @briri I agree that things have got really complicated and bit fragile logic-wise in condensing the org-admin and super-admin views. It's also going to make it more difficult for @stephaniesimms and I to take screengrabs for user guides as the only way to really view something as an org admin now is to have an account without super-admin privileges.

I think the suggestion here works well as it keeps the standard org admin functions in separate tabs to super-admin stuff. Rather than a single "All templates" tab, it would probably be more useful to have a "All funder" and "All org templates" or if we're adding the filters noted in #955 I guess we could have a 'Funder' and 'Organisation' filter at the top of the 'All templates' tab

**Comment by stephaniesimms** [comment]
Echoing my comments in #955 that I like the All Templates tab approach. If filtering works out there it would be great to include @sjDCC 's suggestion to separate Funder (Published/Unpublished) and Org (Published/Unpublished) templates for that tab, but this is not critical for MVP.

Re screenshots for user guides, I always use a test account or adjust my privileges to be an Org Admin for DMPTool.

**Comment by stephaniesimms** [comment]
all changes to templates tables noted in related issue #955 - closing this one but leaving here just in case.
