### ISSUE TITLE
Add functionality to delete/remove themes

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#939]
Super Admins need a way to remove the themes. After discussion we agreed the easiest/best way is to add a Delete button when editing a theme record. So in the screenshot below, insert a new button on lower right in the order: Save - Delete - Cancel. When a user clicks "Delete" include the confirmation message step "Are you sure you want to delete..."
 
![screen shot 2017-12-12 at 7 15 28 pm](https://user-images.githubusercontent.com/12703638/33920076-da1f0680-df70-11e7-8fd6-9b0a140d9ec8.png)

**Comment by sjDCC** [comment]
Yes, agree. #3 sounds best

**Comment by stephaniesimms** [comment]
all working as expected. but the banner msg made me LOL. please revise the msg text @jollopre to the following:

"Notice: Successfully deleted your theme."

**Comment by sjDCC** [comment]
This looks good and works well.

I noticed that we have the existing themes in Roadmap, not the new ones. This is probably because it's DMPonline data. Do we need to add a separate ticket to migrate to / implement new ones? Here's a summary of the mapping from one to another in case that helps.

[DMP-theme-migration-2018.docx](https://github.com/DMPRoadmap/roadmap/files/1568501/DMP-theme-migration-2018.docx)
