### ISSUE TITLE
Finish Project Details page - including Guidance section

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#943]
@briri on steps to complete #491. Alright, I reviewed the ticket and here's what's left to do:

- Fix spacing between the 'mock/test project' checkbox and the input elements above and below it. It currently encroaches on 'Funder'
- Make sure that only the first word in the field labels is capitalized (except for 'ORCID iD' which is the official name for that)
- Finish implementing the guidance section. Note that it may be difficult to introduce a typeahead style autocomplete box like we use for Orgs since this list deals with a combination of Org name and Guidance Name (e.g. University of Edinburgh: Roslin Institute vs University of Somewhere Else: Somewhere Else guidance). If it proves to be very difficult I would recommend coming back to the team with a recommendation on an alternative implementation (e.g. a modal window that lists out all of the possibilities in several columns.
- Please also move the migrate:plan_data_contacts rake task to the bugfix.rake rake task (maybe also rename that file to 'upgrade.rake') and add it as a task that gets run for v1.0. This extracts phone numbers and emails out of the old DMP contact info field and places them in the appropriate new columns and would need to be run by anyone upgrading.

Functional specs for Guidance section (blue notepad in screenshot):
- This list should always include:
[x] plan funder
[x] plan organization
[  ] user's organization if different from plan
[x] DCC/CDL generic guidance
- Plan funder should be selected and disabled– users can't turn it off.

![screen shot 2017-12-12 at 7 27 23 pm](https://user-images.githubusercontent.com/12703638/33920389-87238670-df72-11e7-911c-6192d48dc913.png)

**Comment by briri** [comment]
@bhavi Please disregard the instruction above that says 'Plan funder should be selected and disabled– users can't turn it off.'
The write plan page always shows question level guidance from the funder (aka annotations). The user cannot toggle those on or off. They should be able to uncheck the funder from the list on this page because it will allow them to turn off the themed guidance from the funder.

**Comment by stephaniesimms** [comment]
changes are looking good. two things i noticed that need attention:
- there's no restriction on the number of guidance boxes i can tick. restrict total guidance selections to 6 per the instructions.
- there's a usability problem when a user wants to save changes to guidance selections. the Save Selections button is straightforward when I click to expand the full list, but if I make any additional changes on the main Project details page it's not clear that I have to scroll down and click the Submit button. we need to tighten up the layout on this page anyway so users don't have to scroll down to find the Submit button. but it needs to be associated w/the guidance selection area too somehow. i'll consult w/UX and offer a solution by Mon.

**Comment by stephaniesimms** [comment]
same couple of issues persist for guidance selection @briri :
- default/DCC guidance appears in the main list on Project Details page but is not ticked. This should be selected by default.
- I can check more than 6 boxes, seems there is no limit (we should provide an error msg if a user selects more than 6 and tries to save the selection)

1 - DCC should be checked by default
![dcc-check-default](https://user-images.githubusercontent.com/12703638/36115790-0151b25e-0fe9-11e8-9bd1-af8237217f1a.png)

2 - Way more than 6 guidance selections 
![many-things](https://user-images.githubusercontent.com/12703638/36115809-13456514-0fe9-11e8-994b-ebf2f66e701e.png)

**Comment by stephaniesimms** [comment]
I noted some cosmetic issues with guidance names in related issue #944 
Everything in this issues appears to be working as expected. Closing but leaving here for @sjDCC to confirm. Of particular note: need to confirm that the hierarchical presentation of e.g. Edinburgh guidance is acceptable.

**Comment by sjDCC** [comment]
I'm reopening this as I found a couple of issues.

We've suggested a solution to the guidance display / hierarchy issue in ticket #944 so that should resolve this.

My main question related to the work in this ticket is the workflow to save selections. It's not clear what to do when you've clicked to 'see the full list' and made changes in the modal. Can we auto-save them or present this list outwith a separate window so the save button is on the same page? I thought we'd redesigned this page so it was on a single save button but we still have two - one for guidance selections and another for plan details?

The deselection of guidance or changing choices saved doesn't seem to work. I can untick selections but submitting changes doesn't remove these. I tried deselecting some and choosing others, but on 'submit' it retained old values and added new, leaving me with more than the permitted 6 choices. This seems to have jammed the selections now -  I can deselect choices but not amend them for other ones. Re-saving via the 'submit' button doesn't remove those deselected.

![guidance-deselection](https://user-images.githubusercontent.com/6169940/36150662-47907ce0-10bc-11e8-91f8-285aac777850.PNG)

**Comment by stephaniesimms** [comment]
i created a new issue for the usability issues to address post MVP #1154 

for now we just need to enable users to deselect guidance. current behavior prevents me from selecting more than 6 items as expected. but if try to deselect anything at any point and click Submit, the boxes return to being ticked. please fix to allow delection and saving changes @briri .

**Comment by stephaniesimms** [comment]
@briri - i can deselect and save guidance now. but some other weird things are happening:
- i can check more than 6 things now (screenshot 1)
- when i click the x to close the modal I don't see my selections in the guidance list
- if I click Submit, then it does add my selections to the list (all of them)

desired behavior is to allow a max of 6 selections (this was working before) and to add the checked items to the list on the main guidance page when i close the modal but before I click Submit (was also working before).

![screen shot 2018-02-22 at 10 12 40 am](https://user-images.githubusercontent.com/12703638/36556225-536a177a-17b9-11e8-90fd-08a4c0c8ee6c.png)

**Comment by stephaniesimms** [comment]
everything working as expected now. just noting that outstanding issue to resolve hierarchy/guidance subsets is documented in a post MVP ticket. and clicking guidance tabs still results in jumping to the top of the page - this is a bootstrap problem that deserves attention post MVP also. closing this issue.

**Comment by sjDCC** [comment]
Guidance selections working nicely. Well done @briri Removing from board.
